### ISSUE TITLE
Progress percent for Hashing state

### ISSUE THREAD

**Issue by catholic** [alanmcgovern/monotorrent#180]
It would be great to have progress percent running during Hashing State

Some times Hashing takes minutes to complete and it could be useful to give users information that there is no hang happened and work is in progress

**Comment by alanmcgovern** [comment]
Yup, that makes sense. The library currently hashes pieces in a single-threaded way and always hashes from 0 -> end of torrent. You can calculate the progress relatively easily by doing:

```
TorrentManager.PieceHashed += (o, e) => {
    var progress = (float)e.PieceIndex / e.TorrentManager.Bitfield.Length;
};
```

In addition to that, I was experimenting with `TorrentCreator` recently to see if multi-threading hashing was beneficial. I've found that it was beneficial so I am likely to refactor that hashing logic and share it between `HashingMode` and `TorrentCreator`. If I do eventually make that change then I will definitely need to add an actual property representing the hashing progress as a simple calculation like that won't work.

Alternatively, you can just implement a counter and count the number of `PieceHashed` events which are raised. Something like...

```
public async Task HashTorrentWithProgressAsync (TorrentManager manager)
{
    int count = 0;
    var lastUpdated = Stopwatch.StartNew ();
    manager.PieceHashed += (o, e) => {
        Interlocked.Increment (ref count);
        if (lastUpdated.Elapsed > TimeSpan.FromSeconds (1)) {
            lastUpdated.Restart ();
            Application.BeginInvoke (() => {
                UpdateUIWithHashingProgress (count / e.TorrentManager.Bitfield.Length);
            });
        }
    };

    await manager.HashCheckAsync (false);
}
```

**Comment by alanmcgovern** [comment]
Note: You could also just attach to the event when you instantiate a torrentmanager and only detach your handler when you are disposing things. It's up to you!

**Comment by catholic** [comment]
Thanks for the help!
I'm using this formula to calculate Hashing progress percent
`(double)(e.PieceIndex + 1) / e.TorrentManager.Bitfield.Length * 100;`
And it enough to demonstrate the user that work is in progress.

However, the current esthetic problem is that if the user downloads only the first file from TorrentManager, the progress will be shown from 0 to let's say 8% and the rest will be quickly skipped and Downloading state will be set with it Download progress percent. So, visual the user sees only 0-8% progress. If TorrentFile is the middle of TorrentManager, 45-53%, if the last one 92-100%

It's not the problem at lot. Just the space for improving the functionality of MonoTorrent.

**Comment by justscribe** [comment]
You can try to check TorrentManager.PartialProgress.

**Comment by catholic** [comment]
> You can try to check TorrentManager.PartialProgress.

This is not related

**Comment by alanmcgovern** [comment]
I haven't forgotten about this - i just need time to make the changes. Supportingt this is definitely worthwhile and shouldn't be too complicated.

**Comment by alanmcgovern** [comment]
Thanks for bearing with me! I've just thrown together a quick patch which should handle the two main cases:

1) All files in the torrent are marked as downloadable
2) Some files are marked as 'DoNotDownload'
3) Files which used to be marked as 'DoNotDownload' are now marked as 'Download'.

I haven't tested this much, but I would appreciate some feedback while I add some unit tests and finalize the approach/patch. https://github.com/alanmcgovern/monotorrent/tree/fix-180

Feel free to submit pull requests targeting the branch if you want to make any changes/modifications.

**Comment by catholic** [comment]
Thanks for your job.
With this commit https://github.com/alanmcgovern/monotorrent/pull/241 everything is working well.

**Comment by alanmcgovern** [comment]
Brilliant. That's a part i may not have tested thoroughly, however i will be sure to add the tests and get this merged/released soon!

**Comment by alanmcgovern** [comment]
Thanks for the PR. I added a test covering the changes, fixed an off-by-one and am ready to merge it now!
