### ISSUE TITLE
Playing media files when downloading

### ISSUE THREAD

**Issue by uponatime2019** [alanmcgovern/monotorrent#205]
I'm using SlidingWindowPicker to download media files to play, it gone well but when engine is running, video cannot play. If i turn off engine, video can play OK. May be torrent engine block the files, how can I fix that?

**Comment by longxoay1** [comment]
Hi!
Could you please help me how to use SlidingWindowPicker?

**Comment by alanmcgovern** [comment]
@uponatime2019 It depends on a few factors. I have a few questions:

1) What is the error your media player is giving you?
2) Does the video file format store metadata at the start or end of the file? Sometimes you can have a better experience by downloading the last piece immediately and then downloading the torrent from the beginning. This could be built into the sliding window picker relatively easily.
3) What media player are you using, and does using an alternative media player give different results?

Note: MonoTorrent always opens files with `FileShare.ReadWrite` permissions. This *should* mean other applications can open the files while monotorrent is downloading them. However please make sure other programs don't *write* to the files as that cannot be reliably detected and you could potentially corrupt things. Running a hashcheck on the file later will allow monotorrent to detect unwanted changes and it will redownload those pieces.

**Comment by uponatime2019** [comment]
1. Error: Video could not be decoded
2. I'm using default SlidingWindowPicker await manager.ChangePickerAsync(new SlidingWindowPicker(new StandardPicker()));
3. I'm using UWP Media Player, and it giving error at (1). I'm open that file using VLC when still downloading and it keep loading, not playing or giving any error. If I'm stop the engine, both UWP Media Player and VLC can play the file without any problem.
May be UWP don't have FileShare permissions and it just locked the downloading file and not allow any problem to acess that file.

**Comment by uponatime2019** [comment]
> Playing video. need download 2 last piece of file. You try

Problem happen only when downloading in progress, stop engine and video can play without problem

**Comment by alanmcgovern** [comment]
It's not easy to tell what the issue is - but if the UWP player can open a http stream (or equivalent) you could try writing a bit of code to use HttpListener and then get the UWP media player to connect to that HTTP 'server' and then you can send it the data as needed? You'll definitely be able to open additional FileStreams to read the data.

**Comment by alanmcgovern** [comment]
Here's some quickly thrown together code showing how you can expose a file over HTTP. https://gist.github.com/alanmcgovern/c1bfb7b126e9037ffce3f612f9eee1c4

I've hardcoded it to only respond to requests for `c:\test.m4v` so if you wanted to test this approach out with your streamer then you'd need to make this a little more dynamic ;)

This code is sufficient for you to use `Media -> Open Network Stream` in VLC and then use the url `http://127.0.0.1:5555/test.m4v`.

**Comment by alanmcgovern** [comment]
On a related note - if this approach works for your needs, and if you improved the implementation to make it production quality, I would be happy to take a pull request which integrated it into the core of MonoTorrent.

I could imagine making streaming media fairly easy to consume by creating a Http wrapper for TorrentManager which takes care of all the piece picking logic based on what the media player actually needs. It could be as simple as:

```
var httpStreamer = new HttpTorrentStreamer (torrentManager);
await httpStream.StartAsync ();
Process.Start ("vlc", httpStreamer.StreamingUrl);
```
There could be one StreamingUrl per file if there are multiple files in the torrent.

**Comment by uponatime2019** [comment]
I'm implemented your code, but same result. It's play OK when file not downloading, but when download in progress, below exception happen

Play media file:
`MediaPlayer.Source = MediaSource.CreateFromUri("http://127.0.0.1:5555/" + filePath.UrlEncode());`

```
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Connection closed - System.IO.IOException: The process cannot access the file '<TEST TORRENT FILE>' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.OpenRead(String path)
   at TorrentPlayer.HandleContextAsync(HttpListenerContext context)
   at TorrentPlayer.HandleContext(HttpListenerContext context)
```

**Comment by alanmcgovern** [comment]
Hrm. If you're getting that kind of error then I think you may have misinterpreted what I was intending.

The *playing* application should not be opening any files. If you can share a copy of the application you're using to play the file (privately or publicly) i can probably tweak it to demo the approach a bit better.

**Comment by uponatime2019** [comment]
But the exception throw when program try to open file stream to read and write to HttpListener response. And in above code, UWP MediaPlayer try to open the localhost URI, but if I don't open the URI using player, just send a request to localhost path, same exception throw. 

`MediaPlayer.Source = MediaSource.CreateFromUri("http://127.0.0.1:5555/" + filePath.UrlEncode());`

replace with

`await httpClient.SendAsync(new HttpRequestMessage { RequestUri = new Uri("http://127.0.0.1:5555/" + filePath.UrlEncode()) })`

So I think problem not cause by player, but when downloading the torrent engine lock files

Sorry I can't share project right now because it's a part of company project

**Comment by alanmcgovern** [comment]
Here's a screencast of MonoTorrent downloading a torrent and streaming it directly to VLC while the download is happening. https://recordit.co/ajohMdrzz8

This is the code I used to make it happen: https://gist.github.com/alanmcgovern/2909ff307e583c1da15a199f9f24f956 . I've also attached the torrent I used in the 'test.zip' file.

[test.zip](https://github.com/alanmcgovern/monotorrent/files/4094574/test.zip)

If this stream-over-http approach is useful then it can be made a fully supported feature. In this setup only the MonoTorrent process actually opens the underlying files. Other processes just communicate over local  (or remote?) HTTP requests to get the data they need.

If you're getting file lock issues then please make sure every time you open the file you specify the same fileshare/fileaccess parameters as I have done ( https://gist.github.com/alanmcgovern/2909ff307e583c1da15a199f9f24f956#file-test-cs-L124 ). Alternatively, the .NET documentation on `FileStream` may offer some insights into combinations which will work.

**Comment by uponatime2019** [comment]
Thanks tt's working when I replace with new FileStream method

**Comment by alanmcgovern** [comment]
Brilliant! So I do have a few question for you which might help me improve the library!

First, is this your setup:

You have a single UWP application. It uses MonoTorrent to download torrents which contain audio/video media. The media is played while the torrent is actively downloading. You directly open the file which is being downloaded using a `FileStream` and give that `Stream` to the UWP MediaPlayer/MediaElement.  You use `SlidingWindowPicker` and update the `HighPriority` set as the file plays in the MediaPlayer so that it always prioritises the parts the MediaPlayer will need next.


How do you handle seeking? Do you need/want to support seeking while the torrent is downloading? What happens if the torrent downloads slower than it plays, so that you don't have enough data to keep the media player filled? How do you auto-pause it, or what happens?

Is there anything you think is awkward, or could be easier, or should be handled by the library directly?

**Comment by uponatime2019** [comment]
Currently my app only official support play files when download completed. I've just find a way to support play when downloading after your answer. Now the app don't support seeking when download in progress because honestly I don't really understand the library code, I just hide the seeking bar and enable fast forward +30 seconds. 
I think it would be very complex for me right now to build a complete instant torrent player (like github repo **webtorrent**, that support instant torrent player)

**Comment by alanmcgovern** [comment]
It's easy for me to add that if it would be of use. I prototyped it in a few hours and could have something relatively complete within a week or two.

**Comment by uponatime2019** [comment]
Yeah I will wait for new release, a sample code will help us a lot to integrate to our app. Thanks for making this awesome library

**Comment by Sam-fr** [comment]
Hello Alan,

I wanted to inquire whether the feature for streaming torrents directly via HTTP has been integrated into the MonoTorrent library following your prototype discussed in the issue thread. I apologize for any inconvenience, but I couldn't find any additional information elsewhere regarding this. If this information is available somewhere and I missed it, I apologize for the oversight.

Thank you for your help and for your continued work on improving the library.

**Comment by uponatime2019** [comment]
> Hello Alan,
> 
> 
> 
> I wanted to inquire whether the feature for streaming torrents directly via HTTP has been integrated into the MonoTorrent library following your prototype discussed in the issue thread. I apologize for any inconvenience, but I couldn't find any additional information elsewhere regarding this. If this information is available somewhere and I missed it, I apologize for the oversight.
> 
> 
> 
> Thank you for your help and for your continued work on improving the library.

Look at samples code, already have http streaming
