### ISSUE TITLE
How to enable metadata transfer for magnet links in tracker

### ISSUE THREAD

**Issue by eivarin** [alanmcgovern/monotorrent#206]
Hey,

I'm trying to play around a little bit with metatorrent and I wanted to use magnet links with trackers.
For testing purposes, I created a torrent from a movie in my pc, used my external IP with port forwarding, and seeded it with my pc. I also have the test torrent file in the torrents folder for the torrent watcher. Then I copy the magnet link to my phone so that I can try and download with it on mobile data to test the port forwarding and it looks like it connects but stays stuck downloading the metadata and doesn't do anything else. On my PC's torrent client, I disabled everything like DHT and local peer exchange to force using the tracker and it says that there is one seed in the swarm but it can't seem to connect to it. For base reference, when I first started I used the tracker app project on the source folder. On some tests I also got the message on the pc client "Tracker has no peers field" and that is on the UDP link... The HTTP just says offline (timed out)
Can anyone help

**Comment by alanmcgovern** [comment]
Just to check - are you saying that your PC and Phone never make a connection at all, or are you saying that they successfully connect but they never transfer the metadata successfully?

If you're using MonoTorrent on both ends you could try add logging to MetadataMode ( https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs#L91 ) so you can see whether or not the Phone client is actively requesting pieces of the metadata.

Similarly, you could add logging to the PC client to see if it's receiving and processing the requests ( https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs#L212-L221 ).

To reduce the number of variables you could install one, or more, bittorrent clients on your PC and see if they can successfully connect to each other using the magnet link. It's possible the windows firewall is blocking the incoming connections even though your router is forwarding correctly.

**Comment by alanmcgovern** [comment]
@eivarin Just wondering if you have any further information on this?

**Comment by eivarin** [comment]
@alanmcgovern Hadn't have any time to check this out yet... thank you for the preocupation though.

**Comment by alanmcgovern** [comment]
There's some slightly outdated documentation here: https://smuxi.im/wiki/monotorrent . I need to modernise and port it to the github wiki. Hopefully that'll help you get started

**Comment by alanmcgovern** [comment]
@eivarin I just wanted to check in with you to see if you were still having issues that I could help with. If not, i'll go ahead and close this.

**Comment by eivarin** [comment]
At the moment I don't have any other issues... I'll just close for now and if I get another problem I'll just open another thread.
