### ISSUE TITLE
Tracker Connection error!

### ISSUE THREAD

**Issue by longxoay1** [alanmcgovern/monotorrent#216]
Hi alanmcgovern!
At the newest version, i got the trouble, after download already about 9 torrent files then app even our internet can not connect to tracker.
This trouble do not happen with old version from 1 year ago

**Comment by alanmcgovern** [comment]
Are you using MonoTorrent to host a Tracker, or are you using other software? It sounds like the issue is with the Tracker itself, not with the client application, so more information on that would help  :)

**Comment by longxoay1** [comment]
I used "udp://tracker.opentrackr.org:1337/announce". I think internet connection error, then i change tracker "https://github.com/webtorrent/bittorrent-tracker" Same problem.
Close client about 5 - 10 minute  open client then connect tracker ok,  Download the file 9 and then tracker error.

**Comment by alanmcgovern** [comment]
I'm still a little confused about what exactly has gone wrong.

In your first comment are you saying that after a certain amount of time nothing on your computer can connect to the UDP tracker, or are you saying that only the active MonoTorrent process cannot connect, but everything else on your computer can successfully connect?

I've just reviewed the code and it looks like everything is set up correctly. The UdpClient is correctly disposed, the connection id token is refreshed as expected too. Do you have any further details on what is going wrong? Is there an exception, is it an ErrorResponse coming from the Tracker?

Without further details it'll be hard to tell if I've addressed your issue even if I do make some changes, so the more details you can provide about the failure the easier it'll be for me!

**Comment by longxoay1** [comment]
I send link video. test tracker not connect.

[https://www.youtube.com/watch?v=AeMRuj7-Zjc&feature=youtu.be](url)

**Comment by alanmcgovern** [comment]
I don't know what code you're using to generate that webpage with stats. It's not part of MonoTorrent and there's no indication in the screencast that it's MonoTorrent itself that has failed.

Either way, could you share a full project which reproduces the problem? That would likely be the best way to resolve this as we could find out what the underlying exception is.

**Comment by alanmcgovern** [comment]
Hi,

As it stands it looks like the issue you are seeing is caused by code unrelated to MonoTorrent itself. The most likely cause is the code associated with the website displaying the stats.

If there is an issue with MonoTorrent, please provide a repro and/or logs containing the stacktrace from the error so I can dig into it some more!

Thanks for reporting, and please do let me know if I can help further.
