### ISSUE TITLE
Generate .torrent file from Hash

### ISSUE THREAD

**Issue by uponatime2019** [alanmcgovern/monotorrent#242]
Is any fast method to create a torrent file from hashid? 
I found a way to do with **monotorrent** is to start an torrent engine and add a torrent manager from hashid and wait for it to download, then stop manager and get the .torrent file saved in torrent folder, but it takes a very long time (about > 30s).

**Comment by alanmcgovern** [comment]
Do you know if these torrents are using DHT to find peers to retrieve the `.torrent` file, or if they can use a normal HTTP or UDP tracker to get a list of peers? Dht will always be a bit slower than trackers.

Apart from that, do you know roughly how long it takes for peer connections to be established?

MetaData downloading is probably slower than it needs to be. I've been contemplating rewriting it to use more or less the same logic as 'EndGameMode'. At the moment the logic to download the metadata is stored in MetaDataMode and is completely custom. I think there's a very good chance it could be rewritten to rely on an EndGamePicker, which could make things a little faster. At the least it might be a little less maintenance.

**Comment by uponatime2019** [comment]
It's a great way, I think it will be faster than my method because it don't need to create folder, init Torrent Engine and many of unwanted settings

**Comment by alanmcgovern** [comment]
You would still have to create an Engine as downloading the metadata requires a TorrentManager under the hood. 

Perhaps a better API would be something like:

`BEncodedDictionary torrentMetadata = await ClientEngine.GetMetadataAsync (MagnetLink magnetLink);`

In some respects it would be much easier internally if metadata downloading were completely separate to actual torrent downloading. Unfortunately the boat has kind of sailed on that decision :p a simpler API can still be exposed though as it would unlock some nice use cases (like allowing someone to view the files before actually registering the torrent for downloading).

**Comment by vlasenkoalexey** [comment]
If you need a torrent fast, you could try using https://itorrents.org service. Of course there is no guarantee, that it'll have torrent information, but it works pretty well otherwise.

Usage is straightforward:
```
                string itorrentsUri = "https://itorrents.org/torrent/" + magnetLink.InfoHash.ToHex() + ".torrent";
                Uri url = new Uri(itorrentsUri);
                await Launcher.LaunchUriAsync(url);
```

**Comment by alanmcgovern** [comment]
@uponatime2019 Implemented! The best performance will be with MagnetLinks which have trackers. They will return a list of peers very quickly. If you need to rely on Dht it will be a little slower as Dht initialization can take a little bit of time.

Leave your comments on the PR and thanks for the feature request!

**Comment by uponatime2019** [comment]
I will try it! Thanks for listening
