### ISSUE TITLE
send messages to peers

### ISSUE THREAD

**Issue by furesoft** [alanmcgovern/monotorrent#243]
can i send messages to other peers to use monotorrent as peer to peer layer for my applications?

**Comment by alanmcgovern** [comment]
Are you asking if it's possible to send arbitrary/custom messages to peers? If so, the answer is "yes and the API for that could probably use improvement". That is not likely to be something you'd need to do though. If you do want to do this I'd love to know more about your use case. 

There have been successful projects in the past which used MonoTorrent as the file/data transfer engine for P2P like clients. I can't remember the name of the main one now, but it worked by establishing encrypted connections between its clients using its own communication layer and then it wrapped the active socket in an IConnection and gave that to MonoTorrent. This socket was not used for regular communication between the P2P clients.

**Comment by furesoft** [comment]
i want it for many use cases. examples: 
- distributed computing 
- distributed database

**Comment by alanmcgovern** [comment]
From the face of it it sounds like MonoTorrent may be the wrong foundation to build your application on. I suspect a lot of work would have to go into MonoTorrent to allow you to reliably use it for something which *is not* downloading torrents. XMPP or MQTT could be a better technology to base this kind of project on.

If you need something distributed then you could look into creating a https://en.wikipedia.org/wiki/Kademlia like distributed network. If that's the case then you could probably re-use MonoTorrent's DHT implementation with some tweaks to make it less BitTorrent specific. However even a distributed system needs a central server to allow clients to bootstrap, so you would have to run a centralised server of some kind even if you went for a 'full distributed' model.

As for sending messages, it looks like the API in MonoTorrent is not public anymore. It used to be but was made internal a while ago. It would be relatively easy to make it public again. First the API to register new messages would be made public ( https://github.com/alanmcgovern/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client.Messages/PeerMessage.cs#L72-L78 ) and then you would have to expose a new public method on PeerId ( https://github.com/alanmcgovern/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client.Connections/PeerId.cs#L206-L209 ) like:

```
public void EnqueueAsync (PeerMessage message)
{
    await ClientEngine.MainLoop;
    Enqueue (message);
}
```

There is already an event which is raised when messages are received, but that could be always be changed/improved.

**Comment by alanmcgovern** [comment]
I'll close this for now. If you have any questions/thoughts feel free to reopen the issue and drop a comment!

**Comment by vlasenkoalexey** [comment]
You can take a look at https://github.com/BiglySoftware/BiglyBT/wiki/Decentralized-Chat
As far as I understand it is a proprietary protocol, and not sure if anyone is using it.
