### ISSUE TITLE
Throw FormatException in MagnetLink.FromUri only if not a Tr record

### ISSUE THREAD

**Issue by amellini** [alanmcgovern/monotorrent#246]
There's some cases when the magnet uri contain a malformed Tr record, now the FromUri throw a FormatException and cannot start the torrent.

I think tr record should be ignored and the process of validation should continue.
That's right?

(I'll make a PR with a fix)

**Comment by alanmcgovern** [comment]
Your proposed fix has been merged to master! Thanks!
