### ISSUE TITLE
sorry this isn't an issue, can I use this to stream magnet url in android build from unity3d c#

### ISSUE THREAD

**Issue by ajeshyohan** [alanmcgovern/monotorrent#248]

**Comment by alanmcgovern** [comment]
If you want to stream media (typically audio/video) then there is an open PR adding this feature in a simpler way:

https://github.com/alanmcgovern/monotorrent/pull/224

This has shipped in the latest preview release in NuGet. Just bear in mind the API is not stable and it may change before being included in it's first stable release. 

It can be used on Android as this is a normal NETStandard 2.0 compatible library :)

**Comment by alanmcgovern** [comment]
I'll assume this answered your question. If you need more info please feel free to reopen and add a new comment!
