### ISSUE TITLE
Check TorrentFile is complete download issue

### ISSUE THREAD

**Issue by uponatime2019** [alanmcgovern/monotorrent#249]
I wrote this method extension to check if TorrentFile is download complete, but it return **false** result (invalid) when torrent just complete in current session

        public static bool IsFileDownloadCompleted(this TorrentFile file)
        {
            return file.BytesDownloaded >= file.Length;
        }

But when I restart the app and run this again, it return **true** result. May be BytesDownloaded not update yet?

**Comment by alanmcgovern** [comment]
BytesDownloaded is implemented as:
```        public long BytesDownloaded => (long) (BitField.PercentComplete * Length / 100.0);
```
If this property is returning an incorrect value then it means the BitField is being updated incorrectly. It sounds like this only happens while the torrent is actively downloading so I'll look into this to start with. If you can come up with a concrete testcase that would help.

I'll update this issue if I find anything which explains this further.

**Comment by alanmcgovern** [comment]
By the sounds of it the issue is that the torrent reports 100% complete, but individual files aren't marked as 100% complete. I'm not sure how that could happen as the file and torrent are updated in the same method, and there are tests covering this to make sure they are updated correctly.

If you can come up with a way to reproduce the issue that would be very helpful!

**Comment by uponatime2019** [comment]
I will try to reproduce the issue later, and for more info, the method I use to determine torrent is downloaded is
                    if (TorrentManager.Progress >= 100)
                    {
                        // torrent loaded
                    }

**Comment by uponatime2019** [comment]
I can't reproduce issue, it just happen one time. I will open this again when it bother me again. Thanks
