### ISSUE TITLE
Two trackers

### ISSUE THREAD

**Issue by carlosib** [alanmcgovern/monotorrent#250]
Hello!

I have some .torrent file all using two tracker. Some times I have the file complete only 1 tracker and incomplete in the other one. When I have it and the active tracker is incomplete the current .torrent file never is downloaded and it doesn't change to the tracker complete.

I did some test uisng uTorrent app and always do fast the download.

**Comment by alanmcgovern** [comment]
I'm not sure exactly what the problem is from your description.

Are you saying that there are two trackers - one tracker has a fast peer and the other tracker had a slow peer. uTorrent queries both trackers, but MonoTorrent only queries one tracker. As a result uTorrent always gets the fast and slow peer but MonoTorrent might only get the slow peer?

**Comment by carlosib** [comment]
Hello Alan McGovern!

I'll try to explain using others words.

My  torrent file has 2 tracers. Sometime when monotorrent load this .torrent file I have a tracker online and the other offline, but, monotorrent set the active tracker the offline and the active tracker is offline forever.

Sometime, also, I have 2 tracker and both online. But, for exemple, the tracker active is the tracker number 2 and this tracker the file is 'incomplete'. The tracker number 1 is online and it has the file 'complete'. But, I always have as active tracker the number 2.

Sorry my bad English!

**Comment by alanmcgovern** [comment]
Hrmm, can you share the torrent so I can understand how the trackers are included?

If one tracker is offline then the second tracker should always be queried. 

If they are both online then it may be 'correct' to only query one tracker, depending on how they are included in the torrent.

I think I have a clear understanding of the problem you have (your English is great!).
 The only complication left is I don't have the .torrent file so I can't verify how the trackers are grouped into tiers :)

**Comment by carlosib** [comment]
Hello!

Please, see the file like_momentotrailer_sobcustodia_231018.mp4.zip 

[like_momentotrailer_sobcustodia_231018.mp4.zip](https://github.com/alanmcgovern/monotorrent/files/4236810/like_momentotrailer_sobcustodia_231018.mp4.zip)

Thank you!

**Comment by vlasenkoalexey** [comment]
I think I have an idea what this is all about, as I was thinking about changing the way TrackerManager currently works.

If torrent has 2 trackers, one of them has 1 peer, another one has plenty.
When download is started, trackers are randomized so it is not clear which one is going to be used first.

Logic in announce tries to send message to all trackers in the list sequentially, and it stops when it reaches first tracker that responds with peers.
If that happens to be a tracker with multiple peers, everything is great.
If that is a tracker with 1 peer, there is a high chance that user won't be able to download anything.

I think that we should keep scanning all available trackers, and it would also be nice to do that in parallel to make sure that peers are discovered faster which is important for torrents that have too many trackers.

I might have missed some details here, please correct me if I'm wrong.

**Comment by alanmcgovern** [comment]
>  When download is started, trackers are randomized so it is not clear which one is going to be used first.

Yup, the spec calls for trackers in the same tier to be randomized. Trackers in the same tier are supposed to be load balancers which represent the same set of active clients. As such accessing `tracker1` is the same as `tracker2` *as long as they are in the same tier*.

> I think that we should keep scanning all available trackers, and it would also be nice to do that in parallel to make sure that peers are discovered faster which is important for torrents that have too many trackers.

I don't have time to check the TrackerManager logic in-depth, but I think you hit the nail on the head. My recollection is that the current implementation does not announce to every tier immediately. It starts at tier1 and checks every tracker until at least 1 responds.

If that is what occurs, it's wrong. What we *should* do, and i should double check the spec, is that TrackerManager should announce to every Tier, and then within each tier we try each tracker until *one* responds.

i.e. if we have three tiers, as follows
```
[offline_tracker_1a, online_tracker_1b, offline_tracker_1b]
[online_tracker_2a, offline_tracker_2b]
[offline_tracker_3, offline_tracker_3b, online_tracker_3c]
```

We should immediately announce to tiers[0], tiers[1] and tiers[2], and will check each tracker in order, and will eventually get a response from: `online_tracker_1b`, `online_tracker_2a` and `online_tracker_3c`, and will not announce to`offline_tracker_1b` or `offline_tracker_2b` because a previous tracker responded.

**Comment by alanmcgovern** [comment]
So i did have time to check :p

https://github.com/alanmcgovern/monotorrent/blob/d14b4ba1dd904baafa93da16a3d835f10c44faf7/src/MonoTorrent/MonoTorrent.Client/Managers/TrackerManager.cs#L136

If someone is bored and wants to submit a patch, psuedo code for what we need is:
```
        async Task Announce (TorrentEvent clientEvent)
        {
            // If the user initiates an Announce we need to go to the correct thread to process it.
            await ClientEngine.MainLoop;

            LastAnnounce.Restart ();
            LastUpdated = DateTime.UtcNow;

            var announces = new List ();
            foreach (var tier in Tiers)
                announces.Add (Announce (clientEvent, tier);
           await Task.WhenAll (announces);
        }

        async Task Announce (TorrentEvent clientEvent, TrackerTier tier)
        {
            AnnounceParameters p = RequestFactory.CreateAnnounce (clientEvent);

            foreach (var tracker in tier.Trackers)) {
                try {
                    // If we have not announced to this Tracker tier yet then we should replace the ClientEvent.
                    // But if we end up announcing to a different Tracker tier we may want to send the
                    // original/unmodified args.
                    AnnounceParameters actualArgs = p;
                    if (!trackerTier.SentStartedEvent)
                        actualArgs = actualArgs.WithClientEvent (TorrentEvent.Started);

                    List<Peer> peers = await tracker.AnnounceAsync (actualArgs);
                   // LastAnnounceSucceeded = true; // FIXME: needs to be per-tier now
                    AnnounceComplete?.InvokeAsync (this, new AnnounceResponseEventArgs (tracker, true, peers.AsReadOnly ()));
                    return;
                } catch {
                    //LastAnnounceSucceeded = false; // FIXME: Needs to be stored on the tier?
                    AnnounceComplete?.InvokeAsync (this, new AnnounceResponseEventArgs (null, false));
                }
            }
        }
```

**Comment by carlosib** [comment]
Hello again!

I update your psuedo code:

`        public async Task Announce (TorrentEvent clientEvent)
        {
            //await Announce (clientEvent, null);
            // If the user initiates an Announce we need to go to the correct thread to process it.
            await ClientEngine.MainLoop;

            LastAnnounce.Restart ();
            LastUpdated = DateTime.UtcNow;

            var announces = new List<Task> ();
            foreach (var tier in Tiers)
                announces.Add(Announce(clientEvent, tier));

            await Task.WhenAll(announces);
        }

        async Task Announce (TorrentEvent clientEvent, TrackerTier tier)
        {
            AnnounceParameters p = RequestFactory.CreateAnnounce (clientEvent);

            foreach (var tracker in tier.Trackers) {
                try {
                    // If we have not announced to this Tracker tier yet then we should replace the ClientEvent.
                    // But if we end up announcing to a different Tracker tier we may want to send the
                    // original/unmodified args.
                    AnnounceParameters actualArgs = p;
                    if (!tier.SentStartedEvent)
                        actualArgs = actualArgs.WithClientEvent (TorrentEvent.Started);

                    List<Peer> peers = await tracker.AnnounceAsync (actualArgs);
                    // LastAnnounceSucceeded = true; // FIXME: needs to be per-tier now
                    AnnounceComplete?.InvokeAsync (this, new AnnounceResponseEventArgs (tracker, true, peers.AsReadOnly ()));
                    return;
                } catch {
                    //LastAnnounceSucceeded = false; // FIXME: Needs to be stored on the tier?
                    AnnounceComplete?.InvokeAsync (this, new AnnounceResponseEventArgs (null, false));
                }
            }
        }
`

Is it correct?

**Comment by alanmcgovern** [comment]
Perhaps! If you want to push a PR branch with the changes it'd make it easier to review and test, otherwise I might have time this evening to finalise the changeset! It shouldn't take a huge amount of time :)

**Comment by alanmcgovern** [comment]
I'm on it now!
