### ISSUE TITLE
Add more states to the tracker status enum

### ISSUE THREAD

**Issue by alanmcgovern** [alanmcgovern/monotorrent#255]
May I make a suggestion. Currently you have following TrackerStates:
public enum TrackerState
{
Ok,
Offline,
InvalidResponse
}

Could you also add Unknown and connecting Connecting.
Looks like here is the right place to set tracker state now.
All trackers should start with Unknown state, once you start connecting, you change it to Connencting.
If connection succeed, you change it to Ok, if fails - to Offline or InvalidResponse.

**Comment by vlasenkoalexey** [comment]
Thanks!!!
