### ISSUE TITLE
Enable StreamProvider by default for streaming media

### ISSUE THREAD

**Issue by alanmcgovern** [alanmcgovern/monotorrent#257]
Disorganised brain dump:

I expect to merge this in the not too distant future! I'm still debating about the API I want to use to expose this. A lot of these ideas could wait til V2 :)

Currently you have to create a TorrentManager, then wrap it in a StreamProvider, then use the StreamProvider to get a Stream for a file in that TorrentManager. This is a bit confusing as it's unclear what the lifespan/ownership of the TorrentManager is. How does starting/stopping affect everything?

Other thoughts include:

    Should the StreamProvider 'own' the TorrentManager and start/stop it as appropriate? If so what is the right logic?
    What if the TorrentManager was created with a MagnetLink and doesn't have metadata?
    What happens if the user tries to create multiple streams for one TorrentFile.
    What happens if the user wants to stream multiple files simultaenously. Currently only 1 file will stream correctly.
    Suppose there was a completely different implementation of ClientEngine/TorrentManager which dealt exclusively with streaming, what would that look like? Would it be better?

If anyone has any thoughts on this do let me know! Currently i think the most likely outcome is that I'll clean up some of the edgecases with the current approach and then release it more or less as-is.

**Comment by OneFingerCodingWarrior** [comment]
Create multiple streams for one TorrentFile or Stream multiple files simultaneously should not be allowed. The reason is file is still being downloading, and the peers which uploading the data are out of our control. If we insist to implementing these capabilities then we will have to implement a full functional media serving server.

**Comment by OneFingerCodingWarrior** [comment]
TorrentManager should independent of StreamProvider,  TorrentManager  should do the general purpose as to downloading the media file. Because most of the time, the experience of  StreamProvider will not be as good as local file playback. if the user do not like the media file, he will cancel the downloading immediately

**Comment by alanmcgovern** [comment]
@OneFingerCodingWarrior I agree with both of your suggestions!

I've added APIs to StreamProvider to attempt to hide the fact a TorrentManager is needed/used. The underlying TorrentManager is still exposed so you can state rate limits, or access information related to the download. However you do not, and should not, call 'StartAsync' or 'StopAsync' on the TorrentManager, nor will you have to Register/Unregister it with the ClientEngine.

The API is now something like:
```
var provider = new StreamProvider (clientEngine, saveDirectory, magnetLink);
// or
provider = new StreamProvider (clientEngine, saveDirectory, torrent);

await provider.StartAsync ();

// If you downloaded using a MagnetLink you'll have to wait for the metadata to download.
var stream = await provider.GetStreamAsync (provider.TorrentManager.Torrent.Files[2]);
```

**Comment by OneFingerCodingWarrior** [comment]
I have a question, if I love the movie, but the streaming experience is so bad, so I want to watch it after the whole file is downloaded, Do I need to start a total new Downloading Task ?

**Comment by OneFingerCodingWarrior** [comment]
in my wcf implemention, the downloaded file can also be served to cell phone or ipad with simple http streaming

**Comment by OneFingerCodingWarrior** [comment]
> in my wcf implemention, the downloaded file can also be served to cell phone or ipad with simple http streaming

In fact, only downloaded file can be served in my WCF implemention

**Comment by alanmcgovern** [comment]
I've merged the changeset so it's enabled, and documented, now. 

I'll add one more method to allow users to wait for the metadata to be downloaded so they know when the list of TorrentFiles are available.

This will be synchronous when you load from a .torrent file, but will take a little bit of time if you use a magnet link. 

People can use the new ClientEngine.DownloadMetadataAsync method to pre-download the .torrent metadata too

**Comment by alanmcgovern** [comment]
https://github.com/alanmcgovern/monotorrent/pull/273/files

Added!

**Comment by alanmcgovern** [comment]
The current API looks like this:

```
var provider = new StreamProvider (engine, downloadsPath, Torrent.Load ("Torrents\\a.torrent"));
await provider.StartAsync ();
var stream = await provider.CreateHttpStreamAsync (provider.Manager.Torrent.Files[0]);
Process.Start (@"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe", stream.Uri.ToString ());
```

I'm going to make one more small change to the CreateStream methods. I intend on making them buffer a little by default, and then provide an optional boolean parameter to disable buffering. The idea is that you can do something like:
```
var stream = await provider.CreateHttpStreamAsync (provider.Manager.Torrent.Files[0]);
```
and then the first bytes and last bytes will *already* have been downloaded when the stream is returned. This means a media player should be able to start playing immediately.

If you do not want to wait for MonoTorrent to buffer the first/last pieces then you will call:
```
var stream = await provider.CreateHttpStreamAsync (provider.Manager.Torrent.Files[0], prebuffer: false);
```

**Comment by alanmcgovern** [comment]
Ok, V1 of supporting streamable torrents has been released in NuGet!

https://github.com/alanmcgovern/monotorrent/releases/tag/release-v1.0.18
