### ISSUE TITLE
MonoTorrent V2.0 (API break edition)

### ISSUE THREAD

**Issue by alanmcgovern** [alanmcgovern/monotorrent#260]
- [x] Update ITracker so FailureMessage/WarningMessage/State are distinct variables for Announce and Scrape requests.
- [x] Remove the 'LastAnnounceSucceeded', and related, API from TrackerManager. These are per-tier and so we don't want to expose them on TrackerManager itself.
- [x] Remove `IConnection` and rename `IConnection2` to `IConnection`.
- [x] Remove `ITrackerManager` and rename `ITrackerManager2` to `ITrackerManager`.
- [x] Remove `CancellationToken` from `AnnounceParameters` and `ScrapeParameters`. Add it to the methods like a normal API would do!
- [x] Mark `AnnounceParameters` and `ScrapeParameters` as sealed.
- [x] Make DiskManager and IPieceWriter use async methods all the way through. In addition make it so that reads/writes are now locked on a per-file basis, not one read overall. Note: We also need to ensure that the code to ensure all pending writes complete before reading the data for a hash check is not broken by this.
- [x] Fix 'RawTrackerTier' to not be terrible. This is not a good way to access the urls stored in the torrent: `var magetLink = new MagnetLink (torrent.InfoHash, torrent.Name, torrent.AnnounceUrls.SelectMany (t => t.ToArray ()).ToList ());`
- [x] Queue up tracker announces so if you start 100 torrents at a time we only issue a few announces concurrently. Do the same for StopAllAsync.
- [x] Investigate a better return type for StopAllAsync so progress can be tracked for pending announces etc.
- [x] Queue up announces when starting 100s of torrents. Similarly for HashCheckAsync etc. Maybe put torrents in a 'Pending' state which becomes 'Starting' eventually? Will need to be able to tell when the startup tasks are done (first announce etc). Those are currently run when the mode is 'Downloading' so it's not easy to check this.
- [x] Investigate a better StopAllAsync which reports progress is the announces are queued.
- [x] ~Change how the PiecePicker is registered so that it does not get clobbered by StartAsync, and also so you can set one when in MetadataMode and not crash things!~ This was not API breaking!

**Comment by dufoli** [comment]
hello alan, long time and I was curious to discover that the library is sill actively developped WOW!
I am currently working on quarkus (java) cxf (soap support) extension and I use vertx (express js patter with event loop). 
Maybe it can be better for performance to have a such pattern with verticles and signe event loop. 
Anyway, it was just an idea. I just see that this is just still active and very happy. cheers olivier (if you remember me we code together on the firs DHT support 10 years ago )
