### ISSUE TITLE
Exceptions with sample

### ISSUE THREAD

**Issue by mfkl** [alanmcgovern/monotorrent#261]
Hi,

Complete n00b with monotorrent here, so bear with me please :-)

I tried running your sample app, added a random .torrent file and pressed play. This works, the file is downloading and I have no crash. 

However the VS Output window is filled with exception logs such as https://gist.github.com/mfkl/f0ae255c64cd10ddd7052f5c6b78755b

Are you aware of this? Is it normal?

Keep up the good work 👍

**Comment by alanmcgovern** [comment]
Yup, it's normal. 

SocketExcpetions occur when a connection to another client is closed, or trackers give up/port combinations for offline clients and the socket cannot connect. 

ObjectDisposed exceptions can be triggered when a associated socket is closed. 

If there's something suspicious or bad about the actual behaviour of the client do let me know.
