### ISSUE TITLE
Usage with Magnet Links

### ISSUE THREAD

**Issue by jamarchist** [alanmcgovern/monotorrent#262]
This is not really an issue but a question - how do you create a client that can download with magnet links?

Currently I have a client based on the sample that works just fine when using a .torrent file, but when swapping out the `TorrentManager` constructor for the one that takes a `MagnetLink`, my download doesn't work.

To wit, I have something like this working:
```
// Engine/Dht setup omitted

var t = Torrent.Load(torrentData);
var manager = new TorrentManager(t, /* destination directory for downloads */);
await engine.Register(manager);
await manager.StartAsync();
```

Whereas this doesn't work:
```
// Engine/Dht setup omitted

var magnetLink = MagnetLink.Parse(/* a constant string with the link uri */);
var manager = new TorrentManager(magnetLink, /* destination directory for downloads */, new TorrentSettings(), /* destination for torrent files? */);
await engine.Register(manager);
await manager.StartAsync();
```

I considered that maybe my magnet uri is improperly encoded. When I run that string through System.Net.WebUtility.UrlDecode there is no change.

**Comment by alanmcgovern** [comment]
Does the magnet link doesn't have trackers?

If not, you will need to register a DHT engine to discover peers. The sample client does this. 

Alternatively local peer discovery should work if there are other peers on your LAN who are sharing the torrent. 

If you have any issues with Dht let me know! I expect that to solve your problem so I'll close this for now. I'll reopen again if needed :)
