### ISSUE TITLE
Getting data from the client engine

### ISSUE THREAD

**Issue by eivarin** [alanmcgovern/monotorrent#279]
So I was wondering what kind of stats I can get from the main engine. I'm asking because I'm designing a dashboard for my app and it would be cool to have some overall stats to put in the main dashboard.
If you could explain how to get the live data to a variable live, from the main ClientEngine, as i will also be doing the code later.
I would store non live data on a JSON file and do the serialize and deserialize every time I access it. For live data I would use a public parameter using a normal { get; set; } and then accessing it on loading the page.

**Comment by alanmcgovern** [comment]
You can get download/upload speeds, disk write rates, which pieces are downloaded, which are being downloaded, number of peers connected, and lots more.

**Comment by eivarin** [comment]
Also is there a way to store in a variable which peers have the file. I'm thinking about getting the peers from dht as the system i'm, trying to build would use only dht.

**Comment by alanmcgovern** [comment]
I'm not sure what you mean. If you're asking "Can I cache the DHT table to make it bootstrap quicker" the answer is "yes!". 

You can also add arbitrary ip/port combinations to a TorrentManager, however I would recommend against that in general. DHT and/or the trackers should be enough to get a fresh peer list quickly!

**Comment by alanmcgovern** [comment]
Closing this as there hasn't been a response in a while.
