### ISSUE TITLE
Is There any sample written in Console app for .net core 3.1 

### ISSUE THREAD

**Issue by tlejmi** [alanmcgovern/monotorrent#282]

**Comment by alanmcgovern** [comment]
There's a .NET core sample in the main sln file. MonoTorrent is a .NET Standard 2.0 library so it is compatible with .NET Core 2.0 and greater, and the regular .NET Framework 4.6.1 or greater.

**Comment by tlejmi** [comment]
@alanmcgovern : Thankx ... it works ... But i have a problem file larger than 100MB , reach approximately 99MB and stopped ....

**Comment by alanmcgovern** [comment]
Can you share a copy of the files and torrents, either publicly or privately, so i can look into the issue?

**Comment by tlejmi** [comment]
can you send me your email ??
