### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by carlosib** [alanmcgovern/monotorrent#283]
Hello!

After some hours I have this exception:

![image](https://user-images.githubusercontent.com/14793055/77758918-96350200-7012-11ea-8565-736109fed7ba.png)

**Comment by alanmcgovern** [comment]
This is an odd one. I'll need to investigate more. It's unusual for this to be happening with recent builds.

One explanation is that two pieces of code are calling SendAsync or ReceiveAsync at the same time, but that's very unlikely.

The other explanation is that there's a bug in https://github.com/alanmcgovern/ReusableTasks . That is probably more likely, but significantly harder to locate. The stress tests are passing and it did have a fairly thorough review a few months ago.

**Comment by carlosib** [comment]
Hello Alan!

Now I had this exception too:

![image](https://user-images.githubusercontent.com/14793055/77807392-74656a80-7066-11ea-8733-0f3be8704769.png)

**Comment by carlosib** [comment]
More 1 print:

![image](https://user-images.githubusercontent.com/14793055/77808801-a2997900-706b-11ea-998b-976d10507e11.png)

**Comment by OneFingerCodingWarrior** [comment]
hello carlosib, did you made modifications to the MonoTorrent lib?

**Comment by OneFingerCodingWarrior** [comment]
> This is an odd one. I'll need to investigate more. It's unusual for this to be happening with recent builds.
> One explanation is that two pieces of code are calling SendAsync or ReceiveAsync at the same time, but that's very unlikely.
> The other explanation is that there's a bug in https://github.com/alanmcgovern/ReusableTasks . That is probably more likely, but significantly harder to locate. The stress tests are passing and it did have a fairly thorough review a few months ago.

Hello Alan, after you release the ReusableTasks 1.0.6, I didn't test for hours and hours. But before that, I noticed, if you change NetworkIO.cs ReceiveQueuedAsync and SendQueuedAsync from async void to async Task, the exeption is more likely to be throwed-this info need to be cofirmed

**Comment by carlosib** [comment]
Hello Alan!
I have ali you code here. Yes, i can.

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by carlosib** [comment]
But, I use your native code.

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by alanmcgovern** [comment]
> Hello Alan, after you release the ReusableTasks 1.0.6, I didn't test for hours and hours. But before that, I noticed, if you change NetworkIO.cs ReceiveQueuedAsync and SendQueuedAsync from async void to async Task, the exeption is more likely to be throwed-this info need to be cofirmed

If you, or anyone, can trigger the issue somewhat reliably I should be able to resolve it. Ill try this approach and see if it helps me track down the issue! Thanks!

**Comment by alanmcgovern** [comment]
> More 1 print:
> 
> ![image](https://user-images.githubusercontent.com/14793055/77808801-a2997900-706b-11ea-998b-976d10507e11.png)

This one looks like a relatively simple bug, luckily. When an exception occurs this method calls itself. It looks like the socket closed and we recursed until there was a stackoverflow. It should be easy to fix by changing how recursion occurs!

**Comment by alanmcgovern** [comment]
That said - I wish I knew how/why that error was occurring...

**Comment by carlosib** [comment]
Hello @alanmcgovern !

How I can help you understand this?

**Comment by alanmcgovern** [comment]
When the socket goes into an infinite loop, do you know what port/ip it is bound to? Is there a way to reproduce this?

**Comment by carlosib** [comment]
Hi!
I have this error after some hours. All files are seeding mode. How can I get this information when loop issue is started?

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by alanmcgovern** [comment]
If you can modify the code you could add logging statements when ConnectAsync returns false, or add a Debugger.Break call!

**Comment by carlosib** [comment]
Sorry, Debugger.Break is a breakpoint?

![image](https://user-images.githubusercontent.com/14793055/77829744-d1aef980-7102-11ea-8dde-42e484ef296c.png)

**Comment by alanmcgovern** [comment]
The infinite loop in the listener has been resolved and is in version 1.0.21 and newer. Do let me know if you have more issues!

https://github.com/alanmcgovern/monotorrent/commit/62cf0b8d75034f054b15eb8ccbbb3294a9c3b525
