### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by Spec-Nox** [alanmcgovern/monotorrent#284]
sorry, I'm not very experienced, but I can't understand what's wrong.

![Screenshot (76)](https://user-images.githubusercontent.com/58957863/78464629-d91a6800-76eb-11ea-9f55-e1b00a98bf77.png)
![Screenshot (75)](https://user-images.githubusercontent.com/58957863/78464598-9bb5da80-76eb-11ea-920f-627e75015fcb.png)

**Comment by alanmcgovern** [comment]
These are part of the normal operation of the client.

These exceptions are thrown by either the underlying framework, or monotorrent, and then are correctly handled.

**Comment by Spec-Nox** [comment]
thanks for the answer, i have a question to ask you,  can show the download percentage of a torrent file that is being downloaded ?(winform)

**Comment by alanmcgovern** [comment]
You can access `TorrentManager.Progress` for the % completion. If you look at `TorrentManager.Torrent.Files` you can get statistics for each individual file
