### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alessi12** [alanmcgovern/monotorrent#285]
hi, i get an error saying that the ability to download files via magnet link is obsolete.
there are no alternatives?

**Comment by alanmcgovern** [comment]
Can you tell me the exact wording of the message you're seeing? There are only a few usages of `[Obsolete]` in the codebase and they should all describe the new/correct way of accessing the information.

The closest thing I can find is:
```
        [Obsolete("Use MagnetLink.Parse instead of this method")]
        public static InfoHash FromMagnetLink (string magnetLink)
        => MagnetLink.Parse (magnetLink).InfoHash;
```
If you're using `InfoHash.FromMagnetLink(string)`, you should use `MagnetLink.Parse (string)` instead.

That said - if you want to download a torrent via a magnet link, my recommendation is to use this method to download the metadata (essentially the `.torrent` file) first: https://github.com/alanmcgovern/monotorrent/blob/ae2e4077a45a40de82d4294722abadd1cd12309a/src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs#L292-L299 . Once you have the metadata you should save it to disk (if desired) and then instantiate a TorrentManager using that metadata.

You can still create a TorrentManager using a MagnetLink without hitting a codepath marked with the [Obsolete] attribute: https://github.com/alanmcgovern/monotorrent/blob/ae2e4077a45a40de82d4294722abadd1cd12309a/src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs#L356 . My aim is to eventually obsolete this as I can simplify the internals if I completely separate metadata downloading from normal torrent downloading.

**Comment by alanmcgovern** [comment]
I'll close this for now as I don't think this is an issue. If there is still a problem, or an 'Obsolete' warning which I have missed, please reopen the issue and/or add another comment and I'll look further!

Thanks!
