### ISSUE TITLE
Bug with ExtendedHandshakeMessage.MaxRequests

### ISSUE THREAD

**Issue by Jashik** [alanmcgovern/monotorrent#287]
There is problem with `ExtendedHandshakeMessage.MaxRequests` because when creating `ExtendedHandshakeMessage` property `MaxRequests` not filed by value. 
And when this message parsed in `Mode.HandleExtendedHandshakeMessage` property `PeerId.MaxSupportedPendingRequests` become `1`.
Then in `Mode.PreLogicTick` value `PeerId.MaxPendingRequests` always will be `2` and this make bad effect on download speed.

**Comment by alanmcgovern** [comment]
That doesn't seem good at all! Do you think you could submit a pull request updating the code and adding a new test?

**Comment by alanmcgovern** [comment]
@carlisib this might be affecting you?

**Comment by carlosib** [comment]
Hello Alan!
Yes. I think this can be the big issue. When I try to download much files.... All be started but only some are download complete.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by alanmcgovern** [comment]
@Jashik Got that patched and merged! Do let me know if it helps performance for you!

@carlosib This may help performance for you too. This change will make MonoTorrent -> MonoTorrent connections better, which is one area you showed an issue.

**Comment by Jashik** [comment]
@alanmcgovern 
Yes. It's helps.
Thx

**Comment by carlosib** [comment]
Hello Alan!

About download speed I still have issue 🙁

Using monotornt app I have about 5mb download speed, but, using utorrent i have 50...60..80 mb download speed.



________________________________
De: Alan McGovern <notifications@github.com>
Enviado: segunda-feira, 13 de abril de 2020 08:31
Para: alanmcgovern/monotorrent <monotorrent@noreply.github.com>
Cc: carlosib <carlos_am_2003@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [alanmcgovern/monotorrent] Bug with ExtendedHandshakeMessage.MaxRequests (#287)


@Jashik<https://github.com/Jashik> Got that patched and merged! Do let me know if it helps performance for you!

@carlosib<https://github.com/carlosib> This may help performance for you too. This change will make MonoTorrent -> MonoTorrent connections better, which is one area you showed an issue.
