### ISSUE TITLE
Any way to turn a torrent file into a magnet link?

### ISSUE THREAD

**Issue by Suyashtnt** [alanmcgovern/monotorrent#288]
more of a question but simple: just convert a string with the contents of a torrent file and turn it into a magnet link?

**Comment by alanmcgovern** [comment]
If you can get the raw byte[] representing the torrent data then you can use Torrent.Load to parse it into a torrent instance. That can be converted into a MagnetLink, or a magnet link can be constructed using data from the Torrent instance. 

NOTE: if your string was created by calling System.Text.Encoding.UTF8.GetString then the data will be corrupt and you can't construct a valid torrent from it anymore. The only safe way to store the .torrent data as a string is to base64 encoded it, or something alone those lines. You must always treat the .torrent data as a raw byte[] as it contains byte sequences which cannot be represented in UTF8 or UTF16 etc, which means if you attempt to turn it into a string you'll silently discard those bytes

**Comment by Suyashtnt** [comment]
and how do I go about doing that

**Comment by vlasenkoalexey** [comment]
You can just add following method to torrent.cs:
`        public MagnetLink ToMagnetLink()
        {
            return new MagnetLink(this.InfoHash, name: this.Name, announceUrls: this.AnnounceUrls.SelectMany(tier => tier).ToList());
        }
`

**Comment by alanmcgovern** [comment]
If there's something specific you are still unclear about do let me know. The high level description, along with the in-line Xml documentation which will be displayed on intellisense, should cover everything!
