### ISSUE TITLE
Using the StreamProvider

### ISSUE THREAD

**Issue by jangofett4** [alanmcgovern/monotorrent#294]
Hello!
I am writing an application to mount torrent files as filesystem.
Listing the files/directories and getting sizes etc. was easy and is already done, but I am having a bad time streaming data.
So my idea was to stream from internet rather than downloading entire files, so when a file is requested by user, it is streamed to user slowly.
Since documentation for this project is kind of sparse I decided to ask here.
So my torrent, engine and stream provider code is as follows:
```cs
/* Create torrent object */
TorrentObject = Torrent.Load(TorrentFile);

// Setup engine and streaming
Engine = new ClientEngine();

StreamProvider = new StreamProvider(Engine, tempdir, TorrentObject);
StreamProvider.StartAsync().Wait();
```
When user requests a file following piece of code is executed:
```cs
var task = StreamProvider.CreateStreamAsync(file);
// Wait for it to create connection
task.Wait();
var stream = task.Result;
stream.Position = offset;

if (stream.Length - stream.Position > BufferSize)
{
    int rd = (int)(stream.Length - stream.Position);
    buffer = new byte[rd];
    stream.Read(buffer, 0, rd);
    bytesRead = rd;
}
else
{
    buffer = new byte[BufferSize];
    stream.Read(buffer, 0, BufferSize);
    bytesRead = BufferSize;
}
stream.Close();
```
It might be a little not-optimized, since creating & destroying the stream over and over again might slow down the application, but that is not the concern for now.
This piece of code throws an exception at 'task.Wait()' with following message:
`Specified argument was out of the range of valid values. `
Argument said is `index`, which I have no clue about.  
I also tried other things such as custom PiecePicker, but I cant wrap my head around how it works.  
I am kind of new to 'bittorrent library' stuff, I know how it works internally (a little bit).  
Any help is appreciated.

EDIT:  
So testing with barebones I realized it works with this program:
```cs
using System;

using MonoTorrent;
using MonoTorrent.Client;
using MonoTorrent.Streaming;

namespace TorrentTest
{
    class Program
    {
        static void Main(string[] args)
        {
            string torrentfile = "knoppix.torrent";
            Torrent torrent = Torrent.Load(torrentfile);
            ClientEngine engine = new ClientEngine();
            StreamProvider provider = new StreamProvider(engine, "D:\\Temp", torrent);
            provider.StartAsync().Wait(); // wait for it to start
            var file = torrent.Files[0]; // knoppix iso file
            var task = provider.CreateStreamAsync(file);
            task.Wait();
            Span<byte> buffer = new Span<byte>(new byte[1024]);
            task.Result.Read(buffer);
            //
            Console.WriteLine(buffer.ToString());
            return;
        }
    }
}
```  
Tested with knoppix.torrent ([knoppix.zip](https://github.com/alanmcgovern/monotorrent/files/4566129/knoppix.zip))  
Originally my code crashes at `task.Wait()`. I recognized something interesting, program waits more than usual. So my guess is Windows triggers ReadFile of my virtual disk class couple of times when result does not return in time and that somehow breaks streaming.  
Maybe I should create a cache for already created file streams and reject same file requests if it is being created?

**Comment by alanmcgovern** [comment]
Can you create a testcase which you can share with me to help diagnose this issue?

If not, can you at least share the full stacktrace from the exception as it should help me figure out what line of code is throwing the exception.

As it stands, i think there could be an error in your logic. If I'm reading the code right your `else` statement is trying to read `BufferSize` bytes from the stream *when the stream has less than that number of bytes available`. I think you need to flip the if and else so it looks like this:

```
if (stream.Length - stream.Position > BufferSize)
{
    // If we have *lots* of bytes available, read a full buffer.
    buffer = new byte[BufferSize];
    bytesRead  = stream.Read(buffer, 0, BufferSize);
}
else
{
    int rd = (int)(stream.Length - stream.Position);
    buffer = new byte[rd];
    bytesRead  = stream.Read(buffer, 0, rd);
}
````

NOTE: Like every `Stream` implementation - the guarantee is that Stream.Read will return `0` if the stream is over, otherwise it will return at least one byte and at most `count` bytes. It is not correct to assume that Stream.Read (10) will return exactly 10 bytes. As such you should use the return value from `Read` to determine how many bytes were actually read, and to bail out if `0` bytes are read.

**Comment by jangofett4** [comment]
The problem is application doesn't even reach to 'if' statements when a file is requested.  
When application is waiting for the Stream to create at `task.Wait()` exception is thrown `Specified argument was out of the range of valid values (index).`.
I will write a small .NET Core project to demonstrate the problem and update the issue in 10 minutes.

**Comment by alanmcgovern** [comment]
It looks like the issue could be specific to your program. 

If that's the case you will need to share the stacktrace of the exception so i can begin to diagnose the issue. At the moment there's not enough information to draw any conclusions :(

**Comment by jangofett4** [comment]
Nope I fixed the problem. It was related to Windows all along. Windows requests file after file, before previous file is done loading (or DokanNET does that), so waiting before creating another task fixed it. Now I have another problem, which tasks get stuck at WaitingForActivation state, I am not sure what causes that. Thank you for helping!

**Comment by alanmcgovern** [comment]
Ah great. Glad you got that sorted out!

I'll close this for now, but if you have any further issues do let me know!

(I am assuming the waiting for activation thing is unrelated to MonoTorrent as it never creates Task objects which need to be manually started :) )
