### ISSUE TITLE
Socks proxy support

### ISSUE THREAD

**Issue by vlasenkoalexey** [alanmcgovern/monotorrent#296]
It would be nice to have socks proxy support.

**Comment by alanmcgovern** [comment]
If you know of a library which supports socks you could implement a custom IConnection.

You'd need to implement the `IConnection` interface, call `ConnectionFactory.Register ("ipv4", typeof (YourIConnection)` and ensure your implementation has a constructor which takes a `Uri` parameter.

This is all public API so you don't need to modify monotorrent itself to test different libraries/approaches.

As it stands I'm not familiar enough with libraries implementing proxy support to recommend one to integrate with. I can definitely give more help if needed though!

**Comment by alanmcgovern** [comment]
@vlasenkoalexey I'd be happy to take a contribution which adds a `MonoTorrent.Socks` library to the project, as long as that is implemented using an existing maintained/supported Socks library. I don't particularly want to maintain a socks library myself, but i'd happily maintain the glue code required to integrate an existing library with monotorrent :)

As it is relatively trivial for someone to integrate a socks library using the existing API, and as I don't have any near-term intention to implement this, I'll close this issue for now.

The idea is definitely worthwhile though!

**Comment by vlasenkoalexey** [comment]
There are few SocksProxy implementations, like this one: https://github.com/poma/ProxySocket
But integration is not going as simple as adding new proxy connection type. 
If user chooses to use proxy, his IP address should never be surfaced, which means that all networking classes like Socket, HttpClient, etc will have to be replaced with ones that support proxy.
And on the other hand, any decent BitTorrent app nowdays is expected to have Socks support.

**Comment by NickStrupat** [comment]
There is a good, small implementation here:
https://gist.github.com/zHaytam/3730d512eb5eaf37fb3bd3d176185541

...and the corresponding blog post:
https://blog.zhaytam.com/2019/11/15/socks5-a-net-core-implementation-from-scratch/

**Comment by rupisaini123** [comment]
When we are going to get SOCKS5 support on nuget?

**Comment by alanmcgovern** [comment]
A few things:
1) Decide whether to release a NuGet which uses https://github.com/alanmcgovern/DotProxify , which means completing support for UDP forwarding for DotProxify. Once MonoTorrent 3.x is in a public nuget people can integrate with pretty much any alternative SOCKS library so this isn't too big of a deal. However a fully functional implementation using *any* library would be good.
2) Test using at least one other SOCKS proxy implementation. It's all well and good that it worked for me using ShinySocks - extra validations would be nice.
3) Completing support for BEP52 is something i want to do for monotorrent 3.0.

**Comment by alanmcgovern** [comment]
https://github.com/alanmcgovern/monotorrent.socks5/releases/tag/release-v0.1.0

There's a nuget there which is compatible with the pre-release versions of monotorrent (built from master). It needs further testing as I just copied/pasted code and build config. It'll be on NuGet.org in the near future, soon after MonoTorrent 3.x pre-releases are on NuGet.org.

Thanks!
