### ISSUE TITLE
Xamarin

### ISSUE THREAD

**Issue by Vuyiswamb** [alanmcgovern/monotorrent#298]
Hi all 
I tried to use MonoTorent in Xamarin. I just can't get it to work. UI thread get constantly blocked , starting the engine takes time. An example or a lib I can use is appreciated.

**Comment by alanmcgovern** [comment]
Can you share a sample project which reproduces the issue?

Bugs which would cause the UI thread to block should reproduce equally well on desktop or mobile. The latest releases have explicitly moved some operations to the threadpool to reduce blocking the engine itself. However those tasks should not have blocked the UI thread in a UI application

The sample project in the repository loads up torrent files from disk and downloads them. That should be a fairly reasonable example to look at.

**Comment by Vuyiswamb** [comment]
Thanks for your kind reply

This  part takes long with no exception 

```
await  engine.RegisterDhtAsync(dht);
                // This starts the Dht engine but does not wait for the full initialization to
                // complete. This is because it can take up to 2 minutes to bootstrap, depending
                // on how many nodes time out when they are contacted.
await engine.DhtEngine.StartAsync(nodes);
```

if no Torrent file found  on this line 

`foreach (string file in Directory.GetFiles(torrentsPath))
[MonoDev.zip](https://github.com/alanmcgovern/monotorrent/files/4623600/MonoDev.zip)
`

it fails and freeze the UI from Debug bu when you run the app it fails 

I have attached the example code  

http://robotica.vimalsoft.com/MonoDev.zip

**Comment by alanmcgovern** [comment]
I think your app hangs because there's an infinite `while (true)` loop on line 338 of MainPage.xaml.cs.

This is fine in a console application, but in a proper GUI application you'll want to handle updates using the events, or on a timer

**Comment by Vuyiswamb** [comment]
Thanks for the reply , 
i went through the code. made a change put a timer. but that part of the code is not hit yet. 

looks like the code hangs if i await this two lines 

```
  await  engine.RegisterDhtAsync(dht);
  await engine.DhtEngine.StartAsync(nodes);

```
when i remove then await , passes fast. now all move well. My torrent file in the Torrent folder is not seen but that one i can resolve. my issue now is that when it does not find a Torrent file it gives an error 
**System.InvalidCastException: 'Specified cast is not valid.'**

**Comment by alanmcgovern** [comment]
Hrm, interesting. Can you share the file so I can diagnose the issue? That looks like a malformed torrent, or just a bug in MonoTorrent. Either way it should be fixable!

**Comment by Vuyiswamb** [comment]
hi Alan 

here is the Torrent file http://robotica.vimalsoft.com/big-buck-bunny.zip

**Comment by Vuyiswamb** [comment]
i have made an Update , i get this error 

http://robotica.vimalsoft.com/MonoDev2.rar

**System.InvalidCastException: 'Specified cast is not valid.'**

**Comment by alanmcgovern** [comment]
The InvalidCastException isn't coming from loading the .torrent file as I expected.

Can you give the full stacktrace for the error? Without the stacktrace I won't be able to diagnose the issue as I cannot reproduce it locally. I don't have the Xamarin toolchain installed so I won't be able to compile and launch your application. I can review the source code by eye though.

Thanks!

**Comment by Vuyiswamb** [comment]
hi Alan 

Hope all is well your side. Here is the statck trace below 
 
Thread started: DhtLoop #10
05-14 22:55:11.060 D/Mono    (15777): Requesting loading reference 10 (of 16) of netstandard.dll
05-14 22:55:11.060 D/Mono    (15777): Loading reference 10 of netstandard.dll asmctx DEFAULT, looking for System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
05-14 22:55:11.060 D/Mono    (15777): Image addref System.Numerics[0x81dc9038] (asmctx DEFAULT) -> System.Numerics.dll[0x81dc9550]: 2
05-14 22:55:11.060 D/Mono    (15777): Prepared to set up assembly 'System.Numerics' (System.Numerics.dll)
05-14 22:55:11.060 D/Mono    (15777): Assembly System.Numerics[0x81dc9038] added to domain RootDomain, ref_count=1
05-14 22:55:11.060 D/Mono    (15777): Config attempting to parse: 'System.Numerics.dll.config'.
05-14 22:55:11.060 D/Mono    (15777): Config attempting to parse: '/Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/sdks/out/android-armeabi-v7a-release/etc/mono/assemblies/System.Numerics/System.Numerics.config'.
05-14 22:55:11.060 D/Mono    (15777): Assembly Ref addref netstandard[0x7cd3f6c8] -> System.Numerics[0x81dc9038]: 2
05-14 22:55:11.060 D/Mono    (15777): Requesting loading reference 0 (of 1) of System.Numerics.dll
05-14 22:55:11.060 D/Mono    (15777): Loading reference 0 of System.Numerics.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
05-14 22:55:11.060 D/Mono    (15777): Assembly Ref addref System.Numerics[0x81dc9038] -> mscorlib[0x758ee6b0]: 54
Loaded assembly: System.Numerics.dll [External]
Loaded assembly: Anonymously Hosted DynamicMethods Assembly [External]
Thread finished: <Thread Pool> #4
The thread 0x4 has exited with code 0 (0x0).
Thread started: <Thread Pool> #11
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
Thread started: <Thread Pool> #14
Thread finished: <Thread Pool> #3
The thread 0x3 has exited with code 0 (0x0).
Thread started: <Thread Pool> #15
05-14 22:55:28.670 I/Choreographer(15777): Skipped 1025 frames!  The application may be doing too much work on its main thread.
05-14 22:55:28.720 I/Timeline(15777): Timeline: Activity_idle id: android.os.BinderProxy@430f0dc8 time:1894566
05-14 22:55:31.440 D/Mono    (15777): DllImport searching in: 'libmono-native.so' ('./libmono-native.so').
05-14 22:55:31.440 D/Mono    (15777): Searching for 'SystemNative_GetReadDirRBufferSize'.
05-14 22:55:31.440 D/Mono    (15777): Probing 'SystemNative_GetReadDirRBufferSize'.
05-14 22:55:31.440 D/Mono    (15777): Found as 'SystemNative_GetReadDirRBufferSize'.
05-14 22:55:31.440 D/Mono    (15777): DllImport searching in: 'libmono-native.so' ('./libmono-native.so').
05-14 22:55:31.440 D/Mono    (15777): Searching for 'SystemNative_OpenDir'.
05-14 22:55:31.440 D/Mono    (15777): Probing 'SystemNative_OpenDir'.
05-14 22:55:31.440 D/Mono    (15777): Found as 'SystemNative_OpenDir'.
05-14 22:55:31.470 D/Mono    (15777): DllImport searching in: 'libmono-native.so' ('./libmono-native.so').
05-14 22:55:31.470 D/Mono    (15777): Searching for 'SystemNative_ReadDirR'.
05-14 22:55:31.470 D/Mono    (15777): Probing 'SystemNative_ReadDirR'.
05-14 22:55:31.470 D/Mono    (15777): Found as 'SystemNative_ReadDirR'.
05-14 22:55:31.470 D/Mono    (15777): DllImport searching in: 'libmono-native.so' ('./libmono-native.so').
05-14 22:55:31.470 D/Mono    (15777): Searching for 'SystemNative_CloseDir'.
05-14 22:55:31.470 D/Mono    (15777): Probing 'SystemNative_CloseDir'.
05-14 22:55:31.470 D/Mono    (15777): Found as 'SystemNative_CloseDir'.
Thread started: <Thread Pool> #16
Thread started: <Thread Pool> #17
Thread started: <Thread Pool> #18
Thread started: <Thread Pool> #19
Thread started: <Thread Pool> #20
Thread started: <Thread Pool> #21
Thread started: <Thread Pool> #22
**System.InvalidCastException:** 'Specified cast is not valid.'

Thread finished: <Thread Pool> #12
The thread 0xc has exited with code 0 (0x0).

**Comment by alanmcgovern** [comment]
Hi,

Unfortunately the stacktrace is missing. Without that information there's no reason to believe the issue is related directly to MonoTorrent. 

It's possible there's a bug in code autogenerated from your Android interface axml file, or a bug elsewhere in your code, which is triggering this exception. There's no way for me to tell. 

Can you reproduce the issue by launching the application with the debugger attached? If so, could you screenshot the stacktrace when the exception is thrown?

**Comment by Vuyiswamb** [comment]
hi Alan 

i found the issue. the Listview was the issue. when i comment that it worked. now i need to use the Torrent File. for some reason i am not able to get to the torrent file. but i will get it to work

**Comment by alanmcgovern** [comment]
Great! I'll assume everything is OK with monotorrent for now. If you have any issues do let me know!

**Comment by Vuyiswamb** [comment]
Thank you very much. all is in order
