### ISSUE TITLE
Peer user agent.

### ISSUE THREAD

**Issue by justscribe** [alanmcgovern/monotorrent#308]
Hi,

It would be great if there will be a property with client user agent for Peer object.

**Comment by alanmcgovern** [comment]
you can get a list of connected peers using:

```
List<PeerID> peers = await TorrentManager.GetPeersAsync ()
```

You can get the peer's unique identifier by calling `peers[0].PeerID` and you can view information about the torrent application the peer is using by accessing `peers[0].ClientApp`.

Is that the information you need, or is it something else?

**Comment by justscribe** [comment]
I mean "User-Agent" header.

**Comment by justscribe** [comment]
And that's all propetries, what we have for the latest version.
![image](https://user-images.githubusercontent.com/8200485/83838362-a7307c80-a701-11ea-8efe-d8ab59befd18.png)

**Comment by justscribe** [comment]
Forgot, it's inside TorrentTracker, it using a Peer, not PeerId class, from methods:
List<ITrackerItem> trackerTorrentList = aTracker.GetTrackerItems();
List<MonoTorrent.Tracker.Peer> peers = trackerTorrent.GetPeers();

**Comment by alanmcgovern** [comment]
ah yes! That isn't tracked in the 'Tracker' server code. It should be relatively easy to add! If you want to submit a PR i can merge it, otherwise i can add it in the next few days (or week) :)

**Comment by justscribe** [comment]
Merged.
https://github.com/alanmcgovern/monotorrent/pull/309
