### ISSUE TITLE
[Question] Testing in local environment

### ISSUE THREAD

**Issue by boiss-dev** [alanmcgovern/monotorrent#311]
hi,
First of all, congratulations for the work. 

However, I have a small problem when I want to test in my local environment. cf screenshot.

![screenshot](https://i.imgur.com/WeTHPjt.jpg)

I can connect to the MonoTorrent Tracker when I set directly the IP 127.0.0.1 from qBittorrent and my ClientEngine. If I use `IPAddress.Any`, it doesnot work at all.
But If you see on the screen, my ClientEngine with the IP/Port 127.0.0.1:301 cannot communicate with my qBittorrent Client with the IP/Port 127.0.0.1:8381.

Not sure from where can come the problem. Any idea ? If I use opentrackr.org instead of my local server it's working.

Thanks

**Comment by alanmcgovern** [comment]
I suspect you're hitting a known limitation of how HttpListener is intended to work nowadays. 

Does the information here match your experience? https://github.com/alanmcgovern/monotorrent/issues/299#issuecomment-638645652

**Comment by boiss-dev** [comment]
hum not sure, I will test to build the TrackerApp as is and deploy it to heroku to test.
I will make you a feedback.
Thanks for your answer.

**Comment by boiss-dev** [comment]
in fact your comment and the search of @justscribe helped me, but my listener handles the request as expected, as you can see on my screenshot, my qBittorrent client status is Working.

My question is more generic to test in a local environment, my 2 clients did not connect to each other. I don't know why.
I finally found a configuration that works.
- Custom Tracker in Worker Service with MonoLibrary (dotnet core 3.1.4 with @justscribe remarks in [#299 (comment)](https://github.com/alanmcgovern/monotorrent/issues/299#issuecomment-638645652))
- Seed with a Transmission Client
- Leech with a qBittorrent Client

Thanks again for this great library and quick answer.

**Comment by alanmcgovern** [comment]
Some clients will block incoming connections, or refuse to create an outgoing connection, if the IP address matches their own IP address. 

As such, you may find it 'impossible' to force two clients on the same network to connect to each other if they report the same IP address to the tracker. 

UTorrent has a setting which a allows local connections. MonoTorrent doesn't rely on the IPAddress, it also uses the peerid. 

Other clients may vary :)
