### ISSUE TITLE
User-Agent header lost in .Net Core (but some tracker is still need it)

### ISSUE THREAD

**Issue by usikpavel** [alanmcgovern/monotorrent#314]
In the latest version (1.0.22) I found that User-Agent header doesn't exist. So, I suggest a fix:
`client.DefaultRequestHeaders.Add ("User-Agent", VersionInfo.ClientVersion);`
This is line **88** in file **MonoTorrent.Client.Tracker/HTTPTracker.cs**

_Originally posted by @usikpavel in https://github.com/alanmcgovern/monotorrent/pull/4#issuecomment-647043107_

**Comment by alanmcgovern** [comment]
Thanks for filing! I've just patched that for Announce and Scrape requests.
