### ISSUE TITLE
Creating a torrent file Xamarin

### ISSUE THREAD

**Issue by Vuyiswamb** [alanmcgovern/monotorrent#318]
I managed to make MonoTorrent work in Xamarin Android. I download a file from an example torrent. Now I want to be able to create a Torrent file for the files that needs to be shared , how can I do that. I saw a few methods but not sure which one is the correct one. Another thing that I noticed is Trackers if I do this does it mean I have to host some tracking site for the app? 

Thanks

**Comment by alanmcgovern** [comment]
The `TorrentCreator` class can be used to create new torrents from files ( https://smuxi.im/wiki/monotorrent/Creating_Torrents ).

You can host a Tracker yourself, use http://opentrackr.org or something similar, or rely on DHT. On a mobile device I'd probably recommend against DHT as it is a very chatty protocol and would be quite hard on battery life.

If you have any other questions let me know!
