### ISSUE TITLE
Download speed is very slow

### ISSUE THREAD

**Issue by DmitriyV** [alanmcgovern/monotorrent#32]
We are using latest version.

TestCase:
- Put torrent https://dl.dropboxusercontent.com/u/64014628/29527d6eb9722b09aeec04402352fecc.torrent
- Start SampleClient from solution

Results:
- Download speed: 160 Kb/s
- Peers: 31  
- Connected Peers: 3
- 4 trackers

Try to use uTorrent for the same torrent. You will see:
- Download speed: 2,8 Mb/s
- Peers: 6
- Connected Peers: 4
- 2 trackers

How can we find problem reason?

**Comment by gadail47** [comment]
Hi guys. I guess i could solve this shit. Just use method engine.AddAsync and... that is all...
This solve my problem. Good luck
