### ISSUE TITLE
StreamProvider Torrent.Files is always null.

### ISSUE THREAD

**Issue by Kajirinn** [alanmcgovern/monotorrent#320]
Hello there, this is probably a mistake on my part but I can't figure it out for the life of me. I've been trying to find documentation about the StreamProvider, or the library in general; but have been having a rough time.

I'm trying to develop a simple video streaming application in .NET Framework so I don't have to fully download torrents before watching them. I've worked a bunch with vlcdotnet before so that isn't necessarily a problem, it's just I'm currently stuck on the `CreateHttpStreamAsync()` as the torrent files always return null.

I've been trying to figure it out through bits and pieces of codes from closed issues, such as #315 and #294, but it's sadly not working out for me.

```
MagnetLink MagnetLink = MagnetLink.Parse(magnet);
ClientEngine Engine = new ClientEngine();

StreamProvider StreamProvider = new StreamProvider(Engine, @"D:\Temp\test.torrent", MagnetLink, @"D:\Temp\meta.torrent");
await StreamProvider.StartAsync();
await StreamProvider.WaitForMetadataAsync();

Stream stream = await StreamProvider.CreateStreamAsync(StreamProvider.Manager.Torrent.Files[0]);
```

I don't think I'm understanding it correctly, why would the streamprovider need the torrent file itself, when it only recently 'started' with the magnet link I provided? Why is it still null after it supposedly waited for the metadata? The magnet link is valid as a client such as BitTorrent is loading it in correctly.

Besides this issue, are there any starting guides or simple sample projects? I peeked a little in the sample projects I've found, but either they're overwhelmingly big for the simple task that I want to achieve, or out of date.

Forgive my ignorance, and thanks in advance.

**Comment by Kajirinn** [comment]
Upon messing around with it a tad bit more, I realized that the dir's don't want extensions. The `WaitForMetadataAsync()` now populates the `StreamProvider.Files`, instead of the `StreamProvider.Manager.Torrent.Files`. This generates a metadata torrent if I understand it correctly, but still throws an error on the `CreateStreamAsync()`.

```
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
System.NullReferenceException: Object reference not set to an instance of an object.
   at MonoTorrent.Streaming.StreamProvider.<CreateStreamAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Test.MainWindow.<Load>d__2.MoveNext() in D:\Development\Repos\Test\MainWindow.xaml.cs:line 77
```

Where line 77 is `Stream stream = await StreamProvider.CreateStreamAsync(StreamProvider.Files[0]);`.

What am I doing wrong here? I've also noticed that for some torrents the waitformetadata simply doesn't load.

**Comment by alanmcgovern** [comment]
@kajirinn This is, unfortunately, just a bit buggy.

If 'waitForMetadata' doesn't complete it's probably because peers which support metadata mode cannot be found. 

If 'Files' is null, or you see weird null reference exceptions, it's because it's buggy and I've (somewhat) addressed that in the PR i linked to this issue. This needs more thorough integration tests between these two components as the unit tests don't cover the use case.

If you want to test that branch do let me know how that works out. I'll improve the testing around this particular piece of the code and get that branch finalised/merged over the next few days

**Comment by alanmcgovern** [comment]
This should be resolved in master now. Do let me know if you have further issues.

Thanks for reporting!
