### ISSUE TITLE
web seed

### ISSUE THREAD

**Issue by l-quinto** [alanmcgovern/monotorrent#321]
Hello. Web seed download not working? Through uTorrent it works fine

**Comment by alanmcgovern** [comment]
What exactly doesn't work? Do you have a sample demonstrating the problem?

**Comment by l-quinto** [comment]
I don't even know how to demonstrate this. Connects but does not download.

**Comment by alanmcgovern** [comment]
Do you have a .torrent which uses webseeds which I can use to reproduce the problem?

**Comment by alanmcgovern** [comment]
This issue should be fixed with the latest release.

Can you let me know which version you're using so I can double check you have the fix?

**Comment by wizard872** [comment]
webseed not working too i think.

tixati, uTorrent work, but monotorrent's webseed is not working.

i want use webseed  like [ https://github.com/alanmcgovern/monotorrent/pull/152 ] .

**Comment by samhocevar** [comment]
@l-quinto @ScorpionsSM can you maybe have a look at these [web seeding fixes](https://github.com/alanmcgovern/monotorrent/issues/331#issuecomment-716667597) and confirm whether it works again? Thanks!

**Comment by alanmcgovern** [comment]
I assume this has been resolved with the same patch as https://github.com/alanmcgovern/monotorrent/issues/331 . 

Thanks for reporting!
