### ISSUE TITLE
Wrong value of LocalPeerDiscovery.BroadcastEndPoint property 

### ISSUE THREAD

**Issue by vstrizhakov** [alanmcgovern/monotorrent#322]
The BroadcastEndPoint in LocalPeerDiscovery seems to be wrong because it's current ip-address is IPAddress.Broadcast, but if I'm not wrong, it must be the 239.192.152.143, as specified in BEP 14. At least, if I use the IPAddress.Broadcast one, my udp-receiver (on another machine) doesn't receive the multicast message. And with 239.192.152.143 ip-address everything work like it need to be.

**Comment by alanmcgovern** [comment]
Your patch has been merged so i'll go ahead and close this! Thanks for submitting the PR!
