### ISSUE TITLE
MonoTorrent.ListenerStatus.PortNotFree

### ISSUE THREAD

**Issue by gawric** [alanmcgovern/monotorrent#333]
Hello.
sorry for my eng.
problem: can't find other clients
run the file 
[](url)
http://hh-soft.ru/filedownload/eyJ0b2tlbiI6IjUzYWU0ZmY1MzBhMDU0YzQ2NTAzYzg1NjliM2UxZDFhZmVkY2ZiZjM5NGRhOTNiYWFiMjljZGU4ZTBjOGE5MzQifQ==

Status MonoTorrent(VS Debugger): Engine->listener: MonoTorrent.ListenerStatus.PortNotFree  (all the time)

version monotorrent- 1.0.24
version NAT - 2.2

pc computer connection: tp-link router: use NAT

μTorrent Сlient  connects normally

**Comment by alanmcgovern** [comment]
If you're getting a 'port not free' it means some other program is using the port you're asking monotorrent to use.

Have you tried using a different port number in monotorrent?

**Comment by alanmcgovern** [comment]
I'll close this for now as it's unclear what exactly is going wrong here. Please feel free to reopen if the issue still reliably occurs and we'll dig into it!
