### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by alJah** [alanmcgovern/monotorrent#336]
Hello. Since yesterday, a MissingMethodException error has appeared in a previously working project.
Error Text: 
Method not found:" Void Mono.Nat.NatUtility.add_DeviceLost (System.EventHandler`1 <Mono.Nat.DeviceEventArgs>) ".

![2020-11-14 (4)](https://user-images.githubusercontent.com/19330733/99140973-d49e3080-2678-11eb-833e-9f15b5170847.png)
Thanks.
![2020-11-14 (3)](https://user-images.githubusercontent.com/19330733/99141059-96554100-2679-11eb-9849-dcf237fb21d3.png)

**Comment by alJah** [comment]
The solution worked. I was wrong with the versions. Sorry

**Comment by alJah** [comment]
Rolled back Mono.Nat to version 2.0.2

**Comment by alanmcgovern** [comment]
I improperly set the max supported version of mono.nat in the csproj. I'll fix that shortly!

In the meantime I issued a new release of MonoTorrent which is compatible with the latest Mono.Nat release. Version 1.0.25 should be on NuGet now and will work with Mono.Nat 3.0.0+

Thanks!

**Comment by alJah** [comment]
Thanks for your work.


Отправлено из приложения "Почта" для Windows 10

От: Alan McGovern
Отправлено: 14 ноября 2020 г. в 21:19
Кому: alanmcgovern/monotorrent
Копия: GRText; State change
Тема: Re: [alanmcgovern/monotorrent] MissingMethodException (#336)

I improperly set the max supported version of mono.nat in the csproj. I'll fix that shortly!
In the meantime I issued a new release of MonoTorrent which is compatible with the latest Mono.Nat release. Version 1.0.25 should be on NuGet now and will work with Mono.Nat 3.0.0+
Thanks!
