### ISSUE TITLE
MonoTorrent does connect but does not download a single byte

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#339]
I'm trying to download using the provided client setup. Result is that **MonoTorrent** does connect with 3 peers but does not download. 

**Console output after about 3 minutes:**

Total Upload Rate:   0.00kB/sec
Disk Read Rate:      0.00 kB/s
Disk Write Rate:     0.00 kB/s
Total Read:         0.00 kB
Total Written:      0.00 kB
Open Connections:    3

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

State:           Downloading
Name:            TheGoodGoodGiver
Progress:           0.00
Download Speed:     0.00 kB/s
Upload Speed:       0.00 kB/s
Total Downloaded:   0.00 MB
Total Uploaded:     0.00 MB
Tracker Status
        http://bt1.archive.org:6969/announce : Announce Succeeded: True. Scrape Succeeded: False.
        http://bt2.archive.org:6969/announce : Announce Succeeded: True. Scrape Succeeded: True.
Current Requests:   0
        0 - 0.00/0.00kB/sec - https://archive.org/download/
        0 - 0.00/0.00kB/sec - http://ia601006.us.archive.org/12/items/
        0 - 0.00/0.00kB/sec - http://ia801006.us.archive.org/12/items/

Total torrent files: 3
0.00% - The Good Good - Giver.zip
0.00% - TheGoodGoodGiver_meta.sqlite
0.00% - TheGoodGoodGiver_meta.xml

**Torrent I am testing with can be downloaded here:**

https://archive.org/download/TheGoodGoodGiver/TheGoodGoodGiver_archive.torrent

My firewall if disabled.
I am using encrypted:
            AllowedEncryption = EncryptionTypes.All;  // treid all available options.
            PreferEncryption = true;

**Output from vs2019:**

Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
OldState: Stopped NewState: Starting
OldState: Starting NewState: Hashing
Piece Hashed: 0 - Fail
Piece Hashed: 1 - Fail
Piece Hashed: 10 - Fail
Piece Hashed: 3 - Fail
Piece Hashed: 4 - Fail
Piece Hashed: 2 - Fail
Piece Hashed: 5 - Fail
Piece Hashed: 8 - Fail
Piece Hashed: 9 - Fail
Piece Hashed: 11 - Fail
Piece Hashed: 7 - Fail
Piece Hashed: 12 - Fail
Piece Hashed: 16 - Fail
Piece Hashed: 15 - Fail
Piece Hashed: 13 - Fail
Piece Hashed: 14 - Fail
Piece Hashed: 19 - Fail
Piece Hashed: 24 - Fail
Piece Hashed: 6 - Fail
Piece Hashed: 17 - Fail
Piece Hashed: 18 - Fail
Piece Hashed: 23 - Fail
Piece Hashed: 21 - Fail
Piece Hashed: 30 - Fail
Piece Hashed: 22 - Fail
Piece Hashed: 20 - Fail
Piece Hashed: 25 - Fail
Piece Hashed: 29 - Fail
Piece Hashed: 35 - Fail
Piece Hashed: 36 - Fail
Piece Hashed: 32 - Fail
Piece Hashed: 34 - Fail
Piece Hashed: 28 - Fail
Piece Hashed: 40 - Fail
Piece Hashed: 31 - Fail
Piece Hashed: 27 - Fail
Piece Hashed: 43 - Fail
Piece Hashed: 37 - Fail
Piece Hashed: 39 - Fail
Piece Hashed: 33 - Fail
Piece Hashed: 47 - Fail
Piece Hashed: 38 - Fail
Piece Hashed: 42 - Fail
Piece Hashed: 41 - Fail
Piece Hashed: 45 - Fail
Piece Hashed: 46 - Fail
Piece Hashed: 50 - Fail
Piece Hashed: 44 - Fail
Piece Hashed: 49 - Fail
Piece Hashed: 51 - Fail
Piece Hashed: 52 - Fail
Piece Hashed: 26 - Fail
Piece Hashed: 48 - Fail
OldState: Hashing NewState: Downloading
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in ReusableTasks.dll
Exception thrown: 'System.Net.Sockets.SocketException' in ReusableTasks.dll
Exception thrown: 'System.Net.Sockets.SocketException' in ReusableTasks.dll
Connection failed: ipv4://86.84.127.47:37827/ - Unreachable - All
Exception thrown: 'System.Net.Sockets.SocketException' in ReusableTasks.dll
Exception thrown: 'System.Net.Sockets.SocketException' in ReusableTasks.dll
Exception thrown: 'System.Net.Sockets.SocketException' in ReusableTasks.dll
Connection failed: ipv4://86.84.127.47:37827/ - Unreachable - All
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'MonoTorrent.Client.Tracker.TrackerException' in MonoTorrent.dll
Exception thrown: 'MonoTorrent.Client.Tracker.TrackerException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
The thread 0x17b8 has exited with code 0 (0x0).
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
The thread 0xb50 has exited with code 0 (0x0).
The thread 0x2748 has exited with code 0 (0x0).
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in mscorlib.dll
Exception thrown: 'System.Net.WebException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in mscorlib.dll
Exception thrown: 'System.Net.WebException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
The thread 0x2f18 has exited with code 0 (0x0).
The thread 0x28d0 has exited with code 0 (0x0).
The thread 0x2e88 has exited with code 0 (0x0).
The thread 0x1978 has exited with code 0 (0x0).
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Connection succeeded: https://archive.org/download/
Connection succeeded: http://ia601006.us.archive.org/12/items/
Connection succeeded: http://ia801006.us.archive.org/12/items/
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in mscorlib.dll
Exception thrown: 'System.Net.WebException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in mscorlib.dll
Exception thrown: 'System.Net.WebException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

**Comment by alanmcgovern** [comment]
The issue should be resolved with this patch: https://github.com/alanmcgovern/monotorrent/commit/50345740b44ee80135cc5ac6efd81747bf4cb171

I was able so successfully download the torrent after that change. Let me know if you have further issues!

**Comment by borrelnoten** [comment]
Yes, it download perfectly now! When will the update be applied in the GNU package?

**Comment by alanmcgovern** [comment]
I don't know who manages packages for the various flavours of *nix these days so I don't know when it will be updated.

The current master branch is a heavily refactored API/ABI breaking update. I've been a wary of shipping alpha releases of MonoTorrent 2.x as I want to ensure all API/ABI breaks are done so people do not have a treadmill of breaking changes to compensate for as we move towards the 2.0 stable release.

The largest changes are complete at this point and the benefits of the breaking changes have been realised.  There's been a drastic improvement in performance and memory usage across the board, and a much simpler async/await/CancellationToken based API internally.

If you want to test things out with a pre-alpha release I can create a nuget package from master and attach it here, though if you can compile from source then that's as good an option for now!

**Comment by alanmcgovern** [comment]
Actually i just uploaded a 1.0 release with a similar fix, so you can use that too!

**Comment by borrelnoten** [comment]
Thank you very much!!! dinsdag, 24 november 2020, 01:09a.m. +01:00 van Alan McGovern  notifications@github.com :

**Comment by borrelnoten** [comment]
It works pefectly. Now I am trying to create a streamingpicker (like to one available from the streamprovider).
But is seems the MonoTorrent.Client.ITorrentFileInfo interface is not yet available in the package.

My goal is to set the piece priority by hand (for example first 10 pieces get a priority to be downloaded first).

**Comment by alanmcgovern** [comment]
There are two built-in implementations of streaming pickers with slightly different characteristics. What are you trying to accomplish which isn't supported by either of those? There's SlidingWindowPicker which does exactly what you described, then there's StreamingPicker which aims to provide a System.IO.Stream, or a simple Http endpoint, to allow media to be streamed to a player.

While `StreamingPicker` is optimised for media, it can also be used for any file which has a reasonably sequential access pattern.

That said - the 1.x release in nuget is quite different to what's available in master so if you want to build new functionality i would recommend using master builds for now while the 2.x release is being prepped. It will be released from a master based branch eventually :)

**Comment by borrelnoten** [comment]
In that case i would use the sliding window picker but i have to clue how to make that work looking at my goal to manualy set the start point of the window. For example i need to start in the middle of the file so i get the file piece offset. Then devide file length with piece size and add that to the file piece offet so that it downloads from there. How can i do that with sliding window?

**Comment by alanmcgovern** [comment]
Take a look at this implementation: https://github.com/mfkl/lvst/blob/master/LVST/Program.cs of a streaming media player.

When you call [CreateStreamAsync](https://github.com/mfkl/lvst/blob/master/LVST/Program.cs#L134) and get the stream, you can seek to any position and read the stream as if it were a FileStream. If you want to start in the middle of a file, just seek to that position and everything else (downloading the right set of pieces) is handled automatically.

Does this solve the issue for you?

**Comment by borrelnoten** [comment]
I like your suggested solution using 
var stream = await provider.CreateStreamAsync(provider.Files [0]); 
to get the file stream and next seek that file to the right position and by doing so, move the piece priority that will be downloaded in the torrent.

But what if I have done the above and 2 minutes later, I want to switch to another file and say 

var stream = await provider.CreateStreamAsync(provider.Files [1]);
and again seek to a specific byte position. Would that still work? If yes, than this is the solution.

Also, would the torrent progress per file be still available using the solution? I need to keep track of the progress per file.

The reason why I need this level of controle is that I am building an on demand video player that is downloading multiple torrent at the same time holder one or move media files inside. The user can see the playable files, click one and play it while it is still downloading. Also, the user is able to seek the video while downloading.
Right now, I use an old rasterbar c# wrapper for libtorrent. The news version does not work very well and also is not yet supporting 64 architecture. Monotorrent made great steps and I really like all the hard work you have put into this project!! Great improvements so happy to use monotorrent!!

**Comment by alanmcgovern** [comment]
There's a limitation at the moment where you can only use one stream at a time. In practice this means you need to dispose the first stream before requesting the next stream. 

This has no impact on data which has already been downloaded, so if you download a file 100% and then want to swap to something else, the first file will be available on-disk and you can open it with a regular FileStream if you want access to it again later. 

One example usecase would be to download subtitle files first, then when they're fully downloaded you can begin streaming the underlying video file. 

The one-stream-at-a-time limitation is per-torrent. That means you can stream multiple torrents concurrently and have 1 special stream for each one. 

I think it'll suit your usecase perfectly :) if you have any issues do let me know!

**Comment by borrelnoten** [comment]
I will try it! Last question, in the streamprovider solution, you are not using the manager. Does that mean the manager is not allowed combined with the streamingprovider? Case somethimes is that torrents hold archived files and not media type files. Would the streaming provider still work? I would use it like this:

1: create engine
2: setup dht with udp
3: build the torrent object (either from torrent file or from magnet uri)
4: focus on downloading the biggest file in the torrent first
**5: if it is a media file, get the media duration using ffmpeg. If it is not a media file, just download everything until completed.**
6: once a duration is known, the user is allowed to play the file and seek.
7: if the torrent has multiple media files, the user can play another file (disposing the currently used steream first as you've mentioned and build a new streamprovider for the other file inside the torrent).

Not sure about point 5, will this setup download the files without a manager and just using the streamprovider is enough to get it going?

**Comment by borrelnoten** [comment]
I've build the above. Seems to be working very well!! Tank you for the great and very fast support!!
