### ISSUE TITLE
NuGet package of 25th nov 2020: await torrentStreamProvider.CreateStreamAsync seems to hang forever.

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#343]
I'm using the NuGet package of 25th of nov 2020
The below command seems to hang for ever when called:

tsProviderStream = await torrentStreamProvider.CreateStreamAsync(torrentStreamProvider.Files[biggestFileIndexNr]);

before I run that line, I init the engine and streamProvider for a torrent:

engine = new ClientEngine(engineSettings);

DhtEngine dht = new DhtEngine(new IPEndPoint(IPAddress.Any, dhtPort));
await engine.RegisterDhtAsync(dht);

await engine.EnablePortForwardingAsync(CancellationToken.None);

torrentStreamProvider = new StreamProvider(engine, GetDownloaderData().FullDownloaderPath, torrent);
await torrentStreamProvider.StartAsync();

// hang on this command:
tsProviderStream = await torrentStreamProvider.CreateStreamAsync(torrentStreamProvider.Files[biggestFileIndexNr]);

**Comment by borrelnoten** [comment]
I've now treid the master brench, compiled it but same issue.

The line where the program waits forever is

**if (prebuffer) {**

Weird right!? Just after "var tcs = CancellationTokenSource.CreateLinkedTokenSource (Cancellation.Token, token);" it hangs on the next line (simple if statement seems no reason to just hang there).

Below I've copied the streamProvider class function called "**CreateStreamAsync**":

`
            Picker.SeekToPosition (file, 0);
            ActiveStream = new LocalStream (Manager, file, Picker);

            var tcs = CancellationTokenSource.CreateLinkedTokenSource (Cancellation.Token, token);
            if (prebuffer) {
                ActiveStream.Seek (ActiveStream.Length - 2, SeekOrigin.Begin);
                await ActiveStream.ReadAsync (new byte[1], 0, 1, tcs.Token);

                ActiveStream.Seek (0, SeekOrigin.Begin);
                await ActiveStream.ReadAsync (new byte[1], 0, 1, tcs.Token);
            }
            return ActiveStream;
        }
`

**Comment by borrelnoten** [comment]
Update: I've now treid to skip the prebuffer by setting it to false in the call:

torrentStream = await torrentStreamProvider.CreateStreamAsync(torrentStreamProvider.Files[findex], false, new CancellationToken());

That seems to work. Still I would like to use the prebuffer if possible.

**Comment by alanmcgovern** [comment]
Does the issue happen with master builds?

I have a vague recollection of fixing one or two off-by-one issues in the streaming picker within the last few months and they could be master only. If you can confirm master is ok then I can backport the revenant 2-3 commits relatively easily (hopefully!)

Otherwise could you share a sample torrent I can use to reproduce the problem locally?

**Comment by alanmcgovern** [comment]
(pre buffering downloads the first and last piece, so if this is what's failing then it's nearly definitely the off-by-one issue)

**Comment by alanmcgovern** [comment]
There off-by-one fixes in this patch are likely to be the ones you need in a 1.x release! https://github.com/alanmcgovern/monotorrent/commit/777926f0dae8bd617d90112ce95acb762545580a

**Comment by borrelnoten** [comment]
I've compiled the master builds but same issue.
Torrent I test with:

https://archive.org/download/TheGoodGoodGiver/TheGoodGoodGiver_archive.torrent

**Comment by alanmcgovern** [comment]
I'm just testing with this torrent in case there's an off-by-one error i've missed. my usual set of torrents i use for manual testing are working as expected :(

I wonder if part of the problem is that there aren't many seeds for this particular torrent and the Streaming piece picking mode is interacting badly with webseeds.

**Comment by borrelnoten** [comment]
if the buffer means: wait until we have some peers and fill the buffer, in that case, yes, it will take some time before the command will return. In that case I would suggest to take care of the buffer in an async manner to ensure the main thread to continue. If that makes sense, not sure :)

var tcs = CancellationTokenSource.CreateLinkedTokenSource (Cancellation.Token, token);
        if (prebuffer) {
            ActiveStream.Seek (ActiveStream.Length - 2, SeekOrigin.Begin);


Placing the breakpoint on the var tcs and next, step to next line, and then step to next line. That last steps brings the hang so that would mean it hangs on:

            ActiveStream.Seek (ActiveStream.Length - 2, SeekOrigin.Begin);

Maybe this would be a fix?
new Thread(() => 
{
            ActiveStream.Seek (ActiveStream.Length - 2, SeekOrigin.Begin);
            await ActiveStream.ReadAsync (new byte[1], 0, 1, tcs.Token);

            ActiveStream.Seek (0, SeekOrigin.Begin);
            await ActiveStream.ReadAsync (new byte[1], 0, 1, tcs.Token);
}).Start();

**Comment by alanmcgovern** [comment]
Prebuffering is to allow the monotorrent to download the first and last piece of the file before passing it to your media player. It's a small optimisation as some media formats need the last block before they can be played. This provides a slightly better UX as you can display a spinner in your app until prebuffering completes.

However, if you want to disable prebuffering, just pass `false` for the `prebuffer` parameter: https://github.com/alanmcgovern/monotorrent/blob/f875ae639c3e9c8872839895409788c00982f30a/src/MonoTorrent/MonoTorrent.Streaming/StreamProvider.cs#L233 . This shouldn't have any impact on actual performance as the data still needs to be downloaded anyway.

**Comment by borrelnoten** [comment]
clear. Using the prebuffer = false.
