### ISSUE TITLE
FlushAsync does not seem to actualy write bytes to the file

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#345]
After hash is received and was succesfull, I execute the flush command to make sure the data is actually written to the file:

                        engine.DiskManager.FlushAsync(e.TorrentManager.Torrent).Wait();

but after this command is done, still no bytes are in the file. Not even when all the pieced were received.
Only after I kill the engine, the data is written to the files.

**Comment by borrelnoten** [comment]
Update: i use flush with the streamprovider. I have now noticed seeking a file inside the torrent does flush bytes. So Now i have taken out the manual flush command. Playback of movies works good. For downloading zip files using the streamprovider only writes bytes when the torrent is completly downloaded and engine is disposed.

**Comment by alanmcgovern** [comment]
Taking a look now. This seems odd!

**Comment by alanmcgovern** [comment]
@borrelnoten Does the linked patch help solve the issue you were seeing?

**Comment by alanmcgovern** [comment]
I'm not entirely sure what the issue is. 

I think part of the problem could be that doing blocking waits while manually flushing can starve the threadpool. It's not likely to be the issue you're facing here, but it's something which could happen in future. 

I'd recommend using "await" instead of calling .Wait() to avoid thread starvation.

**Comment by borrelnoten** [comment]
Will test when releaed in nuGet package.

**Comment by alanmcgovern** [comment]
I've prepped the nuget packaging versioning code to create an alpha/unstable nuget package which can be uploaded to nuget.org.

I'll prep one, containing this patch, within the next few days!

**Comment by alanmcgovern** [comment]
@borrelnoten There's a preview package on nuget.org now. This build has some API breaking changes, and will continue to gain new API breaking changes over the next few weeks. As such I wouldn't ship a stable product on it *yet*, but do give it a test if you'd like to test it out while it's in the preview cycle! https://www.nuget.org/packages/MonoTorrent/2.0.0-alpha.unstable.build1
