### ISSUE TITLE
the download does not start

### ISSUE THREAD

**Issue by Spec-Nox** [alanmcgovern/monotorrent#351]
hi, i'm trying to download files using monotorrent ... but the download doesn't start and i don't get any errors. what's wrong?
![Screenshot (30)](https://user-images.githubusercontent.com/58957863/101555401-e5606e80-39b8-11eb-82f8-ba66a3cca550.png)

**Comment by alanmcgovern** [comment]
I'd recommend modifying your code so you `await` each asynchronous method. You're probably triggering an usual error by not awaiting them, and you're not seeing the exception because you're not awaiting the Task.

**Comment by Spec-Nox** [comment]
> I'd recommend modifying your code so you `await` each asynchronous method. You're probably triggering an usual error by not awaiting them, and you're not seeing the exception because you're not awaiting the Task.

thank you, now it seems to work perfectly ... in case of new problems or various questions can I get bothered again? :)

**Comment by alanmcgovern** [comment]
Great!

Do file any further issues here and we can dig into them!
