### ISSUE TITLE
udp protocol

### ISSUE THREAD

**Issue by tatanene** [alanmcgovern/monotorrent#354]
hi, i am new to programming and i would like to create a client able to download from torrent files, but i noticed that monotorrent uses the tcp protocol which seems quite slow, i know it is possible to implement udp protocol but i have little experience and i could not this.
I was wondering if it was possible to have an example with the udp protocol.
thanks

**Comment by alanmcgovern** [comment]
Hi!

TCP is definitely not slow in and of itself. uTP will help in some proportion of cases, but I'm not aware of benchmarks which show it to be a clear winner in a meaningful real-world way.

However, if you're curious about implementing uTP you could fork MonoTorrent, implement a `class UdpConnection : IConnection`, and implement https://www.bittorrent.org/beps/bep_0029.html in this subclass.

If you want an example of some implementations which use uTP you can check any of the opensource projects here: https://en.wikipedia.org/wiki/Micro_Transport_Protocol .

I'd definitely be +1 to implementing support for this, though it's a low priority item as the benefits are not clear cut.

**Comment by alanmcgovern** [comment]
I'll close this for now as I don't intend to work on this in the short term.
