### ISSUE TITLE
Per Torrent Max Speed

### ISSUE THREAD

**Issue by Lanpingner** [alanmcgovern/monotorrent#358]
Hi everyone,
I am recently started to make a torrent program with this library, its pretty cool:)
How can i limit the **download speed per torrent,**
I am asking here since i didn't found any forum or documentation about it .
If there is a forum exist about this i would really appreciate the link.
Thanks for any help

**Comment by Deathspike** [comment]
When creating a `TorrentManager`, you can pass in a `TorrentSettings`.
In `TorrentSettings`, you'll find `MaximumDownloadSpeed`.

**Comment by Lanpingner** [comment]
TorrentSettings torrentDefaults = new TorrentSettings();
            torrentDefaults.MaximumDownloadSpeed = Value;

The problem is that MaximumDownloadSpeed is read only.
Another qs apart from that can i change these settings while torrent is downloading?

**Comment by Deathspike** [comment]
Ah, in 2.0 you use a TorrentSettingBuilder, set is there, and then call ToSettings. To update settings of a running torrent, use UpdateSettingsAsync with the same approach.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Lanpingner** [comment]
```
TorrentSettingsBuilder torrentSettings = new TorrentSettingsBuilder {
                MaximumDownloadSpeed = 0,
                MaximumUploadSpeed = 0,
            }.ToSettings ();
```
I did this but i am getting this error 
Cannot implicitly convert type 'MonoTorrent.Client.TorrentSettings' to 'MonoTorrent.Client.TorrentSettingsBuilder'

**Comment by alanmcgovern** [comment]
TorrentSettingsBuilder torrentSettings = new TorrentSettingsBuilder {
                MaximumDownloadSpeed = 0,
                MaximumUploadSpeed = 0,
            };

Or

TorrentSettings torrentSettings = new TorrentSettingsBuilder {
                MaximumDownloadSpeed = 0,
                MaximumUploadSpeed = 0,
            }.ToSettings ();

**Comment by alanmcgovern** [comment]
(I'm on mobile so apologies for the terse response! Thanks for contributing the answer (s) @Deathspike !

**Comment by Lanpingner** [comment]
Thanks for the help,I was so dump.
Thanks for all of you

**Comment by alanmcgovern** [comment]
No problem! Better documentation would have helped here too :)
