### ISSUE TITLE
[Bug] Memory cache prevents torrent 100% complete on-disk

### ISSUE THREAD

**Issue by Deathspike** [alanmcgovern/monotorrent#360]
I'm using MonoTorrent `2.0-rev0017`. When I download a torrent, and it goes into `TorrentState.Seeding`, the disk cache isn't flushed. So whenever I restart my application, and `monotorrent` hashes the existing file, the last downloaded piece will fail and will be re-downloaded. The file on-disk is never 100% complete.

I fixed this with:
```
_manager.TorrentStateChanged += (o, e) =>
{
    Console.WriteLine($"OldState: {e.OldState} NewState: {e.NewState}");
    if (e.NewState == TorrentState.Seeding) _ = _manager.Engine.DiskManager.FlushAsync(_manager);
};
```

But the disk manager should flush whenever the torrent is complete automatically, without being explicitly told.

**Comment by alanmcgovern** [comment]
I'm going to disable the memory cache for now and test a few more scenarios. There are issues with it which need to be flushed out :)

For now please turn it off by setting `EngineSettings.DiskCache` to zero if it's blocking your progress. Otherwise these bug reports are super useful!

**Comment by Deathspike** [comment]
It's not a problem. Please don't turn the new feature(s) off in an alpha
If I wanted perfect stability, I'd use the 1.0 branch.
I'm using the alpha to help test :-)

I'll use my flush-mechanism until you've got this tackled at some point in the future.
Works for now haha

**Comment by alanmcgovern** [comment]
This aspect should be fixed in master now! The engine will flush before emitting the state change event.

**Comment by Deathspike** [comment]
Works great 👍

**Comment by alanmcgovern** [comment]
Great! Thanks for checking!
