### ISSUE TITLE
PieceManager BlockRequested and BlockRequestCancelled never raised

### ISSUE THREAD

**Issue by Deathspike** [alanmcgovern/monotorrent#363]
I'm using MonoTorrent `2.0-rev0017`.
The events `BlockRequested` and `BlockRequestCancelled` are never raised.
Both are in a region called "Old". Perhaps you intended to delete them?
Is there an alternative to be notified of requests and cancelled requests?

**Comment by alanmcgovern** [comment]
Yes - i think those were supposed to have been removed but were left behind accidentally.

One of the issues with that particular API is that it's allocation heavy and also a bit complex to use as, for example, `BlockRequested` is typically emitted around 3,200 times per second if you're downloading at only 50MB/sec. The event is invoked on the threadpool, so it's 1 thread swap to emit each event, and (presumably) another one in a GUI application so you can update the API.

If you add in BlockReceived and BlockCancelled events, and download at 100MB/sec it's over 12,000 events a second.

Would an API which returned a cloned/immutable copy of all pieces, and blocks within those pieces, which are being actively downloaded help you?

https://github.com/alanmcgovern/monotorrent/pull/365

This is work-in-progress is not actually thread safe in that the `Block` objects you access inside the Piece are not immutable or clones. They are the actual objects the engine is using internally and so the values stored inside them will change at any moment.

If this API is a useful way to get what you need, then i can make it immutable. If you think the 12,000+ events a second is reasonable for your usecase, i'd love to know what the usecase is so i can see if it can be supported with less overhead. :)

**Comment by Deathspike** [comment]
I don't need it. I was looking at BlockRequested and related events to do some handling in a custom picker, but since some weren't raised, I couldn't use it. I'm working closer with the StandardPicker and I think I can get it to do what I'm aiming for. It's just that the events are confusing, if they don't work, they shouldn't be there. My preference would be for them to be deleted altogether then.

**Comment by alanmcgovern** [comment]
Oh, gotcha!

These events would've (should've?) been *outputs* based on what the piece picker has actually done. It's the picker's responsibility to generate, and cancel, requests. However removing them seems like the right thing to do so let me review that part of the code again and see what cleanups are necessary! Thanks!

**Comment by alanmcgovern** [comment]
I just removed them.

It's easier all round to use an 'Export' based approach.

* Data will always be 'stale' in comparison to what's in the engine if a torrent is downloading
* The events are async and so can be delivered out of order. Technically, depending on thread scheduling, you could get a 'cancelled' event before you get the 'requested' event.
* It's *probably* easier for everyone if they don't have to maintain an accurate list all requests, in a threadsafe way, using the events.

**Comment by alanmcgovern** [comment]
Do let me know if you have any other questions/problems!

Thanks
