### ISSUE TITLE
[Feature Request] Require Encryption

### ISSUE THREAD

**Issue by Deathspike** [alanmcgovern/monotorrent#366]
I would like to see the following feature in `2.0`:

```
new ClientEngine(new EngineSettingsBuilder
{
    RequireEncryption = true
}.ToSettings());
```

This should behave like other torrent clients do. Don't connect to a peer that doesn't support encryption.
The added value is that we can be sure that nobody can see the transfer except the receiving peer.
Other torrent clients often offer the following options:

- No Encryption
- Prefer Encryption
- Require Encrytion

So perhaps it would be nice to deprecate `PreferEncryption` in favor of an enum:

```
new ClientEngine(new EngineSettingsBuilder
{
    EncryptionStyle = EncryptionStyle.Require
}.ToSettings());

enum EncryptionStyle {
  None,
  Prefer,
  Require
}
```

What do you think?

**Comment by alanmcgovern** [comment]
Ah, this is already supported! The Xml docs for `PreferEncryption` should call out this exact scenario!

`PreferEncryption` is what determines which kind of connection should be attempted *if* a choice must be made.

`AllowedEncryption` is where you can specify the supported connection types. The default is `EncryptionTypes.All`. I should make it an error to set `EncryptionTypes.None`. This is used by the engine to disable connection attempts for a given peer (for potentially a variety of reasons).

What you want is to set it to `EncryptionTypes.RC4Full | EncryptionTypes.RC4Header` so only encrypted connections will be supported. Let me know if you have any issues with this. Note: There's no way to set a priority between RC4Full or RC4Header at the moment. Perhaps the right thing to do would be to take a list of supported types and then use the order of the elements as the priority.

For example, you could do:
``` 
new EngineSettingsBuilder {
    AllowedEncryption =  new [] {
        EncryptionTypes.RC4Header,
        EncryptionTypes.RC4Full,
        EncryptionTypes.PlainText
    }
}
```
And this has an explicit priority - Header-only is the desired, and PlainText is least desired (but still important).

Would this alternative approach to specifying preference be better than the combo of `AllowedEncryption` and `PreferEncryption`?

**Comment by Deathspike** [comment]
Oh! This wasn't clear to me. I'm now using this as per your suggestion:

```
new ClientEngine(new EngineSettingsBuilder
{
    AllowedEncryption = EncryptionTypes.RC4Full | EncryptionTypes.RC4Header,
    PreferEncryption = true
}.ToSettings()
```

I think that dropping `PreferEncryption` would be better since `AllowedEncryption` already includes `PlainText`.

Your suggestion for `AllowedEncryption` with an order would be ideal for me! I really like that one. :-)

**Comment by alanmcgovern** [comment]
WIP branch: https://github.com/alanmcgovern/monotorrent/tree/prioritised-encryption-types

**Comment by alanmcgovern** [comment]
Final PR https://github.com/alanmcgovern/monotorrent/pull/369

**Comment by alanmcgovern** [comment]
Merged!

**Comment by Deathspike** [comment]
Thanks! Looks good to me!
