### ISSUE TITLE
[Feature Request] Support for incomplete files

### ISSUE THREAD

**Issue by Deathspike** [alanmcgovern/monotorrent#367]
I'd like to request support for incomplete files:

```
new ClientEngine(new EngineSettingsBuilder
{
    UseIncompleteStrategy = true
}.ToSettings();
```

This should be the behavior when running:

1. The first piece of the incomplete file will be flushed with 'incomplete' extension, e.g. `myfile.mkv.!mt`.
2. Each piece will flush through the disk manager to the incomplete file.
3. The last piece, completing the file, will rename the file to remove 'incomplete' extension. Now you have `myfile.mkv`.

And this opens an interesting option when (re)loading a torrent:

1. When checking existing files, look for both `$filename` and `$filename.!mt`.
2. If file with incomplete extension exists, hash it and continue business as usual.
3. If file without incomplete extension exists, assume it's correct and skip hashing.

This gives two benefits, in my opinion.

1. It's obvious when a file isn't done yet just by looking at the file.
2. Massive performance benefit when reloading torrents to seed files.
3. Allows to build massive torrent library of thousands torrents w/o startup problems.

What do you think? :-)

**Comment by alanmcgovern** [comment]
I'm definitely not averse to the idea of using `.incomplete` (or equivalent) for incomplete files. The proposal makes sense and with the new EngineSettingsBuilder approach it makes it very easy to enable/disable this on the fly.

- What should happen to pre-existing torrents when this goes from `false -> true`, or `true -> false`. Should all partial files be renamed?

For the second part - I'd rather not *assume* that files with the same name are actually the correct file. The library is currently 'safe' in that it will never accidentally send incorrect data. There are some easy things you can do on your side if you want to avoid hash checking though!

1. If you have hash checked a torrent+files at least once, you can call `TorrentManager.SaveFastResume` and `TorrentManager.LoadFastResume`. As long as you load the prior fast resume data then the you can skip the hash check when starting a torrent the next time your application is restarted. (I wonder if this could be made easier to use?)
2. If you don't have fast resume data, just create one and pretend everything has been fully hashed. `FastResume` data is a suggestion - If the data says everything is fully hashed, MonoTorrent will still double check all files exist on disk, and if anything is missing (or if the file is the wrong size?) a full hash check will be performed. If MonoTorrent natively supported the `.incomplete` approach you could use this approach safely. If you tried this today then incomplete files would be indistinguishable from the actual complete files and you'd end up sharing junk data.

However, if MonoTorrent supported .incomplete files would you be OK with the idea of faking your own FastResume data? Or, ideally, storing fast resume data alongside the `.torrent` such that every torrent would be hash checked at least once and you reduce the risk of invalid data?

**Comment by Deathspike** [comment]
Yeah, it makes sense to me that files are renamed from when the setting changes. We'd have to be sure that the files *can* be renamed, though. I can imagine that a different process locks the file in a way that makes it impossible to rename it, like when another stream is opened on the file as read-only. I don't think you can rename if that's the case. Perhaps it's possible to try it when changing the setting, and fail gracefully when the files are in use?

I didn't actually consider the second part. Assuming the file is valid is indeed a recipe for disaster. I didn't know about `SaveFastResume` and `LoadFastResume`. That's actually perfect. No need to 'fake' my way out of it, either. I do like the idea that a torrent should have at least one full validation, so storing the resume data works great for me. I'll tinker with this in a little while, so we can forget about this for the request I think.

**Comment by alanmcgovern** [comment]
https://github.com/alanmcgovern/monotorrent/tree/partial-files

I've just begun looking into implementing this. I'm trying to figure out the best way of handling the two file paths (complete and incomplete) so the odds of 'data loss' due to files being unexpectedly named are minimised.

I think the most robust option is to allow the engine to always look for two files:
- `ITorrentFileInfo.FullPath`
- `ITorrentFileInfo.FullPath + ".!mt"`

If the engine deems the file to be incomplete, it will rename the file to be `.!mt`. If a file has the suffix and is 100% downloaded, the suffix will be removed.

If a torrent is loaded and the setting to support '.!mt' files is off, then the engine will still look for files with the suffix and will immediately rename them to *not* have the suffix if any are discovered.

Or something like that ;)

**Comment by alanmcgovern** [comment]
This has been merged!
