### ISSUE TITLE
magnet increase download speed by adding 200 url trackers or will this just clutter the engine?

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#372]
I have 200 tracker url's that I add to the magnet url and I hope that it will increase my download speed.
Questions is, will adding so many random trackers actualy help or will it block the system because they are too many?

**Comment by alanmcgovern** [comment]
It probably won't be hugely helpful to have that many. I'm not entirely sure how well the engine would cope with that many trackers. I might need to add some rate limiting to the tracker manager to ensure it doesn't contact too many TrackerTiers concurrently.

I'd recommend relying on DHT and also only add trackers which you think will be functional. Even if MonoTorrent has excellent support for torrents with hundreds of trackers (which it *probably* doesn't at the moment) it's quite likely that other torrent clients could act a little weirdly with that kind of torrent.

**Comment by borrelnoten** [comment]
tnx! Will filter out unused trackers.

**Comment by alanmcgovern** [comment]
One thing worth keeping in mind - if a torrent has 200 tracker tiers, each with 1 tracker, then it makes it much harder for two peers to discover each other. 

Imagine starting two clients at the same time and they contact peers in a spec compliant randomised order. 

The worst case scenario is that they'll each announce to 100 trackers before they finally announce to the same tracker. Not ideal! :)
