### ISSUE TITLE
streamProvider : seeking does not put focus onto the needed piece it seems

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#375]
version 37

when using the streamProvider I tested that when I seek to 3544779710 for example (total file size: 3544780933), it does not actualy move the focus onto that piece. Eithe rI am not seeking correctly or the focus is not shifted to the wanted piece.

I seek like this:

            if (torrentStream != null)
            {
                torrentStream.Dispose();
            }

            if (torrentStreamProvider != null)
            {
                torrentStream = await torrentStreamProvider.CreateStreamAsync(torrentStreamProvider.Files[findex], false, new CancellationToken());
            }

torrentStream.Seek(offset, SeekOrigin.Begin);

**Comment by alanmcgovern** [comment]
What exactly is the issue you're seeing? When you seek - what makes you think focus is not shifting?

**Comment by borrelnoten** [comment]
I see it is not downloading the bytes at the seeked position because I am not receiving the "piece received" event for that piece that holds the bytes for that byte position in the file.

**Comment by alanmcgovern** [comment]
It looks like it should, at least, be approximately correct.

You could look at `TorrentManager.Files[$index].BitField` as a way to see which pieces are available. It might be a good cross-check.

When you say you're not receiving the event for the piece you want to download, what pieces are you receiving events for and how long are you waiting?

Also, if you're not on rev37 then please try that first.

**Comment by borrelnoten** [comment]
I use rev 37.  The event trigger I use to check the piece is "PieceHashed" ( torrentStreamProvider.Manager.PieceHashed += ...)

**Comment by borrelnoten** [comment]
done some move testing. The seek does move to the correct piece number. Also the calcs seem to match ok. Makes me wonder why some seek requests simply take 3 minutes while at 2 mb/s download speed. Test results:

Summary:
moving cursor to 925794174. Received piece start bytes 935329792 = piece 446 as first after seek. should be 441.
2(441) : 924843903 -> 926941054 : received after few more seconds after seek.

piece length = 2097152
start piece = 0
end piece = 1560
total length = 3271670286


RARBG.txt Idle 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
0(0) : 0 -> 30
1(0) : 0 -> 99
2(0) : 0 -> 2097022
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
2(1) : 2097023 -> 4194174
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
moving cursor...652a2429-933b-459b-8150-2a749292b189 to 925794174
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
2(2) : 4194175 -> 6291326
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
2(3) : 6291327 -> 8388478
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
2(4) : 8388479 -> 10485630
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
2(5) : 10485631 -> 12582782
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
Unsupported standard style: WS
RARBG.txt Completed 1% done =  False isMedia = False 0% done
RARBG_DO_NOT_MIRROR.exe Completed 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.mkv Downloading 1% done =  False isMedia = True 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb.nfo Idle 1% done =  False isMedia = False 0% done
the.mandalorian.s02e08.1080p.web.h264-dryb_tvm.jpg Idle 1% done =  False isMedia = False 0% done
2(446) : 935329663 -> 937426814
2(445) : 933232511 -> 935329662

Piece 441 followed next which is exactly the right one as requested.

**Comment by alanmcgovern** [comment]
Can you share a testcase which I can compile and run? It might help me figure out what's going on. At the moment I'm just taking shots in the dark to try and figure out what's going on :)

**Comment by Deathspike** [comment]
> done some move testing. The seek does move to the correct piece number. Also the calcs seem to match ok. Makes me wonder why some seek requests simply take 3 minutes while at 2 mb/s download speed. Test results:

The stream picker prioritizes the required pieces and focuses on those first, but if a slow peer happens to get assigned to the piece, it can take a while before the piece is completed. It fluctuates enormously depending on the quality of the assigned peer, and there's no prioritization of 'fast' peers or cancellation when a prioritized peer takes too long. This is probably why it varies so much for you?

**Comment by alanmcgovern** [comment]
Perhaps!

I've decided to give this a much more thorough review to improve some of these aspects.

https://github.com/alanmcgovern/monotorrent/tree/tweak-picking

I've added prioritisation based on who is uploading fastest. Faster peers are assigned blocks from the high priority set first.
https://github.com/alanmcgovern/monotorrent/compare/tweak-picking#diff-2e05c0dd4662ce4f95cc996d74d62d095fe2d37cbe50f89ef503d1dec49f2cf1R173-R200

There's a stricter timeout on re-requesting pieces: https://github.com/alanmcgovern/monotorrent/compare/tweak-picking#diff-44e0b6ef75278a0411e80c6ea89f5080db563f56eaab467c90bae9a0df025faeR205

If we request the same block more than once, we're a little more lenient about accepting older requests. https://github.com/alanmcgovern/monotorrent/compare/tweak-picking#diff-44e0b6ef75278a0411e80c6ea89f5080db563f56eaab467c90bae9a0df025faeR168

I'll keep tapping away at this over the next few days. I suspect the recent changes to picking weren't quite good enough and made the streaming situation a bit worse. These need to be refactored/tested thoroughly before landing them, though if you're comfortable testing pre-release code please do compile the branch and let me know if it works better, or worse, for you.

**Comment by alanmcgovern** [comment]
@borrelnoten there's an issue with the latest release where the same blocks could be requested multiple times when a piece is considered "abandoned". This is the desired behaviour when in endgame mode (downloading the last few pieces) but was unintentionally activating during normal downloading due to the recent tweaks in how pieces are assigned. 

The simplest thing for now is to go back a few revisions in the alpha releases to avoid the issue. A future alpha release will contain further tweaks to ensure this doesn't happen, and lay a simpler foundation for future piecepicking changes

**Comment by alanmcgovern** [comment]
I believe this is fixed in master now, but i haven't released a new update.

I'll close this for now! Thanks for reporting this!
