### ISSUE TITLE
Change DiskManager.ReadAsync to public-facing API

### ISSUE THREAD

**Issue by Deathspike** [alanmcgovern/monotorrent#376]
I'm working on a custom picker and streaming implementation, and I want to use DiskManager.ReadAsync. Everything works perfectly fine when I change the internal method to a public one, and I don't see a reason why it should be internal. Can you make this a public API for use?

**Comment by alanmcgovern** [comment]
This should be accomplishable using the `IStreamingPieceRequester` API.

You can implement this interface and then create a `Stream` object for individual files. This will allow you to seek around and read arbitrary data. Let me know if you need anything else!
