### ISSUE TITLE
Picker no longer has CancelTimedOutRequests; responding on ticks?

### ISSUE THREAD

**Issue by Deathspike** [alanmcgovern/monotorrent#377]
In 6acce74e48c32ee22a16cb1d448e8084eca9547b, `CancelTimedOutRequests` was removed.
As far as I can see, there's no way for a picker to receive a `Tick` anymore.
What is now the appropriate way to do active checks in a picker?

**Comment by alanmcgovern** [comment]
Out of curiosity, what kind of logic do you want to run on a timed/recurring basis?

I am debating reverting that PR as I think there is a place for it still, though perhaps in a slightly different form.

**Comment by Deathspike** [comment]
I have a custom picker to stream files due to different requirements than the built-in one. The picker tracks priorities of individual pieces and their expiration times (e.g. priority become higher and the assigned peer is too slow). In `CancelTimedOutRequests`, I could find a high-quality peer assigned to a low-priority piece, and re-assign it to the high-priority piece. That call on `Tick` gave me a good place to do logic without having to worry about threading. I could do the same by using a monitor task, but then I need to manage threaded access and that's a huge hassle, especially since monotorrent is already well optimized for this.

Oh, I don't mind if it's not called every tick. It just needs to be called regularly (like a few times a second) and be on the correct thread.

**Comment by alanmcgovern** [comment]
https://github.com/alanmcgovern/monotorrent/tree/refactoring-picking

I think if I inplement this well I'll be able to delete the old endgame mode and handle everything with StandardPicker as it'll expose the primitives needed for any kind of picking. 

As you're implementing a custom picker, how do the changes to IPiecePicker look to you? It adds an explicit "Tick" method for time based changes and (hopefully) makes it much clearer how each method should be used.

**Comment by Deathspike** [comment]
At first glance, this looks pretty good. 
I didn't implement it yet, though.
The main concern I have is this one:

`IList<PieceRequest> CancelRequests (IPieceRequester peer, int startIndex, int endIndex);`

I don't understand this. What calls this? As far as I understand, the StandardPicker does call this internally when necessary, but it's never called from the outside. If that assumption is true, then there is no point to having that method in the interface -- because nothing from outside calls it. Having it on the StandardPicker makes sense because derived types can use it, but it doesn't make sense on the interface.

**Comment by alanmcgovern** [comment]
Well spotted!

There are two fairly distinct usecases for an IPiecePicker implementation. The first is to filter the Bitfield/startIndex/endIndex to determine the correct subset of pieces. Examples: RandomisedPicker, IgnoringPicker, PriorityPicker.

The second is to actually create Piece request objects, track when a request has been successfully fulfilled, reissue requests for timeouts, handle cancellation/rejection etc. 

Perhaps it's worth trying to split these concerns. 

I could imagine StandardPicker supporting several primitives:
1) request a piece using a single peer
2) request a piece using multiple peers
3) send 1, or more, requests for a single block

With those primitives it'd be fairly easy to build a "normal" picker, a streaming picker, and an "end game" picker as they would be different combinations of those three basic actions. Are there other basic actions?

The IPiecePickingFilter interface would allow filtering of the Bitfield/startIndex/endIndex before passing it to StandardPicker (or IPiecePicker)

**Comment by Deathspike** [comment]
There's just one more change that I'd like to see, but other than that, I would be perfectly fine with one `IPiecePicker` without splitting the concerns. I think it's more simple to keep it in one interface, and have other pickers layering on top simply be delegates when applicable. It will prevent having to really understand the various responsibilities and implementing multiple interfaces.

The one change, or rather the one addition, I'd like to see, is enabling a call to queue requests for *other* peers. Right now, when `PickPiece` is called and you return a bundle of `PieceRequest`, they are enqueued on the message queue of the peer for which the method was called. If there's a situation where I would want to delegate work to other peers, I'd have to wait for a call for that peer. For example, when you have a super-high priority for a piece and want to delegate the work to a whole bunch of (good) peers to get blocks from each of them.

This should also be possible in the `Tick` method. It could be designed to return an enumerable of `PeerPieceRequest`, which is just a `PieceRequest` with an addition of `peer`. A picker could then decide to cancel something during the Tick, and immediately redistribute blocks to other higher-quality peers without having to wait for the appropriate `PickPiece` calls. It would make it much more manageable to implement an intelligent cancel-and-redistribute without having to wait for that second call.

Even if it's not possible to do this in `PickPiece`. it would be superb if you could do this at least in `Tick`.

**Comment by alanmcgovern** [comment]
Hello hello!

This should all be supported after the most refactorings. I believe you'll be able to implement everything you want using an `IPieceRequester` implementation rather than an `IPiecePicker`.

I'll need to improve the documentation and samples to show how a custom picker/requester can be correctly/safely implemented. I'd recommend copying/pasting the `Initialise` method from `StandardPieceRequester.cs` as an example of how to create the right set of IPiecePickers to have a functional piece picking setup.

The tl;dr is that the built in `StandardPicker` allows you to selectively download any range of pieces (any method which requests the first block from a *new* piece has a start/end range). And for any piece which has already been started, you can choose to allow a single peer to download all the pieces (`ContinueExistingRequest`), allow multiple peers to help (`ContinueAnyExistingRequest`) or allow multiple peers to help and also allow blocks to be requested multiple times (`ContinueAnyExistingRequest(.... maxDuplicates: 2)` .

If you create your own IPieceRequester you can choose how those methods are invoked, and thus control how many times each block is requested, and who it's requested from.

**Comment by alanmcgovern** [comment]
Let me know if you have any thoughts/questions on this! I'll reopen the issue if there's any further improvements which would help!
