### ISSUE TITLE
Message=Cannot access a disposed object. : Object name: 'System.Net.Sockets.UdpClient'.

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#379]
version 37. Dispose engine resulted in the below error. This does not happend alot.

System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.
  Source=System
  StackTrace:
   at System.Net.Sockets.UdpClient.EndReceive(IAsyncResult asyncResult, IPEndPoint& remoteEP)
   at System.Net.Sockets.UdpClient.<ReceiveAsync>b__64_1(IAsyncResult ar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoTorrent.Client.Tracker.UdpTracker.<ReceiveAsync>d__17.MoveNext()

  This exception was originally thrown at this call stack:
    System.Net.Sockets.UdpClient.EndReceive(System.IAsyncResult, ref System.Net.IPEndPoint)
    System.Net.Sockets.UdpClient.ReceiveAsync.AnonymousMethod__64_1(System.IAsyncResult)
    System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(System.IAsyncResult, System.Func<System.IAsyncResult, TResult>, System.Action<System.IAsyncResult>, System.Threading.Tasks.Task<TResult>, bool)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    MonoTorrent.Client.Tracker.UdpTracker.ReceiveAsync(System.Net.Sockets.UdpClient, int, System.Threading.CancellationToken)
	

version: 4.8.4300.0 built by: NET48REL1LAST_C	
C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll

**Comment by alanmcgovern** [comment]
I think this is fine. Do you have Visual Studio set to stop whenever any exception is thrown? It looks like the engine was cancelling a pending request, so this error would be normal.

**Comment by borrelnoten** [comment]
indeed this seems standard socket behavior.

**Comment by alanmcgovern** [comment]
Great! If you have further issues do let me know!
