### ISSUE TITLE
Prohibition on distribution

### ISSUE THREAD

**Issue by ScorpionsSM** [alanmcgovern/monotorrent#389]
is it possible to prohibit distribution?

**Comment by AN3Orik** [comment]
Set `AllowInitialSeeding = false` at `TorrentSettings`

**Comment by alanmcgovern** [comment]
If you're asking if it's possible to completely disable uploading - no it isn't.

What's your usecase for this capability? Or, if that's not what you're asking, could you be a little more specific about what you mean?

**Comment by ScorpionsSM** [comment]
Disallow distribution during download

**Comment by AN3Orik** [comment]
Impossible to disable upload fully, but you can set upload speed:  `MaximumUploadSpeed` at `TorrentSettings`

**Comment by alanmcgovern** [comment]
There's no support for this at the moment. I don't think it's the kind of thing I'd spend time adding support for it in the short or medium term.

Thanks for the suggestion though!
