### ISSUE TITLE
proposal：Improve for or foreach performance，

### ISSUE THREAD

**Issue by BoyFaceGirl** [alanmcgovern/monotorrent#390]
Replacing for  with Parallel.For to improve performance.

**Comment by alanmcgovern** [comment]
It's unlikely to be of any practical benefit once thread safety is taken into account. 

Feel free to experiment and submit a patch if there's some improvements to be had!

**Comment by alanmcgovern** [comment]
I'll close this for now as I don't intend to explore this option myself :)
