### ISSUE TITLE
Write piece to disc after fully received

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#393]
Is a fully received piece written to disc emediatly? If not, how can i make that happen?

**Comment by alanmcgovern** [comment]
What problem are you trying to solve by forcing data to flush to disk?

I'm curious as the memory cache seems to be introduced an odd bug ( https://github.com/alanmcgovern/monotorrent/issues/380 ) and there's a similar request to expose some methods here ( https://github.com/alanmcgovern/monotorrent/issues/376 ) so there's a deterministic/safe way for something external to MonoTorrent to safely read data which may/may not still be stored in memory rather than on disk.

**Comment by borrelnoten** [comment]
It so to make sure the dowbloaded segment can be played from drive by vlc or ffmpeg or other consumer. dinsdag, 09 februari 2021, 10:10p.m. +01:00 van Alan McGovern  notifications@github.com :

**Comment by alanmcgovern** [comment]
The guarantee MonoTorrent will make is that all data for a given Piece will be flushed to the `IPieceWriter` after the piece has passed it's hash check, but before the engine is updated internally to reflect that. If you have not written a custom `IPieceWriter` then this means all blocks of data for a given piece will be passed to the `DiskWriter`, which will ensure they are written (and flushed) to disk.

In short, when you receive a `PieceHashed` event indicating a piece has been successfully hashed, the data associated with that piece is guaranteed to be accessible on-disk.

NOTE: If you write a custom `IPieceWriter` implementation then the guarantee you can rely on is: Every block of data for a given piece will be passed to `IPiecePicker.WriteAsync` , and then `FlushAsync` will be invoked to indicate the engine no longer needs the data internally.

Finally, `WriteAsync` has a parameter which lets the engine provide a hint as to whether caching could be beneficial. If MonoTorrent successfully incrementally hashes a block of data, it will set `preferSkipCache` to `true`. This is merely a hint to show that the engine is unlikely to try and read that block of data again.

If this parameter is set to false, the engine is likely (but not guaranteed) to call `ReadAsync` to get that data again.

Hope this helps!

Finally  - the above may not be true *right now*, but this is the set of changes I'm working through at the moment. In addition to this I intend to make some of the read/write methods publicly accessible so people using custom `IPieceWriter` implementations have a thread-safe way to read arbitrary data while taking any in-memory cache or custom `IPieceWriter` implementation into account. For example https://github.com/alanmcgovern/monotorrent/issues/376

Let me know if you have any questions about this, or if you find cases where the assertions/guarantees above are *not* true using the current master builds. I landed one chunk of this work yesterday but will need to do a final review of the tests to ensure these guarantees are validated.

**Comment by borrelnoten** [comment]
Very clear and fits my needs perfectly!
vrijdag, 12 februari 2021, 08:17p.m. +01:00 van Alan McGovern  notifications@github.com :
