### ISSUE TITLE
CreateHttpStreamAsync throws ArgumentOutOfRange on some torrents.

### ISSUE THREAD

**Issue by SICGames** [alanmcgovern/monotorrent#398]
Birds of Pray for instance is throwing this. Boss Level didn't throw it. 

> Exception Thrown By CreateHttpStreamAsync in StartStreamingTorrent:Specified argument was out of the range of valid values.
Parameter name: index [System.Collections.ListDictionaryInternal]

```
 try
                {
                    //-- creates a ArgumentOutOfRange with some torrents.
                    streamObject = await streamprovider.CreateHttpStreamAsync(tf);
                    SaveFastResume(streamprovider.Manager, AppGlobals.gFastResumePath + @"\fast_resume.dat");
                }
                catch(Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine("Exception Thrown By CreateHttpStreamAsync in StartStreamingTorrent:{0} [{1}]", ex.Message, ex.Data);
                    bCreateStreamFailed = true;

                }
                if (bCreateStreamFailed)
                {
                    return null;
                }
                return streamObject;
```

But other than that, your C# library is beautiful. Was able to watch torrents using it.  I'll take a closer look into why Birds Of Pray is failing hard. It's able to download while streamprovider started. Just won't CreateStreamSync. At first, I thought it was the name of the file. It's long. I'm not entirely sure if I could create a friendlier version of the mp4 file name within the torrent.

**Comment by SICGames** [comment]
What I've found out was that anything over 2.0 GB of media would result in this exception being tossed. I've tried Birds of Pray 720p which is 1.5GB and it's working. Maybe filesize too big?

**Comment by alanmcgovern** [comment]
Hrmm, I thought that had been fixed in stable and pre-release. 

Could you tell me which version of the nuget you have installed? Also, does the problem go away if you upgrade to the latest pre-release/stable?

**Comment by SICGames** [comment]
i'm running Monotorrent v1.0.28 from NuGet. I can certainly test out the latest pre-release. At first, I thought it was the long filename. But nope, it's definately the file size. Anything over 2 GB, pukes and throws the exception. But I'll definately see if the latest pre-release/stable works.

**Comment by SICGames** [comment]
i used the latest pre-alpha build 2.0.0 and it worked like a charm. I've seen a lot of the functionality has been very simplified. Love the EngineSettingsBuilder. Sending that to EngineSettings is easy pie. I was taken by not doing:

`clientengine.RegisterDhtAsync();`

But I reckon, it does it automatically when the developer specifies it inside the EngineSettingsBuilder? 

What was causing the issue with CreateStreamAsync that you fixed? I could be a bit delusional, but... I'm possibly downloading (streaming) much faster than I did with the stable release [1.0.28]. So, you've been improving how pieces are obtained?

**Comment by SICGames** [comment]
i'll continue to use the pre-alpha unstable version for now. So far, it's not been buggy. However, if anyone's needing some direction on the new changes. I've set up the clientengine fairly simple. 

```
    EngineSettingsBuilder engineSettingsBuilder = new EngineSettingsBuilder();
            EncryptionType[] encryptionTypes = { EncryptionType.RC4Full, EncryptionType.RC4Header };

            engineSettingsBuilder.AllowedEncryption = encryptionTypes;
            
            engineSettingsBuilder.MaximumConnections =  300;
            engineSettingsBuilder.MaximumUploadSpeed = 100 * 1024;
            engineSettingsBuilder.SavePath = AppGlobals.gDownloadPath;
            engineSettingsBuilder.DhtPort = 5555;
            engineSettingsBuilder.AllowPortForwarding = true;
            engineSettingsBuilder.AllowLocalPeerDiscovery = true;
            
            TorrentSettingsBuilder torrentSettingsBuilder = new TorrentSettingsBuilder();
            torrentSettingsBuilder.MaximumUploadSpeed = engineSettingsBuilder.MaximumUploadSpeed;
            torrentSettingsBuilder.MaximumConnections = engineSettingsBuilder.MaximumConnections;
            torrentSettingsBuilder.UploadSlots = 5;
            torrentSettingsBuilder.AllowDht = true;
            torrentSettingsBuilder.AllowPeerExchange = true;

            EngineSettings enginesettings = engineSettingsBuilder.ToSettings();
            TorrentSettings torrentsettings = torrentSettingsBuilder.ToSettings();

            clientengine = new ClientEngine(enginesettings);
            //-- create DHT
            DhtEngine dhtEngine = new DhtEngine(MonoTorrent.Dht.Listeners.DhtListenerFactory.CreateUdp(5555));
            
            //clientengine.RegisterDhtAsync(dhtEngine);
            if (System.IO.File.Exists(AppGlobals.gDHTFilepath))
            {
                clientengine.DhtEngine.StartAsync(System.IO.File.ReadAllBytes(AppGlobals.gDHTFilepath));
            }
            else
            {
                clientengine.DhtEngine.StartAsync();
            }

```

What I've noticed is that the DHTNode files aren't saved. Perhaps, I'll have to wait until a download is officially completed. The clientengine.RegisterDHTAsync() threw me off a bit. I'm not entirely sure if I'm using it correctly when I'm trying to configure DHT.

**Comment by SICGames** [comment]
![ProjectZilla-Screencapture-MovieStreaming](https://user-images.githubusercontent.com/8494886/107986375-e950d400-6f99-11eb-8e13-305ffe58be5d.JPG)

Beautiful isn't it? The orange progress bar on the very bottom of the player indicates the streamprovider.manager.progress. The video was obtained from a MagnetUrl and custom-parsed.

Keep doing a fantastic job. This C# library is amazing.

**Comment by alanmcgovern** [comment]
> But I reckon, it does it automatically when the developer specifies it inside the EngineSettingsBuilder?

Yup! If you want to disable DHT just set the DHT port to -1. The intellisense documentation *should* have the explanation for the API.

> What was causing the issue with CreateStreamAsync that you fixed?

There was a place where the code was multiplying two int32 values `pieceIndex * pieceLength` but it needed to do `(long) pieceIndex * pieceLength` to avoid overflow errors for files larger than 2gb. As it's such a trivial fix I should double check what happened with the stable release as I probably just forgot to push the change, or release it, as I do remember fixing it. Oops.

> I'm possibly downloading (streaming) much faster than I did with the stable release [1.0.28]. So, you've been improving how pieces are obtained?

Yup! This is *exactly* what the latest round of changes have been addressing. Steaming perf should be significantly better now :) 

> What I've noticed is that the DHTNode files aren't saved

Let me file a tracking issue for that. The point behind the most recent changes around `EngineSettingsBuilder` is to hide some complexities around forwarding ports and re-creating socket listeners when ports change. I should also make saving/restoring fast resume, and dht node, data easier.

**Comment by alanmcgovern** [comment]
https://github.com/alanmcgovern/monotorrent/issues/400

Do let me know how you get on with the latest preview anyway. It is API unstable (still) so the only downside is that if you update frequently you *may* have to continually tweak for API breakages. I hope to wrap those breaking changes up in the not too distant future though :)

**Comment by SICGames** [comment]
So far, I'm loving the new updates. Just a question, I had to do a work around to verify all the streamed files were downloaded completely. Because once they were done, and I closed out, copied them to another folder (leaving same files still in the download (streamed folder) on the local drive, Monotorrent would redownload them all.

 I checked the status, it says, "Downloading." So a work around that I've done was to create a CompletedTorrentFile.dat that verified what was downloaded, size of downloaded file. When I ran the CreateStreamAsync again and pulled the metadata, I compared the CompletedTorrentFile.dat with the streamprovider.Files. 

Once they were verified, they were marked as DoNotDownload. Those that weren't done, I left the Priority as Normal. I've read that you mentioned that FastResume should help? Is that only with TorrentManager and/or StreamProvider? Maybe it's my code. 

```
  public void SaveFastResume(TorrentManager manager, string fastresumepath)
        {
            // Store the fast resume for each torrent in a list,
            // then serialise the list to the disk.
            //BEncodedList list = new BEncodedList();
            FastResume data = manager.SaveFastResume();
            BEncodedDictionary fastResumeDict = data.Encode();

            System.IO.File.WriteAllBytes(fastresumepath, fastResumeDict.Encode());

        }

        public bool LoadFastResume(TorrentManager manager, string fastResumePath)
        {
            BEncodedDictionary dict = (BEncodedDictionary)BEncodedDictionary.Decode(System.IO.File.ReadAllBytes(fastResumePath));
            FastResume data = new FastResume(dict);
            if (manager.InfoHash == data.Infohash)
            {
                manager.LoadFastResume(data);
                return true;
            }
            return false;
        }
```

I found most of that code on HotScripts. It does save the FastResume file. Now should the LoadFastResume be... I think I see my problem... but... shouldn't CreateStreamAsync because it has a TorrentManager in it be okay with LoadFastResume? My question would be would I place the LoadFastResume before StreamProvider.StartAsync() or after? Or maybe after it has pulled metadata? SaveFastResume should be in what location? Before shutting down everything? Or after or during the downloading? 

Thanks again, Alan.

**Comment by alanmcgovern** [comment]
@SICGames It looks like i did backported the required patch [0] to the `monotorrent-1.0` branch in December but never actually released them. I just issued a new release in the stable series which includes the fix for files of length 2GB+.

[0] https://github.com/alanmcgovern/monotorrent/commit/c33b63fc76eae82e1a784d016beea9f692f8fcc3#diff-2e05c0dd4662ce4f95cc996d74d62d095fe2d37cbe50f89ef503d1dec49f2cf1R109-R110

That said - I'd still highly recommend using the pre-release if you're OK dealing with the API changes. It should be far superior in terms of streaming performance due to the changes to how piece picking is performed in this mode.

> Because once they were done, and I closed out, copied them to another folder (leaving same files still in the download (streamed folder) on the local drive, Monotorrent would redownload them all

This doesn't sound right. MonoTorrent should run a hash check on files which already exist on disk, unless FastResume data has been loaded for that torrent. In this scenario fastresume data *should not* be loaded, so a full hashcheck should be performed as soon as StartAsync is invoked. No actual data should be re-downloaded.

I'll double check this with the latest alpha. Maybe something went wrong with the `DiskManager.ExistsAsync` code with the recent changes around how the in memory cache is handled. Perhaps 'false' was being returned when the in memory cache was empty, instead of querying the filesystem for the existence of the file.

**Comment by SICGames** [comment]
I put the SaveFastResume function after CreateStgreamAsync. So, I think that was my bad on my part. Where should SaveFastResume function be placed?

**Comment by alanmcgovern** [comment]
>  I placed the SaveFastResume on video player close and after when the file been downloaded.

Yup, this is perfect. This ensures you have the most up-to-date representation of which pieces have been hash checked/downloaded. If you load this *before* starting the download you'll be able to skip the hashcheck. If you, for whatever reason, believe that the fast resume data may not be accurate you can call `TorrentManager.HashCheckAsync` to force a full re-scan and revalidate data.

It sounds like the original issue you faced is fixed in stable now, and also you're able to use the unstable release, so i'll close this bug report off for now. Please feel free to open new issues if you have any questions/issues! Feedback is always welcome :)
