### ISSUE TITLE
System.Net.Sockets.SocketException: 'The I/O operation has been aborted because of either a thread exit or an application request'

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#405]
in socketConnection.cs:

        public async ReusableTask ConnectAsync ()
        {
            var tcs = new ReusableTaskCompletionSource<int> ();
            SocketAsyncEventArgs args = GetSocketAsyncEventArgs (null);
            args.RemoteEndPoint = EndPoint;
            args.UserToken = tcs;

            if (!Socket.ConnectAsync (args))
                tcs.SetResult (0);

            await tcs.Task;
        }

this line:

            await tcs.Task;

gives an exception:

{"The I/O operation has been aborted because of either a thread exit or an application request"}
    Data: {System.Collections.ListDictionaryInternal}
    ErrorCode: 995
    HResult: -2147467259
    HelpLink: null
    IPForWatsonBuckets: 0x0ee1cbc9
    InnerException: null
    IsTransient: false
    Message: "The I/O operation has been aborted because of either a thread exit or an application request"
    NativeErrorCode: 995
    RemoteStackTrace: null
    SocketErrorCode: OperationAborted
    Source: "ReusableTasks"
    StackTrace: "   at System.Runtime.CompilerServices.ReusableTaskAwaiter`1.GetResult()\r\n   at MonoTorrent.Client.Connections.SocketConnection.<ConnectAsync>d__35.MoveNext() in C:\\Users\\tm\\Downloads\\monotorrent-master\\monotorrent-master\\src\\MonoTorrent\\MonoTorrent.Client.Connections\\SocketConnection.cs:line 176"
    TargetSite: {T GetResult()}
    WatsonBuckets: null
    _HResult: -2147467259
    _className: null
    _data: {System.Collections.ListDictionaryInternal}
    _dynamicMethods: null
    _exceptionMethod: null
    _exceptionMethodString: null
    _helpURL: null
    _innerException: null
    _ipForWatsonBuckets: 0x0ee1cbc9
    _message: "The I/O operation has been aborted because of either a thread exit or an application request"
    _remoteStackIndex: 0
    _remoteStackTraceString: null
    _safeSerializationManager: {System.Runtime.Serialization.SafeSerializationManager}
    _source: "ReusableTasks"
    _stackTrace: {sbyte[48]}
    _stackTraceString: null
    _watsonBuckets: null
    _xcode: -532462766
    _xptrs: 0x00000000
    m_EndPoint: null
    nativeErrorCode: 995

**Comment by alanmcgovern** [comment]
If you discovered this by running the code with the visual studio debugger attached, then this is normal and expected behaviour. The .NET framework uses exceptions for error propagation and this is one scenario where exceptions might be raised.

I'll close this as there's no indication that this is anything out of the ordinary :)

Thanks for reporting though!
