### ISSUE TITLE
Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#406]
in file udptracker.cs:

        async Task<UdpTrackerMessage> SendAndReceiveAsync (UdpTrackerMessage msg)
        {
            var cts = new CancellationTokenSource (TimeSpan.FromSeconds (RetryDelay.TotalSeconds * MaxRetries));

            try {
                // Calling the UdpClient ctor which takes a hostname, or calling the Connect method,
                // results in a synchronous DNS resolve. Ensure we're on a threadpool thread to avoid
                // blocking.
                await MainLoop.SwitchToThreadpool ();
                using var udpClient = new UdpClient (Uri.Host, Uri.Port);
                using (cts.Token.Register (() => udpClient.Dispose ())) {
                    SendAsync (udpClient, msg, cts.Token);
                    return await ReceiveAsync (udpClient, msg.TransactionId, cts.Token).ConfigureAwait (false);
                }
            } catch {
                cts.Token.ThrowIfCancellationRequested ();
                throw;
            }
        }

the line:

  return await ReceiveAsync (udpClient, msg.TransactionId, cts.Token).ConfigureAwait (false);

results in an exception:

{"Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'."}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146232798
    HelpLink: null
    IPForWatsonBuckets: 0x71f9a2f9
    InnerException: null
    IsTransient: false
    Message: "Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'."
    ObjectName: "System.Net.Sockets.Socket"
    RemoteStackTrace: null
    Source: "System"
    StackTrace: "   at System.Net.Sockets.Socket.EndReceiveFrom(IAsyncResult asyncResult, EndPoint& endPoint)\r\n   at System.Net.Sockets.UdpClient.EndReceive(IAsyncResult asyncResult, IPEndPoint& remoteEP)\r\n   at System.Net.Sockets.UdpClient.<ReceiveAsync>b__64_1(IAsyncResult ar)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at MonoTorrent.Client.Tracker.UdpTracker.<ReceiveAsync>d__17.MoveNext() in C:\\Users\\tm\\Downloads\\monotorrent-master\\monotorrent-master\\src\\MonoTorrent\\MonoTorrent.Client.Tracker\\UdpTracker.cs:line 151\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)\r\n   at MonoTorrent.Client.Tracker.UdpTracker.<SendAndReceiveAsync>d__16.MoveNext() in C:\\Users\\tm\\Downloads\\monotorrent-master\\monotorrent-master\\src\\MonoTorrent\\MonoTorrent.Client.Tracker\\UdpTracker.cs:line 140"
    TargetSite: {Int32 EndReceiveFrom(System.IAsyncResult, System.Net.EndPoint ByRef)}
    WatsonBuckets: null
    _HResult: -2146232798
    _className: null
    _data: {System.Collections.ListDictionaryInternal}
    _dynamicMethods: null
    _exceptionMethod: null
    _exceptionMethodString: null
    _helpURL: null
    _innerException: null
    _ipForWatsonBuckets: 0x71f9a2f9
    _message: "Cannot access a disposed object."
    _remoteStackIndex: 0
    _remoteStackTraceString: null
    _safeSerializationManager: {System.Runtime.Serialization.SafeSerializationManager}
    _source: "System"
    _stackTrace: {sbyte[192]}
    _stackTraceString: null
    _watsonBuckets: null
    _xcode: -532462766
    _xptrs: 0x00000000
    objectName: "System.Net.Sockets.Socket"

**Comment by alanmcgovern** [comment]
This one is normal too. 

If a response isn't received within the specified time limit the socket will be disposed. This will raise the exception you describe, and the engine should handle it and continue on. Let me know if there's any issue there!
