### ISSUE TITLE
CreateStreamAsync HttpListener Allow CORS feature request

### ISSUE THREAD

**Issue by SICGames** [alanmcgovern/monotorrent#411]
I don't mind using VLC. But I'm trying to create a HTML5 video player.  When I'm using NodeJS to access the created Http created from CreateStreamAsync, I'm getting CORS Policy rejection. 

I could fork the newest Monotorrent release, add in the HttpListener COR headers myself.  If you like them, you can put them in the future releases.

**Comment by alanmcgovern** [comment]
Sure - that sounds like a pretty reasonable request. I'm not exactly sure what you need to make this work so it would be great if you could submit a pull request with an example of what you need!

In the meantime, if you're stuck you can work around the problems with the built in HttpStream code by using `CreateStreamAsync` and then creating your own `HttpListener` (or whatever) and seek and read from the local stream to fulfill any requests you receive on your customer Http listener.

**Comment by SICGames** [comment]
Yup. right now I'm working on the HttpStream and CreateStreamAsync. I'll submit the changes to you when I'm done and test everything out.

**Comment by SICGames** [comment]
I created the changes to HttpStream and CreateHttpStreamAsync and did a pull request. I believe you should see changes.

**Comment by alanmcgovern** [comment]
I think you pushed the commit to your fork, but didn't submit a PR upstream. The change looks fine but I'll give it a double check when you submit the PR!

**Comment by alanmcgovern** [comment]
This has been merged to master now. Thanks for working this one out!

**Comment by rupisaini123** [comment]
When using CreateHttpStreamAsync the uri is created using http://127.0.0.1:5555/.
I am not sure if this has to be this way, as I am trying to stream video on HTML5, But not able to stream it.
