### ISSUE TITLE
How to reset FastResume

### ISSUE THREAD

**Issue by AN3Orik** [alanmcgovern/monotorrent#419]
Hi. After last changes with auto fastresume load/save i can't reset FastResume data like a:

`_currentTorrentManager?.LoadFastResume(new FastResume());`

How i can reset fastresume (to initialize full torrent file rehashing) now?

**Comment by AN3Orik** [comment]
Maybe add to TorrentManager ?

`        public void FlushFastResume()
        {
            UnhashedPieces.SetAll (true);
            HashChecked = false;
            var fastResumePath = Engine.Settings.GetFastResumePath (InfoHash);
            if (File.Exists (fastResumePath)) {
                File.Delete (fastResumePath);
            }
        }
`

**Comment by AN3Orik** [comment]
public void FlushFastResume()
{
	UnhashedPieces.SetAll (true);
	HashChecked = false;
	var fastResumePath = Engine.Settings.GetFastResumePath (InfoHash);
	if (File.Exists (fastResumePath)) {
		File.Delete (fastResumePath);
	}
}

**Comment by alanmcgovern** [comment]
You could call TorrentManager.HashCheckAsync to force a full re-check if a full re-check is desired (for whatever reason). 

Would this suit your needs?

Alternatively I could make the internal "SetNeedsHashCheck" method public and it could serve a similar purpose. 

Apart from that, under what circumstances would you need to invalidate fast resume data like this? I wonder if there's a better way to support your usecase. The intention is that you should not need to worry about fast resume data anymore.

**Comment by AN3Orik** [comment]
I flushing fastresume in my case for force recheck application files integrity in case when user delete some critical data - in other words make sure all application files are ok.
I'll try to use HashCheckAsync, ty for information.
