### ISSUE TITLE
Incorrect FileShare for seeding mode

### ISSUE THREAD

**Issue by AN3Orik** [alanmcgovern/monotorrent#421]
MonoTorrent in seeding mode throws "The process cannot access the file" when write access blocked by, for example, application running from this torrent files. I think problem in FileStreamBuffer.cs

```
internal async ReusableTask<RentedStream> GetOrCreateStreamAsync (ITorrentFileInfo file, FileAccess access)
```
Where we need only reading (in seeding mode) we must set FileShare.Read flag for stream to avoid access errors and FileShare.ReadWrite for writing streams when torrent in Downloading mode.

**Comment by alanmcgovern** [comment]
I think this may solve your issue: https://github.com/alanmcgovern/monotorrent/commit/faab4a6ed3a2c59219af00c048fb87ea31e64133

The files were always being opened in read/write mode. Now they're opened in read-mode when seeding.

I believe it's correct to always set 'FileShare.ReadWrite' as this affects *other* processes, and some apps (like VLC) historically fail to open files in read-only mode and so you can only open files which are being seeded if monotorrent opens the stream with `FileShare.ReadWrite`.

If this doesn't work then i could make this a configurable setting. It's one of those annoying things which is impossible to get right as it's dependent on the specific usecase and which other software is involved.

**Comment by AN3Orik** [comment]
Yeah, sorry for mistype - i mean FileAccess.Read.
Anyway, thank you for fix!
