### ISSUE TITLE
how can you fix this?

### ISSUE THREAD

**Issue by ScorpionsSM** [alanmcgovern/monotorrent#423]
how can you fix this?
3 GB file and downloads more

https://ru.files.fm/u/wugwbhxeq

**Comment by alanmcgovern** [comment]
What exactly is the issue you're facing?

**Comment by ScorpionsSM** [comment]
downloads much more than the file itself or files

**Comment by alanmcgovern** [comment]
The best thing to do would be to enable logging: https://github.com/alanmcgovern/monotorrent/blob/master/src/SampleClient/StandardDownloader.cs#L35

and then see what's going wrong. If a specific piece is being re-requested repeatedly it would be interesting to know why. Attaching to the TorrentManager.PieceHashed event would also be interesting..

**Comment by alanmcgovern** [comment]
If you can provide logs from a run where it downloaded too much data i might be able to infer what's gone wrong. Or, if you can provide a way for me to reproduce the issue I could investigate in more detail.

As it stands I don't have a way to dig into this further, so I'll close the issue off for now.

Thanks for reporting!
