### ISSUE TITLE
HashCheckAsync logic

### ISSUE THREAD

**Issue by AN3Orik** [alanmcgovern/monotorrent#426]
After update to last revision smth strange happen with HashCheckAsync logic.
Before update if i called HashCheckAsync(true) torrent engine check files and if nothing changed - engine switching to Stopped state, otherwise download all needed files and then switch to Stopped.
Now engine switch to Seeding mode and never come to Stopped

**Comment by alanmcgovern** [comment]
The old behaviour you're describing sounds like a bug, the new/current behaviour sounds correct. 

If you call HashCheckAsync(false) the engine will always enter the Stopped state when the hash check completes.

If you call HashCheckAsync(true) then the engine will always enter the Downloading/Seeding state when hash checking completes. If you initially enter the Downloading mode, the torrent *will not* automatically stop when the final piece downloads and you enter the Seeding phase. 

If anything else happens it's a bug and I should fix it!

**Comment by alanmcgovern** [comment]
I'll double check the changes in this area and see if something unintentionally changed

**Comment by AN3Orik** [comment]
So how i can implement now "old behavior" when i need just check and download missed files? Before FastResume internal changes i just delete FastResume info from manager and do StartAsync with AllowInitialSeeding = false config. 
Now i don't know how correctly do this.

**Comment by alanmcgovern** [comment]
If you used to delete fast resume data and call StartAsync then there was nothing which would cause the torrent to automatically stop when it reached the Seeding state. 

Are you sure you didn't have some special logic to make this happen?

MomoTorrent, to my knowledge, has never had a feature or bug which caused a TorrentManager to automatically Stop when it enters the Seeding state. This is an odd one.

**Comment by AN3Orik** [comment]
TorrentManager switch to Stop after hashing & downloading when set AllowInitialSeeding = false

**Comment by alanmcgovern** [comment]
That setting controls 'Initial seeding' (also known as 'super seeding') mode. It's a way of sharing pieces *slower* than you normall would, but in a way which means you are more likely to upload pieces to peers which, in turn, are sharing them with other peers in the swarm.

https://github.com/alanmcgovern/monotorrent/blob/34b33affc3a83db4b8f92bc2b4a182ccab87f24f/src/MonoTorrent/MonoTorrent.Client/Modes/StartingMode.cs#L104-L109

It is not intended to have any impact on when a torrent enters 'Stopped' mode. I'll take a look in case something odd is happening there!

**Comment by AN3Orik** [comment]
Holly molly!
Sorry for disturb you - seams it's my bug, i really using custom torrent state handling for force torrent stop after before seeding and this code smh works before latest merges with master:

```
if ((e.OldState == TorrentState.Hashing || e.OldState == TorrentState.Downloading) && e.NewState == TorrentState.Seeding)
            {
                if (_isSeedingMode)
                {
                    TorrentComplete(e);
                }
                else
                {
                    await e.TorrentManager.StopAsync();
                }
            }
```

But after last updates seams engine didn't switch directly after Hashing to Seeding (without Starting between) and broke my code. Added check for `OldState == Starting` and now all works. Ty for your time.
