### ISSUE TITLE
MonoTorrent over Tor (multiple segments)

### ISSUE THREAD

**Issue by ExperimentsAndIdeas** [alanmcgovern/monotorrent#427]
Hello, do you have any connection to .Onion addresses (Tor)?

I have a set of files that I want to keep redundant on a .Onion address accessed by MonoTorrent.

Do you have an integration, or know of one that exists entirely on Mono (MonoTorren over Tor for HSP .Onion access) 

https://www.torproject.org

**Comment by alanmcgovern** [comment]
Its not something I've looked into before. If you want to try and integrate some kind of proxy support to push traffic over TOR, I'd be interested in seeing if it could be supported as a third party/external extension.

**Comment by alanmcgovern** [comment]
If you have any questions about putting torrent traffic through Tor feel free to each out. For now I'll close this issue as it is not something I'll work on personally, for now at least.
