### ISSUE TITLE
Handle invalid Uri in HttpSeeds

### ISSUE THREAD

**Issue by phil-scott-78** [alanmcgovern/monotorrent#428]
Working with some torrents from archive.org I'm seeing they have an invalid absolute Uri in their torrent file. E.g. this torrent  https://archive.org/download/latinmass2/latinmass2_archive.torrent has an entry for `/8/items/` which throws an exception in ` MonoTorrent.Client.Modes.Mode.DownloadLogic`.  

```
      Unexpected main loop exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at MonoTorrent.Client.Modes.Mode.DownloadLogic(Int32 counter)
   at MonoTorrent.Client.Modes.Mode.Tick(Int32 counter)
   at MonoTorrent.Client.Modes.DownloadMode.Tick(Int32 counter)
   at MonoTorrent.Client.ClientEngine.LogicTick()
   at MonoTorrent.Client.ClientEngine.<.ctor>b__77_0()
      MonoTorrent.Client.MainLoop.<>c__DisplayClass10_0.<QueueTimeout>g__Callback|0(Object state)
…     MonoTorrent.Client.MainLoop.Loop()
```

I could create a PR that uses `Uri.TryCreate` but I'm not sure if the best place to put the logic would be in the `DownloadLogic` to just ignore these entries, or in the torrent loading logic.

**Comment by alanmcgovern** [comment]
I've never been thrilled about how http seeds are integrated, so in the interests of making things a little bit better... Would you be up for submitting a patch which fixes things at the Torrent loading side of things? I could imagine exposing this as a List<Uri> in the Torrent class, rather than a List<string>. 

If you're not up for making that adjustment I can get around to it in the next day or three!

**Comment by phil-scott-78** [comment]
I suspect GH ate part of your comment there when talking about the List. I was going to assume you were thinking about exposing it as a `List<Uri>` rather than a `List<string>`. I already created a PR that tidies up HTTP list with #429 but I could change this to a `List<Uri>` pretty easily. Doesn't look like there would be much of a change internally, but this would obviously be a breaking change. I guess now's the time for that if you want to go that route

**Comment by alanmcgovern** [comment]
Yup, you're exactly right. GH seems to have tried treating it as html or some nonsense. Oops!

Breaking API and exposing it as a List of Url would be ideal. This will roll into v2 which has far larger breaking changes already :)

Thanks for the PR!

**Comment by phil-scott-78** [comment]
I'll get the PR updated. 👍

**Comment by phil-scott-78** [comment]
Pushed the change to `IList<Uri>`. Left it as two commits because I kind of felt like they were doing two different tasks. Feel free to squash away if needed.

**Comment by alanmcgovern** [comment]
Great stuff. I just merged that in! Thanks for taking the time to make those changes
