### ISSUE TITLE
Some ideas for new api

### ISSUE THREAD

**Issue by uponatime2019** [alanmcgovern/monotorrent#433]
Hello I'm creating a new app using new API. Some ideas I think should be integrated into 2.0 api (or it already there but I can't discover)
- Provide exactly path to torrent folder. If it have folder contains files, it should point to that path, if torrent have only one files it should point to parent of that files. So we can open folder to show user files (like uTorrent)
- Method to **"Delete Torrent Only"** and **"Delete Torrent And Data"**. Currently I must **StopTorrent**, then remove **Manager** from Engine, then delete torrent file (Can't find **TorrentPath** in this version), then delete all files (sometimes can't delete file because file in use?)
- If add new Torrent from MagnetLink, after download metadata that **Torrent File** should save to **TorrentsPath**, but it's not
- It's still take so long to load big downloaded file at start (May be I can skip that, but I don't know how, some examples is good)
- In UWP app if set  AutoSaveLoadFastResume = true, but don't set CacheDirectory, it will have error when StopTorrent because default cache directory ( ./ ) not accessible in UWP. If I set CacheDirectory it will running OK

**Comment by alanmcgovern** [comment]
> it will have error when StopTorrent because default cache directory ( ./ ) not accessible in UWP. If I set CacheDirectory it will running OK

https://github.com/alanmcgovern/monotorrent/pull/436

I think the simplest solution here is to no longer use `./` as the default value. `EngineSettings` and `EngineSettingsBuilder` will default to `null` instead.

The `ClientEngine` constructor will throw an error if `Settings.CacheDirectory` is null, or if the path chosen by the user is not writable. These checks will also be performed whenever UpdateSettingsAsync is invoked.

The other ideas are pretty interesting too! I'll keep them in mind and get back to you when i have updates/thoughts!

**Comment by alanmcgovern** [comment]
> 
> 
> Hello I'm creating a new app using new API. Some ideas I think should be integrated into 2.0 api (or it already there but I can't discover)
> 
>     * Provide exactly path to torrent folder. If it have folder contains files, it should point to that path, if torrent have only one files it should point to parent of that files. So we can open folder to show user files (like uTorrent)

`return TorrentManager.HasMetadata && TorrentManager.Files.Length == 1 ? TorrentManager.Files[0].FullPath : TorrentManager.SavePath;`

It's not built in, but this approach should give you the result you want in the meantime.

> 
>     * Method to **"Delete Torrent Only"** and **"Delete Torrent And Data"**. Currently I must **StopTorrent**, then remove **Manager** from Engine, then delete torrent file (Can't find **TorrentPath** in this version), then delete all files (sometimes can't delete file because file in use?)
> 
>     * If add new Torrent from MagnetLink, after download metadata that **Torrent File** should save to **TorrentsPath**, but it's not

I have a thought here! What if these guarantees were made:

- Whenever `ClientEngine.AddAsync(MagnetLink link)` is invoked, the metadata will be written to disk in the cache directory once it's downloaded, and then that copy will be loaded into the TorrentManager.
- Whenever `ClientEngine.AddAsync(string filePath)` is invoked, the torrent file will be copied to the cache directory and then loaded into the TorrentManager.

In both of those scenarios there'll be a known path on-disk, and it will be in the cache directory. The TorrentManager will expose the path to this file (`TorrentManager.MetadataPath` for example)

- Whenever `ClientEngine.AddAsync(Torrent)` is invoked, the engine will not have a reference to the original .torrent metadata and so nothing will be written to disk and there'll be no known path to metadata.

If the above guarantees were made, then ClientEngine.RemoveAsync (TorrentManager)` could take an enum, `enum RemoveMode { Nothing, Torrent, Data, TorrentAndData}`.

Additionally, I could add some additional serialization code so most (all?) of the state in a ClientEngine could be written to disk, and then you could easily re-create a `ClientEngine` by calling `ClientEngine.LoadAsync (string path)`. The idea is that when you're app is shutting down you can serialize the engine to disk, which would store the engine settings, all active torrents, the TorrentSettings for each of those, any customisations you've made (for example if you moved files to a new location, set priorities of the files) etc. You could then reload that data next time you start your app.

By virtue of copying all metadata files to the cache directory, it makes it a bit safer to store/reload engine state as things won't break if a user cleans up their 'downloads' directory.

Would this make your life easier, and simplify the problems you're hitting?

>     * It's still take so long to load big downloaded file at start (May be I can skip that, but I don't know how, some examples is good)

That should be solved with the new EngineSetting which auto saves fast resume data. It's enabled by default.

>     * In UWP app if set  AutoSaveLoadFastResume = true, but don't set CacheDirectory, it will have error when StopTorrent because default cache directory ( ./ ) not accessible in UWP. If I set CacheDirectory it will running OK

The engine will check the CacheDirectory is writeable before beginning to download anything. This should make this particular issue less problematic as it'll fail ~immediately.

**Comment by uponatime2019** [comment]
Thanks, I will try to fix problems using your suggestes
