### ISSUE TITLE
UWP Release Mode Fail in Logger

### ISSUE THREAD

**Issue by brunotrevisan** [alanmcgovern/monotorrent#434]
Good night, when compiling a project in UWP in release mode it fails to build the Logger at the very beginning, I just commented I slightly changed the beginning by putting a try catch on it

`  internal static Logger Create ()
        {
            try {
                //return null;
                var callingClassName = new StackFrame (0, true).GetMethod ().ReflectedType.FullName;

                var writer = Factory?.Invoke (callingClassName);
                return new Logger (writer);

            } catch {
                var writer = Factory?.Invoke ("Local");
                return new Logger (writer);

            }
        }`

I'm not familiar with StackFrame but callback

`new StackFrame (0,).GetMethod ()`

returns Null and makes the app Close

**Comment by vlasenkoalexey** [comment]
ReflectedType is not available on UWP release, here is the code I used:

`  
       public static Func<string, ILogger> Factory { get; set; }

        private static string GetClassFullName ()
        {
            // Code from https://github.com/NLog/NLog/blob/master/src/NLog/Internal/StackTraceUsageUtils.cs
            int framesToSkip = 2;

            string className = string.Empty;
            var stackTrace = Environment.StackTrace;
            var stackTraceLines = SplitAndTrimTokens(stackTrace.Replace ("\r", ""), '\n');
            for (int i = 0; i < stackTraceLines.Length; ++i) {
                var callingClassAndMethod = stackTraceLines[i].Split (new[] { " ", "<>", "(", ")" }, StringSplitOptions.RemoveEmptyEntries)[1];
                int methodStartIndex = callingClassAndMethod.LastIndexOf (".", StringComparison.Ordinal);
                if (methodStartIndex > 0) {
                    // Trim method name. 
                    var callingClass = callingClassAndMethod.Substring (0, methodStartIndex);
                    // Needed because of extra dot, for example if method was .ctor()
                    className = callingClass.TrimEnd ('.');
                    if (!className.StartsWith ("System.Environment") && framesToSkip != 0) {
                        i += framesToSkip - 1;
                        framesToSkip = 0;
                        continue;
                    }
                    if (!className.StartsWith ("System."))
                        break;
                }
            }
            return className;
        }

        private static string[] SplitAndTrimTokens (string value, char delimiter)
        {
            if (String.IsNullOrWhiteSpace (value))
                return new string[0];

            if (value.IndexOf (delimiter) == -1) {
                return new[] { value.Trim () };
            }

            var result = value.Split (new char[] { delimiter }, StringSplitOptions.RemoveEmptyEntries);
            for (int i = 0; i < result.Length; ++i) {
                result[i] = result[i].Trim ();
                if (string.IsNullOrEmpty (result[i]))
                    return result.Where (s => !String.IsNullOrWhiteSpace (s)).Select (s => s.Trim ()).ToArray ();
            }
            return result;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        internal static Logger Create ()
        {
            var callingClassName = GetClassFullName();
            var writer = Factory?.Invoke (callingClassName);
            return new Logger (writer);
        }
`

Extracted it from Nlog library, works fine as far as I can tell.

**Comment by alanmcgovern** [comment]
The complexity/benefit of this trick doesn't outweigh the simplicity of just passing in the right class name. I've removed this trick and pass in the right classname using `nameof (Class)`. It's refactor-safe so there's still some benefit to this over using a hardcoded string!

Thanks for reporting!
