### ISSUE TITLE
Add feature of dead torrents

### ISSUE THREAD

**Issue by Ennorath** [alanmcgovern/monotorrent#437]
It's the question and in same time idea to add feature to library.

What is the best way to detect dead torrent? (By dead torrent I mean, that it's not downloading for long-time)
0 speed, or seeds.
If you have it, please, write it. I will propose my experience:
Firstly, I thought about tracing percentage of torrent and make timer, like if after 1 hour < 20% downloaded - delete it.
Then realized, that it depends more on speed\seeds, so if torrent completely dead, it means there 0 seeds. 
Is it possible to check on seeds on MonoTorrent library?  

Following line showing requests, does it mean seeds, peers and leaches are under it? - 
AppendFormat(sb, "Current Requests:   {0}", await manager.PieceManager.CurrentRequestCountAsync());

**Comment by alanmcgovern** [comment]
It really depends on how accurate you want to be.

The simplest approach would be to send a Scrape request to the trackers. If they report 0 seeders and 0 leeches then you could check the bittorrent DHT. If you get zero peers from DHT when announcing the infohash, then the torrent is probably dead.

Would this approach work for you?

You could try to actively download the torrent to be 110% certain, but it may not be worth the hassle.

**Comment by Ennorath** [comment]
> It really depends on how accurate you want to be.
> 
> The simplest approach would be to send a Scrape request to the trackers. If they report 0 seeders and 0 leeches then you could check the bittorrent DHT. If you get zero peers from DHT when announcing the infohash, then the torrent is probably dead.
> 
> Would this approach work for you?
> 
> You could try to actively download the torrent to be 110% certain, but it may not be worth the hassle.

Oh thanks for the reply! If it's not hard, can you help me with one more thing.
Torrent speed is 0 in console, but when I'm adding same torrent to UTorrent application, it downloads with speed 15.4 mbit\s. Is it possible that reason is downloading in same time 20 torrents? Is there any queue? I didn't set up any limits (Like maximum download 20 torrents, or smth like this.). But usually it downloads 2-3 torrents in same time. Or what reason else can be?

**Comment by alanmcgovern** [comment]
If the issue is that monotorrent isn't evenly distributing connections amongst all active torrents, then you might solve the problem by restricting the total number of active connections per-torrent to be 40, and then making the total number of active settings overall be 1000.

These settings are in EngineSettings and TorrentSettings.

Let me know if that solves your problem and i can take another look at how the engine chooses to allocate connections! It's supposed to be reasonably fair already, so perhaps another focus on this would help!

**Comment by Ennorath** [comment]
Is it possible to use proxy on monotorrent? Because I have feelings that server banned my ip on speed, is it possible? Coz torrents from other sources are downloading pretty fast, comparing to it. Now I have 4100 kb/s, when in first source around 200 kb/s is high peak.

**Comment by alanmcgovern** [comment]
A server cannot slow down your download rate directly. Transfer rate is determined purely by the peers your are connected to. If some torrents are slow then maybe you need to connect to more peers, or maybe there are just few high quality seeders around and that's limiting your download rate. 

It's not easy to tell.
