### ISSUE TITLE
Can't connect locally.

### ISSUE THREAD

**Issue by justscribe** [alanmcgovern/monotorrent#439]
Hi,

I have an issue while trying to download torrent on and from same machine.
Before it was ok (maybe a half of the year ago), but after latest updates, it can't connect.
![image](https://user-images.githubusercontent.com/8200485/115992134-bf88de80-a5d4-11eb-8bc8-f71ad3457ec0.png)
I've also implemented saving peer data in the DB:
![image](https://user-images.githubusercontent.com/8200485/115992950-fb25a780-a5d8-11eb-9684-ce8caa71cbd2.png)

So,
On port 8999 is qBittorrent client, that is seeding.
On port 1000 is MonoTorrent client, that trying to download.
Torrent tracker (Mono) is on another machine (Linux), but in local network (it works also outside, necessary ports are open).
I understand a try to use a public IP (grayed), but 192.168.1.1... It's a router address. Machine local address is different.
Maybe I've missed some configuration option.
Help=)

**Comment by alanmcgovern** [comment]
`192.168.1.1` is definitely strange. This should not be advertised/used by anything!

Can you determine where this address is coming from? Are the clients reporting this, or is the tracker doing the wrong thing?

**Comment by justscribe** [comment]
I'd say it comes from router, when it redirecting clients.
As example of one request we have: Public IP -> Router IP -> Local IP (Tracker).
Clients are using Public address to connect to local Tracker, so it might using router to connect locally, without direct (Local IP to Local IP) connection, but (Local IP to Router IP to Local IP). I don't know why it's happened now... It's very strange.

**Comment by alanmcgovern** [comment]
I'm asking a slightly different question...

Are the clients accidentally configured to send the ipaddress '192.168.1.1' to the tracker? Or is the tracker mis-detecting the IPAddress of clients which send an announce? Or is something else bizarre happening? Are the clients discovering each other using local peer discovery and is that embedding the incorrect address?
