### ISSUE TITLE
Priority.DoNotDownload

### ISSUE THREAD

**Issue by ScorpionsSM** [alanmcgovern/monotorrent#444]
how to select a file in priority?
` foreach (var file in manager.Files)
                    {
file.Priority = Priority.DoNotDownload;
                    }`

not work

**Comment by alanmcgovern** [comment]
You need: TorrentManager.SetFilePriorityAsync(ITorrentFileInfo, Priority)

Let me know if you have any issues with that!

**Comment by ScorpionsSM** [comment]
foreach (var file in manager.Files)
                    {
             await manager.SetFilePriorityAsync(file, Priority.DoNotDownload);
                    }

did i do the right thing?

**Comment by alanmcgovern** [comment]
That should be correct!

**Comment by ScorpionsSM** [comment]
Thank you for such a program, it was difficult to switch to the new version, but everything worked out, thank you!

**Comment by ScorpionsSM** [comment]
just didn't figure out how to work with the creation of a torrent for now

**Comment by alanmcgovern** [comment]
@ScorpionsSM If you have any questions please let me know and I can add samples here: https://alanmcgovern.github.io/monotorrent/
