### ISSUE TITLE
MetadataMode Available is out of sync with AvailablePeers.Count;

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [alanmcgovern/monotorrent#447]
in Tick Method, we should call Manager.Peers.UpdatePeerCounts (); as in Mode.Tick();
and in Tick() Method, if we run out of Peers, we should call SendAnnounces() again.

**Comment by alanmcgovern** [comment]
I'm just going through old tickets. I'll address this as part of https://github.com/alanmcgovern/monotorrent/pull/575 :)

**Comment by alanmcgovern** [comment]
>  if we run out of Peers, we should call SendAnnounces() again

This is implemented now. The re-announce behaviour is the same between `MetadataMode`, `PieceHashesMode` and regular `DownloadMode`.
