### ISSUE TITLE
Crash on release mode UWP

### ISSUE THREAD

**Issue by uponatime2019** [alanmcgovern/monotorrent#448]
![image](https://user-images.githubusercontent.com/15900671/121703404-fa9b8e80-cafc-11eb-9a74-725f232434fe.png)
This happen only in release mode UWP app. App fine in debug mode
All fixed when replace this function in Logger.cs
```
        internal static Logger Create ()
        {
            return new Logger (null);

            //var callingClassName = new StackFrame (1).GetMethod ().ReflectedType.FullName;
            //var writer = Factory?.Invoke (callingClassName);
            //return new Logger (writer);
        }
```

**Comment by vlasenkoalexey** [comment]
I thought this should have been fixed by now, see: https://github.com/alanmcgovern/monotorrent/issues/434

**Comment by uponatime2019** [comment]
> I thought this should have been fixed by now, see: https://github.com/alanmcgovern/monotorrent/issues/434

Still crash in mono.nat

**Comment by alanmcgovern** [comment]
https://github.com/alanmcgovern/Mono.Nat/releases/tag/release-v3.0.2
