### ISSUE TITLE
Better separate components so they can be used outside of the MonoTorrent

### ISSUE THREAD

**Issue by alexanderfedin** [alanmcgovern/monotorrent#449]
I am looking for to use DHT and file sharing features of this in a separate (very promising!) product, but they are mostly either having "internal" or "private" level of visibility. Of course, I can change that in my branch, but then it shall be more and more difficult to merge with the main repo.

**Comment by alanmcgovern** [comment]
That's definitely doable. What exactly is your usecase? If I had a better idea of what you needed direct access to the Dht code for I could figure out the best way to support it
