### ISSUE TITLE
looks like monotorrent got memory leak in tracker

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [alanmcgovern/monotorrent#450]
![image](https://user-images.githubusercontent.com/53161726/123790375-d6b7b580-d910-11eb-8bca-91da087352ff.png)
![image](https://user-images.githubusercontent.com/53161726/123790429-e46d3b00-d910-11eb-83cc-064684afc687.png)

**Comment by OneFingerCodingWarrior** [comment]
it's related to SemaphoreSlimExtensions, after i comment out using (await AnnounceLimiter.EnterAsync ())
everything back to normal

**Comment by mfkl** [comment]
Can you share a minimal repro please?

**Comment by alanmcgovern** [comment]
This should be fixed now. This issue would manifest when there were over 10 tracker tiers in a torrent, and the trackers within that tier frequently timed out or were unresponsive.

The fastpath which discarded excessive announce attempts occurred *after* rate-limiting was applied, but announce attempts should have been discarded *before* rate-limiting was applied. That meant a significant queue of attempts could build up when there were dozens/hundreds of tracker tiers, though the majority of those queued attempts would be a no-op in the end.
