### ISSUE TITLE
Is this project not maintained and upgraded??

### ISSUE THREAD

**Issue by BoyFaceGirl** [alanmcgovern/monotorrent#455]
.net   there is a great need for such an excellent project

**Comment by alanmcgovern** [comment]
It's updated whenever i have time or interest.

Is there something in particular you're looking for? Pull requests are always welcome!

**Comment by alanmcgovern** [comment]
Let me know if you have any questions! I don't think there's any action to take on this so i'm going to go ahead and close the issue.
