### ISSUE TITLE
Regression in legacy 1.0 releases

### ISSUE THREAD

**Issue by samhocevar** [alanmcgovern/monotorrent#496]
Hi! There is a regression in dd028c6d158a9090b0fc262203633510ae649010: `Torrent.Load (Stream stream, string path)` no longer stores `path` in `torrentPath`. Since `TorrentPath` is read-only, application code cannot bypass this bug.

This is specific to the 1.0 releases, so probably of low importance to you, but there are public NuGet packages for these and I have legacy apps that still use them…

I cannot create a PR because there is no longer a branch against which a PR can be created, but I pushed a fix in https://github.com/alanmcgovern/monotorrent/tree/fix-torrentpath-init

**Comment by alanmcgovern** [comment]
I created a branch from the 1.0.29 tag and merged your proposed change to it. 

https://github.com/alanmcgovern/monotorrent/tree/monotorrent-1.0.30

As the change is quite small I'm happy to make a new release for it. Thanks for reporting the issue!

MonoTorrent 2.0 handles this a bit differently. `Torrent` objects are immutable and are a direct representation of the contents of the `.torrent` file itself. i.e. the Torrent object does not store the full path to files on disk, or the path where the metadata was loaded from, etc. That data is available on the TorrentManager object itself.

Now, when you call ClientEngine.AddAsync, the engine will automatically store a copy of the metadata in it's Cache directory. This can be a `File.Copy` of the original .torrent file, or if you use a magnet link the data will be written to disk once it's been downloaded from other peers. You can access this path using `TorrentManager.MetadataPath`. The path to the original file (if there was one) is not stored anywhere. This makes things a little more consistent when dealing with torrents loaded from files and torrents loaded from magnet links.

Is this new approach usable for you?

**Comment by samhocevar** [comment]
> Is this new approach usable for you?
Sure, I can still keep a dictionary of torrent file paths if necessary. Thanks for merging this!

**Comment by alanmcgovern** [comment]
Published to NuGet!

**Comment by alanmcgovern** [comment]
https://github.com/alanmcgovern/monotorrent/releases/tag/release-v1.0.30
