### ISSUE TITLE
Download piece in sequence

### ISSUE THREAD

**Issue by rupisaini123** [alanmcgovern/monotorrent#505]
I am using stream to live stream the download file on http.
But the file pieces are not downloading in sequence, and I am not able to figure out how to download pieces in sequence from start to end. I am using AddStreamingAsync to add new torrent.
Downloading video is of 800mb over 1:30hrs. Its downloaded 70% but I can't play over 4 mins, have to wait until 100% download is complete.
Please provide an example using latest version of MonoTorrent.
Really appreciate your good work.

**Comment by alanmcgovern** [comment]
When you use AddStreamingAsync, do you also access the file data using `TorrentManager.StreamProvider`?

https://github.com/alanmcgovern/monotorrent/blob/master/src/MonoTorrent.Client/MonoTorrent.Streaming/StreamProvider.cs

If you use `CreateStreamAsync` you get a seekable `Stream` object which you can use to play media. Seeking the stream causes the torrentmanager to download the appropriate set of pieces.

There's also a `CreateHttpStreamAsync` which is (essentially) the same, except you can pass the `Uri` from that object to any player which plays from a Uri (for example VLC) and the same magic occurs. You can seek to any position in that player and the engine will download the correct set of bytes.

**Comment by alanmcgovern** [comment]
There's a VLC example here, though you will likely need to change the path to VLC: https://github.com/alanmcgovern/monotorrent/blob/master/src/Samples/SampleClient/VLCStream.cs#L69

There's also another example here using libvlc-sharp: https://github.com/mfkl/lvst

**Comment by rupisaini123** [comment]
Actually i am using web api, in Webapi i have to create new stream with new request. But that doesn't work, as I can't maintain the state of stream in web api. Can only have one stream for torrent, but not able to retrieve the last stream.
So i was just using FileResult with partialdata 206.
Is there a way to to use stream in webapi

**Comment by alanmcgovern** [comment]
I don't know what 'web api' is in this context. 

At a high level there are two parts:
1) There's some process which has loaded monotorrent.dll and is actively downloading torrents.
2) There's a process (maybe the same one?) which wants to play media which is being downloaded by monotorrent.

As long as process 2 knows what bytes it needs and it can communicate with process 1, then process 1 can create a 'Stream' object with `TorrentManager.StreamProvider` and then seek/read the required bytes using that stream, and then send those bytes back to process 2.

**Comment by alanmcgovern** [comment]
I'll close this for now. It's rare that someone wants sequential downloading *without* also needing to know when the pieces are available, or being able to seek to arbitrary locations. As such the exposed API should be more than enough to solve your problem. 

If not, please share some more details about your precise usecase and I'll see what change(s) could be made to better support it!

Thanks!
