### ISSUE TITLE
Use FileAccess.Read during seeding

### ISSUE THREAD

**Issue by vasama** [alanmcgovern/monotorrent#506]
The library seems to always use `FileAccess.ReadWrite` during seeding, or at least when download is completed and seeding begins.
This seems to be a regression of https://github.com/alanmcgovern/monotorrent/issues/421 that occurred when `DiskWriter` was introduced.

**Comment by alanmcgovern** [comment]
> or at least when download is completed and seeding begins.

There's a missing `CloseAsync` call when changing from downloading -> seeding mode which leaves the files open in Read/Write mode.

If you want to work around it in the meantime, you can call `StopAsync` and then `StartAsync`. This will cause the files to be closed, and then if/when they're reopened they'll be opened using `FileAccess.Read`.

I'll push a fix for the downloading -> seeding transition! Thanks for reporting

**Comment by alanmcgovern** [comment]
Fixed by 
https://github.com/alanmcgovern/monotorrent/commit/f54c4ead433ac7ef7541636bd7f884e9930201ad
https://github.com/alanmcgovern/monotorrent/commit/c603f9fd8095fb99f41101e424706e3d4cb487bc
