### ISSUE TITLE
AddAsync allows duplicates

### ISSUE THREAD

**Issue by jpmikkers** [alanmcgovern/monotorrent#509]
Found by accident on monotorrent 2.0.4, `AddAsync(MagnetLink magnetLink, string saveDirectory)` will happily add the same magnet link multiple times (to the same download location). This results in some strange behavior due to multiple TorrentManagers downloading the same thing. It's easy to prevent this beforehand by checking if the infohash is already present of course so it's barely an inconvenience.

**Comment by alanmcgovern** [comment]
Oops! Sorry about that. I had this fixed a few months ago but never backported it - https://github.com/alanmcgovern/monotorrent/commit/849ffd665213af7b65e1e5a3952a5f792035a36d

I'll pop it in the 2.0 release branch now and i'll push an update over the next few days! Thanks for reporting the issue!
