### ISSUE TITLE
Re add torrents after app restart

### ISSUE THREAD

**Issue by rupisaini123** [alanmcgovern/monotorrent#510]
I need some help. Whenever app restart the previous downloding torrents will be gone. But if added same torrent it will start from same  progress. 

Is there any way to retrieve and add those torrents that were in progress before the app restart automatically, on app start.

**Comment by jpmikkers** [comment]
you're probably looking for `ClientEngine.SaveStateAsync()` and `static ClientEngine.RestoreStateAsync()`.

**Comment by alanmcgovern** [comment]
@rupisaini123 Let me know if that didn't answer your question, or if you have issues with those APIs!
