### ISSUE TITLE
get ETA

### ISSUE THREAD

**Issue by E4zily** [alanmcgovern/monotorrent#512]
can i get the ETA of when the torrent is going to finish downloading? if so, how?

**Comment by jpmikkers** [comment]
It's easy to calculate yourself like this: 
```
private const int MaxETA = 60 * 60 * 24 * 300;
var EtaInSeconds = Math.Min( MaxETA, (int)((manager.Torrent.Size - manager.Monitor.DataBytesDownloaded) / (double)Math.Max(1, manager.Monitor.DownloadSpeed)));
```

**Comment by alanmcgovern** [comment]
You have access to the size of the torrent, the completion progress, and the download rate. With that you can produce estimates with whatever accuracy you need, with whatever smoothing makes sense for your usecase. Let me know if you have issues!

`manager.Monitor.DataBytesDownloaded`

Note: This API just tells you how many bytes have been downloaded in the current session. If you want the total amount of data remaining to download across multiple download sessions, just use: `(int)((1 - manager.Progress / 100.0)  * manager.Size)`

Progress is a value between 0 and 100 (it should really be between 0 and 1), so this will tell you the amount of the data whic h *has not* been downloaded.
