### ISSUE TITLE
[Question] Next release date? Looking forward to it!

### ISSUE THREAD

**Issue by jeffward01** [alanmcgovern/monotorrent#514]
Hello!

First of all amazing library! Thank you for being the hero the c# community needs for BitTorrent technology. You deserve massive credit and kudos!!

# Question 

I saw some great updates in the code base on GitHub that are not reflected in the latest nuget package such as:

•Completed and In Progress folders 
• append suffix to the file extension if not complete
• and a few others. 

I would rather stick to the nuget releases compared to modify the existing code or pull down the GitHub code. 

When do you estimate the next release to nuget will be?

## other question 

Aside from implanting BEPs, are there any ways we can help contribute to this library?

—-

Thanks again for this awesome code!!!

**Comment by alanmcgovern** [comment]
I'm intending on beginning to release alpha/beta releases for monotorrent 3.x in the near term. One of the things i wanted to support was BEP52, which is *probably* good enough to ship in it's current state. There's no support for mixed-swarm torrents yet, and there's no support for creating BEP52 compliant torrents, but that can be added before releasing the stable `MonoTorrent 3.0.0`.

If you want to play around with a zip file generated from master you can grab the nupkg from https://github.com/alanmcgovern/monotorrent/releases/tag/release-v3.0.0-alpha-0142 and give it a whirl.

I'm open to suggestions/ideas/fixes before I start releasing versions on NuGet.org. There are still some API changes being made in support of the migration to Memory<byte>/Span<byte>. ReadOnlyMemory<T>/ReadOnlySpan<T> have made several APIs much safer and it'd be good to finalise those migrations to avoid future API breaks.

> Aside from implanting BEPs, are there any ways we can help contribute to this library?

I've always struggling with getting a nice setup for creating and updating documentation. If you have any experience in that area, i'd definitely appreciate help getting the scaffolding in place and a clear process for adding new samples/documentation :)

**Comment by alanmcgovern** [comment]
I'm just going to close this as things are approaching completion for a v3 release.

BEP52 support is done (i think), and that was the major thing I wanted to support. There are alpha releases on nuget.org already :)
