### ISSUE TITLE
[Question] I’m having issues performing a hash recheck on an incomplete file 

### ISSUE THREAD

**Issue by jeffward01** [alanmcgovern/monotorrent#516]
Hello!

Ive  been working with this library a lot lately, it’s very cool and I’d like to learn more about how it works so I can contribute and build some tools with it!

I am having issues performing a hash re-check on partially complete torrent files. This is a process I use:

* download any torrent to 50% completion using QBittorrent or similar software
* Move the ‘.torrent’ file to monotorrent 
* Move the 50% complete file to the ‘SavePath’ in MonoTorrent
* Perform a re-hash
* When the re-hash completes the torrent within MonoTorrent shows 0 percent. I would expect it to show as 50% 

If I repeat the above steps using a torrent which was downloaded to 100% using Qbittorrent or similar, Monotorrent processes that fine and will mark the torrent as 100% complete and begin to seed. 

Am I doing something wrong with the lack of “FastResume” files? I don’t want to say this is a bug, I don’t know if this is operating as “expected” or not. 

—

my goal is to write a software which migrates torrents from Qbittorrent and other clients to MonoTorrent, so thus partial hash recheck is an important piece of the workflow 

thanks all!

**Comment by jeffward01** [comment]
I have tested this again using `Deluge` then adding the torrent to MonoTorrent and checking the progress. It seems to work in this case.

However, when i used `QBittorrent`, then added to MonoTorrent it did not seem to work.  Also, it seems that if:

* I download a file to 50% with `Deluge`, for example: `C:/downloads/deluge`
* I add the torrent to MonoTorrent _with a different download directory_ for example: `C:/downloads/monotorrent`
* I download the file 5% using MonoTorrent
* Then I set the directory of MonoTorrent to  `C:/downloads/deluge`
* Then I perform a ReCheck hash using MonoTorroent
* MonoTorrents seems to have issues recognizing the file is at 50% 
* I must remove the torrent from monoTorrent completely, then re-add the torrent with `C:/downloads/deluge` and perform a 'Recheck hash', under this condition MonoTorrorrent sees the file at 50% completion

Is anyone else experiencing this?

I opened a ticket #515 to better understand how 'ReHashing' works so that I can understand why and when this occurrs.

Thanks all

**Comment by alanmcgovern** [comment]
Is this still an issue? I suspect the underlying problem is that the paths passed to MonoTorrent result in it looking for the partial file in a different location.

While it's a long time since this was filed, can you check the values of `TorrentManager.Files[xxx].FullPath` and ensure it's actually pointing at the partial file?

I'll close this for now as it's probably just a path issue and there was some conversation on the other ticket :)
