### ISSUE TITLE
v2 only magnet links don't parse correctly

### ISSUE THREAD

**Issue by jpmikkers** [alanmcgovern/monotorrent#520]
Tested on v3.0.0 alpha 0142:
The following **v2 only** magnet link doesn't parse correctly. It fails with System.FormatException: the magnet link did not contain a valid 'xt' parameter referencing the infohash. The v1/v2 hybrid one does work.
`magnet:?xt=urn:btmh:1220caf1e1c30e81cb361b9ee167c4aa64228a7fa4fa9f6105232b28ad099f3a302e&dn=bittorrent-v2-test`

Found those tests links here: [https://blog.libtorrent.org/2020/09/bittorrent-v2/](https://blog.libtorrent.org/2020/09/bittorrent-v2/)
Alan, I wouldn't mind having a go at fixing this one.

**Comment by alanmcgovern** [comment]
If you're interested, it's not a bug, it's just some code that hasn't been implemented yet! There are still some rough edges around V2 torrents :)
```
                            case "urn:btmh:":
                                // placeholder to parse v2 multihash
                                break;
```

**Comment by jpmikkers** [comment]
work in progress: https://github.com/jpmikkers/monotorrent/commit/ac8bb0b3548bb6417d6ff4f35507d6866ef67dcd

**Comment by alanmcgovern** [comment]
Looks great so far! I like the usage of slicing the `Memory` here to cut out the identifier bytes! https://github.com/jpmikkers/monotorrent/commit/ac8bb0b3548bb6417d6ff4f35507d6866ef67dcd?w=1#diff-c86c3ce1d7bf3c4a55f211238b36781ed5c2b1f2975e8024d3fd26bb50470d72R195 . Glorious!
