### ISSUE TITLE
Implement support for BEP47

### ISSUE THREAD

**Issue by alanmcgovern** [alanmcgovern/monotorrent#522]
https://www.bittorrent.org/beps/bep_0047.html

@jpmikkers  I was just curious if you were interested in tackling adding support for this BEP. It's one of the pieces needed to complete full support for BitTorrent V2. No pressure at all if you're not interested/able to take it on - I just figured I'd ask in case you were looking for something!

Otherwise I can tackle this over the next while :)

**Comment by jpmikkers** [comment]
I'll experiment a little tomorrow. Decoding the additional fields seems easy enough, but I feel I may run into questions on how to handle the padding files higher towards the monotorrent user-api.

**Comment by alanmcgovern** [comment]
I can definitely give more thorough guidance as needed! I'll write something a bit more detailed today/tomorrow, and if at any point you want to pass it back to me feel free!

You just seemed like an interested contributor so I figured I'd test the waters :)

**Comment by jpmikkers** [comment]
I can produce padded v1 torrents now:
https://github.com/jpmikkers/monotorrent/commits/bep0047

Is that somewhat in the right direction?

**Comment by alanmcgovern** [comment]
Yup, that looks pretty great! The only real change I'd suggest would be to keep `TorrentFileTuple` internal, not public. The implementation is great.

There's one potential optimisation - It looks like that implementation would [create a padding file after the very last file](https://github.com/alanmcgovern/monotorrent/compare/master...jpmikkers:bep0047#diff-adac72b2edb8c5a6701db3bfc3019a71482764e254eedaa236fc4cad8515d886R229-R233)? If so, while that isn't a problem as such, it's also not necessary. Everything would work as-expected if the final padding file is omitted.

If you want to take a shot at integrating padding such that we never download them, but also always generate the correct hashes, keep on reading!

Throughout this explanation assume these things are true:
- The piece length is 256kB.
- Assume 'piece 7' contains the last 100kB of the first file
- Assuming there's a 156kB padding file to ensure the second file starts at a piece boundary.

For clarity I'll highlight this:
- In BitTorrent V2 the hash for piece 7 would be the SHA256 hash of the 100kB of data.
- In BitTorrent V1 the hash for piece 7 would be the SHA1 hash of the full 256kB - the 100kB of data and the 156kB of padding.

I wonder if it would be possible to make it so that [ITorrentInfoExtensions.BytesPerPiece](https://github.com/alanmcgovern/monotorrent/blob/48778b785842108945cf2db5ac818bc6c3afa63c/src/MonoTorrent/MonoTorrent/ITorrentInfo.cs#L80-L98) always ignore padding files. This way, when downloading a padded torrent from a peer who supports the V1 or V2 protocol we would only ever request non-padding bytes. No further tweaks would be needed to ensure padded bytes are *not* requested from peers.

If we need to compute the SHA256 hash for this file as per V2 spec, nothing further needs to be done. We have all the bytes we need.

If we need to compute the V1 hash for that piece, we will need to append extra 0s to the hasher as the padding bytes are included in V1 hashes.

The trick we would apply would be that when we receive all 100kB of data and try to get the V1 hash we would need to  augment [this code](https://github.com/alanmcgovern/monotorrent/blob/48778b785842108945cf2db5ac818bc6c3afa63c/src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs#L128-L129) to do something like:

```
// There are probably other ways to check if 
var fileIndex = GetFile(pieceIndex);
if (fileIndex + 1 < manager.Files.Count && manager.Files[fileIndex + 1].IsPadding)
    SHA1Hasher.AppendData (new byte [manager.Files[fileIndex + 1].Length);

return SHA1Hasher.TryGetHashAndReset (dest.V1Hash.Span, out int written) || written != dest.V1Hash.Length))
``` 

Or something like that. 

The `DiskManager` code already operates on `ITorrentFile`, so we would also need to augment various methods, [like this](https://github.com/alanmcgovern/monotorrent/blob/48778b785842108945cf2db5ac818bc6c3afa63c/src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs#L287-L291) to return true when checking for the existence of a padding file. Similarly, if something tries to [read](https://github.com/alanmcgovern/monotorrent/blob/48778b785842108945cf2db5ac818bc6c3afa63c/src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs#L444) padding bytes we could just fill in all zeros immediately and return.

Let me know if that doesn't make sense!

**Comment by jpmikkers** [comment]
That makes sense, I do have a question though. As it is now, the pad files make it past torrent decoding, they show up as separate entries in Torrent.Files.  What if I would get rid of those entries (somewhere in the Torrent constructor) and just mark the preceding real file entry as needing 'x' padding bytes? I think it would make for much cleaner logic onward, not having to deal with the separate pad file entries. Would that work, or would we run into v1/v2 problems with that eventually?

**Comment by alanmcgovern** [comment]
Hrm, it's an interesting idea. I've been having a think about the implications of this and I can't see a reason why this wouldn't work.

There's no reason a *user* of MonoTorrent would ever need to know about these padding files, so it would make sense that `TorrentManager.Files` does not expose them. Having a property on `ITorrentFIle` which represents the number of padding bytes would be a simple way to retain this data in a non-intrusive way. There are two things I'd consider/review:

1) Will existing users of the  [ITorrentFile.OffsetInTorrent](https://github.com/alanmcgovern/monotorrent/blob/48778b785842108945cf2db5ac818bc6c3afa63c/src/MonoTorrent/MonoTorrent/ITorrentFile.cs#L59) property still work correctly if there's a 'gap' because the padding file is not in the list of files? I think some code binary searches based on this. I assume it'll all be ok, but it'd be worth checking!

2) If a torrent client which *does not* support BEP47 is requesting data from monotorrent, it will request data from the padding files. As such, while we will never need to *write* data to padding files, we will need to be able to fulfil piece requests sent by other clients/libraries by 'reading' the bytes from these padding files. If there is no `ITorrentFile` for the padding files, then i *think* the only addition we'd have to make would be to check if there are padding bytes on the current file before [looping around to the next file](https://github.com/alanmcgovern/monotorrent/blob/48778b785842108945cf2db5ac818bc6c3afa63c/src/MonoTorrent.PieceWriter/MonoTorrent.PieceWriter/IPieceWriterExtensions.cs#L63-L66). If there are padding bytes, we can write the appropriate amount of zeros to the buffer, and if we still need more data we can loop to the next file then.

So as long as the extension methods like `BytesPerPiece` still 'do the right thing' and the library never generates a requests for padding bytes, we should be good to go with your alternative approach too! 🎉

**Comment by jpmikkers** [comment]
I'll give the fully hidden approach a shot then

**Comment by alanmcgovern** [comment]
Just marking this as done now :) Thanks for working through that!
