### ISSUE TITLE
How to add trackerslist? Is there a code example?

### ISSUE THREAD

**Issue by BoyFaceGirl** [alanmcgovern/monotorrent#528]
I think we should add a globally managed public trackrslist, which can be configured and used when downloading resources,

https://github.com/ngosang/trackerslist

**Comment by alanmcgovern** [comment]
What kind of integration are you thinking of? For something like this you can do something like the following:
```
var torrentManager = await clientEngine.AddAsync (torrentfile);
var tracker = Factories.Default.CreateTracker ("http://whatever.tracker.com/announce")l
await torrentManager.TrackerManager.AddTrackerAsync (tracker);
```

As long as the torrent is not a private torrent you can add as many additional trackers as you want.

**Comment by alanmcgovern** [comment]
I'll close this as the question appears to have been answered!
