### ISSUE TITLE
Stop torrent take more than 1 minute

### ISSUE THREAD

**Issue by uponatime2019** [alanmcgovern/monotorrent#533]
I try sample with 2 different torrent files. It take more than 60s to stop a single torrent

```
            foreach (var manager in engine.Torrents) {
                var now = DateTime.Now;
                var stoppingTask = manager.StopAsync ();
                while (manager.State != TorrentState.Stopped) {
                    Console.WriteLine ("{0} is {1}", manager.Torrent.Name, manager.State);
                    await Task.WhenAll (stoppingTask, Task.Delay (250));
                }
                await stoppingTask;
                if (engine.Settings.AutoSaveLoadFastResume)
                    Console.WriteLine ($"FastResume data for {manager.Torrent?.Name ?? manager.InfoHashes.V1?.ToHex () ?? manager.InfoHashes.V2?.ToHex ()} has been written to disk.");

                Console.WriteLine ($"Stopped {manager.Torrent.Name} - take {(DateTime.Now - now).TotalSeconds}s");
            }
```

Result:
`Stopped fantastic.beasts.the.secrets.of.dumbledore.2022.1080p.hdrip.hevc.x265.rmteam.mkv - take 60.8170329s`

Torrent files used
[torrents sample.zip](https://github.com/alanmcgovern/monotorrent/files/8802111/torrents.sample.zip)

**Comment by alanmcgovern** [comment]
It's probably one (or more) of the trackers failing to respond and hitting the default web request timeout.  

You can pass a cancellation token, or maybe it's a TimeOut, to StopAsync which let's you put an upper bound on the maximum time spent waiting for the trackers to respond. 

I can check in more detail later though.
