### ISSUE TITLE
ClientSample exited with code 1073741845

### ISSUE THREAD

**Issue by lienminhld49** [alanmcgovern/monotorrent#535]
[Example](https://media.discordapp.net/attachments/892748971183857670/987312508241080340/1073741845.png?width=1058&height=601)

Hello !
Please help me to fix this error. Thank you for your support.
I used Client sample to download this file as below but received error " exit with code" (can't find the reason).
[54.torrent](https://cdn.discordapp.com/attachments/892748971183857670/987312976820310046/54.torrent) 

Best regards,
Yu

**Comment by lienminhld49** [comment]
Thank !!!

**Comment by alanmcgovern** [comment]
I'm not sure what the issue is from that alone. If you're compiling from git, are you using master, one of the pre-release 3.x branches, or one of the stable 2.x tags?

**Comment by alanmcgovern** [comment]
Feel free to reopen this if you have any further information to add. I can't tell what the issue is :s
