### ISSUE TITLE
Unhandled exception when start Engine, only in Release mode UWP app

### ISSUE THREAD

**Issue by uponatime2019** [alanmcgovern/monotorrent#537]
It work fine on Debug, but when Release this exception occurred
![image](https://user-images.githubusercontent.com/15900671/174725127-b3165a22-486d-42bb-a40d-f141f139fdd6.png)

**Comment by alanmcgovern** [comment]
Can you let me know if you're using mono.nat 3.0.2 or newer?

https://github.com/alanmcgovern/Mono.Nat/releases/tag/release-v3.0.2

That should've been fixed a while back!

**Comment by uponatime2019** [comment]
> Can you let me know if you're using mono.nat 3.0.2 or newer?
> 
> https://github.com/alanmcgovern/Mono.Nat/releases/tag/release-v3.0.2
> 
> That should've been fixed a while back!

I'm not install Mono.Nat library, it's include in MonoTorrent 2.0.5

**Comment by alanmcgovern** [comment]
If you explicitly add a reference to  Mono.Nat  3.0.2 then it'll probably fix the issue. 

MonoTorrent was probably compiled against a slightly older version of mono.nat and so the explicit upgrade should fix the issue.
