### ISSUE TITLE
Web seeds are slow or do not connect in a hybrid torrent

### ISSUE THREAD

**Issue by chyyran** [alanmcgovern/monotorrent#538]
When downloading a V2 torrent from the Internet Archive, it seems that webseeds are never connected to and the torrent never starts, or stalls after a few moments.

For reproduction, the torrent in question can be found here: 
https://archive.org/details/trails-evo-voices

Although I suspect most torrents from the Internet Archive that are recently derived will have this issue.

```csharp
this.TorrentClient = new ClientEngine();

var torrent = await this.TorrentClient.AddAsync(
                await Torrent.LoadAsync(torrentStream), 
                Path.Combine(Environment.CurrentDirectory, $"download"),
                new TorrentSettingsBuilder()
                {
                    CreateContainingDirectory = false,
                    
                    // encourage webseed use
                    WebSeedDelay = TimeSpan.Zero,
                    WebSeedSpeedTrigger = int.MaxValue,
                }.ToSettings());
await torrent.StartAsync();
await Task.Run(async () =>
            {
                while (torrent.State != TorrentState.Stopped && torrent.State != TorrentState.Paused && torrent.State != TorrentState.Seeding)
                {
                    if (cancel.IsCancellationRequested)
                    {
                        await torrent.StopAsync();
                        cancel.ThrowIfCancellationRequested();
                        break;
                    }
                    await Task.Delay(1000);
                    this.SpeedChangedEvent?.Invoke(this, torrent.Monitor.DownloadSpeed);
                    this.ProgressChangedEvent?.Invoke(this, torrent.PartialProgress);
                }

                var assetFile = torrent.Files.Single(f => f.Path.StartsWith(asset));
                return File.OpenRead(assetFile.FullPath);
            });
```

**Comment by alanmcgovern** [comment]
V2 torrent support is still very much a work in progress. Today is the first day where monotorrent was able to load and transfer the sample v2 and hybrid torrent files, including transferring v2 hashes if those are downloaded as magnet links. If you're testing v2 torrents, you'll need to compile master from about 15 minutes ago.

I am curious about the webseed issue though. Performance should be reasonably consistent throughout the download as long as the server is active. If perf is dropping off it's nearly definitely an issue with monotorrent. I'll have to check it out!

**Comment by chyyran** [comment]
As of cc8273e89883d5cb6d1f9130a4d132b3718273cc, it seems MonoTorrent now successfully opens a connection to the WebPeers but no pieces are actually exchanged. I'm also suspect of the many connections to the main `archive.org` webseed but it could be a difference in V2 handling?
![image](https://user-images.githubusercontent.com/1000503/174913851-b9bd1da6-ecfc-4f74-9f5e-81f319407e0d.png)

With 2.0.5, exactly 256 pieces are exchanged before the speed drops off. There is only one connection each to each of 2 webseeds, one to `https://archive.org/download/` and one to `http://ia[shard number].us.archive.org/3/items/`

![image](https://user-images.githubusercontent.com/1000503/174913636-507448e9-5094-416b-89c0-bb6c8c117722.png)

**Comment by chyyran** [comment]
With #540 I'm able to finish the download at around 40MB/s on a gigabit connection

**Comment by alanmcgovern** [comment]
That's what I experienced too. 

The way to improve that is to request more data per http invocation. I'd have to double check, but it looks like the data was being requested in chunks of 4MB. There's a latency of about 10-15 seconds for the server to accept the http request, which gives an effective throughput of about 0.5MB/sec. There are two http seeds so that gives a total throughput of nearly 1MB/sec. 

Requesting I'm higher chunk sizes would be less beneficial if there were other peers sharing data. It would also be less beneficial if the server had "normal" latency when serving the response data.

**Comment by alanmcgovern** [comment]
I updated https://github.com/alanmcgovern/monotorrent/pull/540 to make these timeouts configurable. I also increased the default values as per original PR.

Thanks for the report and for testing the tweaks! Hopefully that's the only webseed issue you see :p
