### ISSUE TITLE
CreateHttpStreamAsync inside Docker

### ISSUE THREAD

**Issue by leandroconsiglio** [alanmcgovern/monotorrent#548]
Hi! 
I have been using CreateHttpStreamAsync to generate an URL for streaming in Kestrel without problems. But when I want to run the same code inside a Docker container, CreateHttpStreamAsync hangs forever. I'm exposing the port 5555 in the container which is the one used I think.

Thanks in advance!

**Comment by alanmcgovern** [comment]
Hrm, I just want to double check. Is the issue that the code running inside the docker container 'hangs' and so the call to `CreateHttpStreamAsync` never completes? If so, that nearly definitely means the torrent isn't downloading, and the library is unable to retrieve data for the first and last pieces.

You can test this theory by disabling pre-buffering. Just pass `false` as the value for `prebuffer`:
https://github.com/alanmcgovern/monotorrent/blob/beb6930ce1f568c6b7d1ee803b43eb3034b7945b/src/MonoTorrent.Client/MonoTorrent.Streaming/StreamProvider.cs#L89-L90

If the call doesn't hang when prebuffering is enabled, you can be fairly certain it's that the torrent isn't actively downloading. You can also examine the state of the TorrentManager object to see what's going on. If there's any error in `TorrentManager.Error` that might help diagnose what's happening.

However, I also wonder if this line will be an issue now, or in the near future:

https://github.com/alanmcgovern/monotorrent/blob/beb6930ce1f568c6b7d1ee803b43eb3034b7945b/src/MonoTorrent.Client/MonoTorrent.Streaming/HttpStream.cs#L56 

By binding to localhost then it will be difficult to guarantee the engine is listening at the appropriate address/port in all networking scenarios. If you are having trouble actually connecting to the URL to stream the data, then I am curious if running the docker container with `--network=host` fixes that issue.

I'll update the library to expose this as a configurable setting anyway.

**Comment by alanmcgovern** [comment]
https://github.com/alanmcgovern/monotorrent/pull/549

This will make it possible to bind the internal http listener to any ip/port. `127.0.0.1` is a fine/safe default, but it should be configurable to support all/more scenarios :)

**Comment by leandroconsiglio** [comment]
You were certainly correct, it's working well now. I had not realized that every time I started the container the download started from scratch again. DIsabling the prebuffer made me realize it.

But now even though I have the URL for streaming the torrent, I can't access it from the host. I exposed the port 5555 in the dockerfile and also tried using `--network=host` as you mentioned, but no luck.

**Comment by alanmcgovern** [comment]
Hrm, I would've expected --network=host to have solved that particular problem. It should mean MonoTorrent (running inside the container) is listening on port 5555 on 'localhost' as seen by the host. Therefore the request to "http://127.0.0.1:5555/randomly_generated_guid" should succeed from inside and outside the docker container. 

Are you comfortable compiling the library from source? If so, could you compile the branch I linked above and configure the Http prefix to be something like: "http://public-ip-of-docker-container:port" and ensure you've forwarded that port correctly?

By listening on the public IP of the docker container it should allow apps external to the docker container to directly access it.

If not, I'll finish up tests for that code later today or tomorrow and can do a preview release with the changes. 

Secondly, could you confirm that the http streaming address is non-functional both inside and outside the docker container for --network=bridged and --network=host?

If it works from within the container but not outside the container then this is a much simpler problem to diagnose.

**Comment by alanmcgovern** [comment]
Perfect! That's exactly what I was hoping to hear! Thanks for running the test. 

I'll finalise that branch and ship a preview release. 

Out of curiosity, are you using MonoTorrent 2.x stable, or the 3.x previews? I'm happy enough to backport an equivalent change to the 2.x series if that's what you're currently using.

**Comment by alanmcgovern** [comment]
@leandroconsiglio Alrighty, we should be in a good place now.

I just pushed the changes to nuget.org as part of MonoTorrent 2.0.6. Please update at your convenience at let me know if configuring the new `EngineSettings.HttpStreamingPrefix` property does what you expect!

If it does, we can close this bug out :)

**Comment by leandroconsiglio** [comment]
Well now the problem is that, for example, `http://+:5555/` is not a valid Uri. Is possible set a string to `EngineSettings.HttpStreamingPrefix`? Or maybe another property for that?

**Comment by alanmcgovern** [comment]
Ah whoops, that's a great point! 

Well, you can definitely create a wrapper around LocalStream by copying/pasting HttpStream and fixing it :)

I'll change the API and let it take a pure string. I used URI in a failed attempt to eliminate the need to write string validation logic. Bah! :(

**Comment by leandroconsiglio** [comment]
Great! Thanks for your help! Feel free to close the issue if you consider it

**Comment by alanmcgovern** [comment]
This is fixed in master and the 3.x series in a more durable way. I won't backport it to 2.x as only reasonable way to support '*' or '+' based URI prefixes is to push an API breaking change. The original intention was that the only actual IP addresses/hostnames would be set as the http prefix, which (obviously enough) doesn't happen if someone uses the '*' or '+' notation, which in turn means a 'Uri' object can't be created.

Still, such is life! The refactor in master/3.x allows string based prefixes, and IUriStream has been changed to IHttpStream. The new interface supports '+' or '*' as the prefix :)
