### ISSUE TITLE
TorrentCreatorEventArgs -- OverallCompletion seems not showing the right progress?

### ISSUE THREAD

**Issue by ycy1164656** [alanmcgovern/monotorrent#554]
TorrentCreatorEventArgs -- OverallCompletion seems not to show the right progress, it seems still to show the piece hash progress?

**Comment by alanmcgovern** [comment]
Is this happening with the 2.x release of MonoTorrent?

**Comment by ycy1164656** [comment]
> Is this happening with the 2.x release of MonoTorrent?

Yep

**Comment by alanmcgovern** [comment]
Ah, I think I see the issue. The mechanism used by monotorrent 2.x to hash data in parallel with reading from disk was to partition the list of files. When the partitioning strategy is used, it looks like incorrect values will be reported for the `Overall` progress.

It's *probably* not worth trying to fix this as the code was rewritten to take advantage of better threading primitives as part of the monotorrent 3.0 release series.

The two simplest options are:
1) I can patch 2.x to disabling partitioning. This will have some impact on performance, but will also make this emit correct information.
2) Could you update to a 3.x pre-release?

**Comment by ycy1164656** [comment]
> 
For me , I'll try the 3.x pre-release, it's up to you whether you would fix this issue in 2.x.
Thx!
