### ISSUE TITLE
Need help changing max upload speed while seeding

### ISSUE THREAD

**Issue by rjclarkewp007** [alanmcgovern/monotorrent#555]
Hey!

I need some help changing the MaxUploadSpeed after/while seeding please.

This is basically the code I am using to start seeding. It's more like an on demand seeding option so one can click Seed and only then the seeding will start:

```
private async void button_Seeding_Click(object sender, EventArgs e)
        {
            // Give an example of how settings can be modified for the engine.
            var settingBuilder = new EngineSettingsBuilder
            {
                AllowPortForwarding = true,
                AutoSaveLoadDhtCache = true,
                AutoSaveLoadFastResume = true,
                AutoSaveLoadMagnetLinkMetadata = true,
                AllowLocalPeerDiscovery = true,
                MaximumConnections = 300,

            };

            var torrent = await Torrent.LoadAsync(torrentfile);
            dhtEngine = new DhtEngine(new IPEndPoint(IPAddress.Any, 0));
            TorrentEngine = new ClientEngine(settingBuilder.ToSettings());
            manager = await TorrentEngine.AddAsync(torrent, currentinstalldir);
            manager.TorrentStateChanged += Manager_TorrentStateChanged1;

            await dhtEngine.StartAsync();
            await manager.StartAsync();
        }

private void Manager_TorrentStateChanged1(object sender, TorrentStateChangedEventArgs e)
        {
            while (manager.State == TorrentState.Seeding)
            {
                manager.LocalPeerAnnounceAsync();
                manager.DhtAnnounceAsync();

                label_seeding.Text = manager.State + "... " + ConvertBytesToMegabytes(manager.Monitor.UploadSpeed).ToString("0.00" + " MB/s");
               
            }
        }

```

From here the torrent starts seeding at full speed as expected, but I would like to make use either a textbox or NumericUpDown in Windows Forms to be able to change the max upload speed while seeding. I just don't know where and how to implement this. Any help will be much appreciated!

**Comment by justscribe** [comment]
TorrentSettingsBuilder.MaximumUploadSpeed

**Comment by alanmcgovern** [comment]
As @justscribe said, you can do something like:

```
public async Task UpdateUploadSpeed (TorrentManager manager, int uploadSpeedInBytesPerSecond)
{
    var settings = new TorrentSettingsBuilder (manager.Settings);
    settings.MaximumUploadSpeed = uploadSpeedInBytesPerSecond;
    await manager.UpdateSettingsAsync (settings);
}
```

Let me know if you need any further help!

**Comment by rjclarkewp007** [comment]
Hey there, I tried so many times to get this working, but still cannot get it to work hehe.
When i use that last piece of code then I just keep getting this error:

![image](https://user-images.githubusercontent.com/13123792/200124557-430e9e8f-127d-4b38-a8fc-4a76c571456a.png)

Obviously I'm still missing something here :(

**Comment by rjclarkewp007** [comment]
Not sure if this is important, but I am using static arguments at the very start if my project like this:
![image](https://user-images.githubusercontent.com/13123792/200125433-682e1cb8-37c1-4863-b07b-aba07574a631.png)

Anyway, don't think it is, but here you can see that it doesn't like that setting part:
![image](https://user-images.githubusercontent.com/13123792/200125489-bdd8b6bf-9517-41a3-8bb5-dff6fa22545f.png)

**Comment by uponatime2019** [comment]
> Not sure if this is important, but I am using static arguments at the very start if my project like this: ![image](https://user-images.githubusercontent.com/13123792/200125433-682e1cb8-37c1-4863-b07b-aba07574a631.png)
> 
> Anyway, don't think it is, but here you can see that it doesn't like that setting part: ![image](https://user-images.githubusercontent.com/13123792/200125489-bdd8b6bf-9517-41a3-8bb5-dff6fa22545f.png)

how about `settings.ToSettings();`

**Comment by rjclarkewp007** [comment]
So i used this which i found in another thread:

```
public async Task UpdateUploadSpeed(int uploadSpeedInBytesPerSecond)
        {
            TorrentSettings setmaxupload = new TorrentSettingsBuilder
            {

                MaximumUploadSpeed = uploadSpeedInBytesPerSecond,

            }.ToSettings();
            await manager.UpdateSettingsAsync(setmaxupload);
        }
```
The on the numeric up down button I am using this:

```
private async void numericUpDown1_ValueChanged(object sender, EventArgs e)
        {

            int uploadSpeedInBytesPerSecond = Convert.ToInt32(Math.Round(numericUpDown1.Value * 1000000, 0));
            await UpdateUploadSpeed(uploadSpeedInBytesPerSecond);
        }
```

I used `numericUpDown1.Value * 1000000` to get from bytes to megabytes. Hope that works.
I still need to test it though. Running on a mobile network now so cannot test really :(

**Comment by alanmcgovern** [comment]
Ah yeah, the joys of writing code in comments instead of an IDE.

```
    var settingsBuilder = new TorrentSettingsBuilder (manager.Settings);
    settingsBuilder.MaximumUploadSpeed = uploadSpeedInBytesPerSecond;
    var settings = settingsBuilder.ToSettings ();
    await manager.UpdateSettingsAsync (settings);
```
@uponatime2019 had it right - you need to call `.ToSettings()` on the builder. Sorry for the confusion!
