### ISSUE TITLE
ClientEngine.DownloadMetadataAsync Never completes

### ISSUE THREAD

**Issue by Aaron2550** [alanmcgovern/monotorrent#559]
Hey. Im trying to download the Metadata of Torrents using `ClientEngine.DownloadMetadataAsync`. However, even with 10, 20 or 100 Trackers, nothing ever happens. When trying the same in QBittorrent everything is fine and works almost instantly. My EngineSettings are as follows:
```
EngineSettingsBuilder Builder = new() {
  DhtEndPoint = new IPEndPoint(IPAddress.Parse("<public ip>"), 44444),
  ListenEndPoint = new IPEndPoint(IPAddress.Parse("<public ip>"), 44444),
  MaximumConnections = 5000,
  MaximumHalfOpenConnections = 5000
};
```
Sometimes nothing happens for 10+ hours (ive let this run on my VPS to check) and sometimes it takes only 7 seconds to get the metadata for the same InfoHash with the same Trackers, whats the problem? The port is open both in TCP and UDP.

I'm on .NET 6 - MonoTorrent 3.0.0-beta.rev0034

**Comment by uponatime2019** [comment]
Same problem with default settings metadata wait very long compare to other client

**Comment by alanmcgovern** [comment]
https://github.com/alanmcgovern/monotorrent/issues/561#issuecomment-1302766349

I think this is the underlying issue you're seeing here! I'll push a release in a few minutes and then let me know if it works. The fix described in that comment should reduce the time to fetch metadata from 'a few minutes if you have to go through several rounds of timeouts' to 'a few seconds' as the same data will be requested from multiple peers at the same time.

If you have to wait 10+ hours and metadata is not retrieved, then something else is going wrong. The issue I fixed should still result in metadata being fetched successfully as timeouts would eventually trigger and cause blocks to be re-requested.

I'll go take a look at those timeouts now just in case they're not being triggered in Metadata download mode. If that's the case, this patch should still help a bit, but it won't be foolproof.

**Comment by alanmcgovern** [comment]
Well, that didn't take long. I can confirm the 45 second timeout isn't being applied in this case.

As a result, if any block of data is *not* fulfilled, then the engine will be 'stuck'. The patch mentioned in the other thread will help, as it lessens the likelihood, but I'll fix up this timeout issue now.

**Comment by alanmcgovern** [comment]
@Aaron2550 @uponatime2019 

If either of you are comfortable building/testing from master, could you try that branch? Otherwise I'll do a bit more testing and will try to release a new nuget on Sunday.

**Comment by Aaron2550** [comment]
I saw your first response in my mail inbox but then totally forgot about this...  Its now 1:47 in the morning for me so i cant test it right now ^^ I can try in about 9 hours tho!

**Comment by alanmcgovern** [comment]
No problem at all! I'm away on vacation for a few days, so i won't get back to this until Sunday at the earliest :) Take your time!

**Comment by Aaron2550** [comment]
Seems to help, might be placebo tho ^^ I eagerly await the new nuget release!
