### ISSUE TITLE
Is this correct way to implement custom http client?

### ISSUE THREAD

**Issue by kishanhathiwala** [alanmcgovern/monotorrent#569]
```
var factories = Factories.Default.WithHttpClientCreator(() =>
{
    var client = new HttpClient();
    client.Timeout = TimeSpan.FromSeconds(30);
    return client;
});

var engine = new ClientEngine(settingBuilder.ToSettings(), factories);

```

**Comment by alanmcgovern** [comment]
Yup, that's perfect. Is that not working as expected or were you just curious?

**Comment by kishanhathiwala** [comment]
There are some private trackers that do not recognize this torrent client and so I was trying to update User-Agent by passing User-Agent of qBittorrent. Unfortunately it didn't work even after changing then User-Agent. That could be because they might have blocked my IP or I need to update PeerId. I did some implementation and created a method `WithPeerId` function similar to `WithHttpClientCreator` and passed qBittorrent's Peer Id but it doesn't seem to work. 

Is there anyway to find out (in console app) to see the status of trackers? Something like this (this is taken from qBittorrent)
![image](https://user-images.githubusercontent.com/29030616/200201399-75834ec3-f51b-4046-8c4d-03f6cb1c071b.png)

**Comment by alanmcgovern** [comment]
> There are some private trackers that do not recognize this torrent client and so I was trying to update User-Agent by passing User-Agent of qBittorrent. Unfortunately it didn't work even after changing then User-Agent

Ah, mimicking other clients is something I can't really give advice on.

> Is there anyway to find out (in console app) to see the status of trackers? Something like this (this is taken from qBittorrent)

Yes! 
```
            foreach (var torrent in Engine.Torrents)
                foreach (var trackerTier in torrent.TrackerManager.Tiers)
                    foreach (var tracker in trackerTier.Trackers)
                        Console.WriteLine ($"{tracker.Uri} - Status: {tracker.Status} - Warning: {tracker.WarningMessage}. Failure: {tracker.FailureMessage}.")
```

You can pull statistics out at the tracker tier level, and at the tracker level, so just dump whatever information you're curious about at that point!

**Comment by kishanhathiwala** [comment]
Thank you for the code
