### ISSUE TITLE
Progress file creation is wrong

### ISSUE THREAD

**Issue by Sonic3R** [alanmcgovern/monotorrent#580]
Hi

I'm using latest version of MonoTorrent 2.0.6

I create torrent file from folder, the code of mine looks like:

```
var folder = "D:\\folder1";
var tc = new MonoTorrent.TorrentCreator();
tc.Private = true;
tc.PieceLength =16 * (long)Math.Pow(1024, 2);

tc.Announce = "...";
tc.Hashed += Hashed;

var saveAs = "D:\\test.torrent";

await tc.CreateAsync(new TorrentFileSource(folder), saveAs);
```

and the Hashed:

```
private static int _overall = 0;

private static void Hashed(object sender, TorrentCreatorEventArgs e)
{
			// use int instead of double
			int overall = (int)(e.OverallCompletion * 100);
			var val = Math.Max(overall, _overall);

			if (val != _overall)
			{
				_overall = val;
				Console.WriteLine($"CREATING_TORRENT: {val} %");
			}
}
```

The problem is that creating torrent is reached very fast to 100% and then is waiting for 2-3 minutes in order to save torrent file. Before updating to 2.0.6 where you add async operation, I used non async method, it worked fine and progress shown correctly, at 100% progress the torrent file is created.

**Comment by alanmcgovern** [comment]
@Sonic3R Can you try with the MonoTorrent 3.x pre-releases before i dig too much into the 2.x issue? The 3.x series is nearly ready for release and beta versions are on nuget already :)

**Comment by Sonic3R** [comment]
I encounter that for big folder like 5-10 GB... I will give a try with 3.x version

**Comment by Sonic3R** [comment]
With 3.x error, if I specify folder I get `System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.'` in `TorrentFileSource.cs`

**Comment by alanmcgovern** [comment]
I used a directory with about 14 files, each file was about 850MB. How many files are in your directory?

**Comment by Sonic3R** [comment]
Over thousands of files, but seems that `TorrentFileSource` I used of my own implementation, not from MonoTorrent namespace. Sorry, now seems that works fine
