### ISSUE TITLE
Setting EngineSettingsBuilder.MaximumOpenFiles to 0 prevents hashing from working

### ISSUE THREAD

**Issue by ManlyMarco** [alanmcgovern/monotorrent#595]
Tested on 3.0.0-beta.rev0106

While MaximumOpenFiles xmldocs say that setting it to 0 will result in unlimited file handles, in reality it seems to actually be 0 handles allowed. Hashing never finishes and no torrents can start.

To reproduce:
```cs
    using var client = new ClientEngine(new EngineSettingsBuilder
    {
       MaximumOpenFiles = 0,
    }.ToSettings());

    var torrentPath = @"E:\hi.torrent";
    var contentsPath = @"E:\test";

    var tc = new TorrentCreator
    {
        Name = "test torrent",
    };

    tc.Create(new TorrentFileSource(contentsPath, true), torrentPath);

    var torrent = Torrent.Load(torrentPath);

    var tm = await client.AddAsync(torrent, Path.GetDirectoryName(contentsPath));

    await tm.HashCheckAsync(false);
    // This line is never reached unless MaximumOpenFiles is set above 0
    Console.WriteLine(tm.Progress);
```

**Comment by alanmcgovern** [comment]
Whoops, yes! That's a regression. If you want to work around the problem for now, just set a limit greater than, or equal to, the number of files in a torrent... even setting it to `1000000` files should be fine!
