### ISSUE TITLE
Memory leaks on Asp.Net Core

### ISSUE THREAD

**Issue by trueromanus** [alanmcgovern/monotorrent#603]
Hello, I am facing memory leaks in MonoTorrent with Asp.Net (Kestrel).
All functionality work perfect but right after first run `StartAsync` application begin very quickly take memory, for 10 minutes it occupy in average 20Mb on my machine. It repeated in 100% cases. I tried change some settings but result was same. I checked on different torrent files and on few machines and it also same result. I have prepared a simple test project, you can check it out below. Thanks!

Environment:
`MonoTorrent 3.0.0-beta.rev0106 (also checked on 2.0.7)`
`Windows 10 22H2`

Project file  
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <ItemGroup>
	    <PackageReference Include="MonoTorrent" Version="3.0.0-beta.rev0106" />
    </ItemGroup>
</Project>
```

Source code
```csharp
using MonoTorrent;
using MonoTorrent.Client;
using System.Text;

var builder = WebApplication.CreateBuilder ();
var app = builder.Build ();

app.UseExceptionHandler ( "/error" );

app.UseRouting ();

app.MapGet ( "/", TestClass.TestRoute );

app.Run ();

public static class TestClass {

    private static ClientEngine m_ClientEngine;

    static TestClass () => m_ClientEngine = new ClientEngine ();

    public static async Task TestRoute ( HttpContext context ) {
        var fileStream = File.OpenRead ( @"path to torrent file" );
        var torrent = await Torrent.LoadAsync ( fileStream );
        var manager = await m_ClientEngine.AddAsync ( torrent, "Downloads" );
        await manager.UpdateSettingsAsync ( new TorrentSettingsBuilder ( manager.Settings ) { MaximumConnections = 40, AllowInitialSeeding = false }.ToSettings () );
        await manager.StartAsync ();

        await context.Response.Body.WriteAsync ( Encoding.UTF8.GetBytes ( "result" ) );
    }
}
```

**Comment by OneFingerCodingWarrior** [comment]
Does the memory occupied keep going up and never drop down? It's pretty normal for Monotorrent occupied 20MB memory.

**Comment by trueromanus** [comment]
> Does the memory occupied keep going up and never drop down? It's pretty normal for Monotorrent occupied 20MB memory.

It keeps taking up memory and never drop down. I left the app running for a few hours and it occupy took up 200MB for a few hours. I understand if this can take up memory when downloading files, but it happened even after the file was already downloaded (on seed stage).

**Comment by alanmcgovern** [comment]
Could you profile the app using JetBrains' DotMemory profiler, or any other profiler you're familiar with?

If you use DotMemory you can share the profiling session with my by exporing the workspace. That'd make my life much easier in figuring out what's going on.

Otherwise, use whatever tool you're familiar with and based on your analysis of what's consuming the memory I should be able to make progress! There's definitely nothing unusual with the sample app you shared, so i'm a bit confused as to what could be causing the issue. I'll try to reproduce it using your sample anyway!

**Comment by alanmcgovern** [comment]
This is roughly what memory usage is like for me while downloading 6 torrents concurrently, and after having downloaded over 20GB of data.

![overall](https://user-images.githubusercontent.com/264396/213942626-cc00ad8e-5991-401f-bbd0-b635d98640cf.png)

Memory stabilised at around 70-80MB at least 10 minutes ago. I'll leave it running for another while before taking a snapshot to see if anything looks suspicious.

**Comment by trueromanus** [comment]
Hello @alanmcgovern, I make deep investigation and find memory leak in myown source code. In example that I share above I also checked and find it has limit in 200Mb, after it memory not growing with many active torrents in long period of time. Thanks for you check and sorry for interruption. I closed issue.

**Comment by alanmcgovern** [comment]
Phew!

That's great - I was getting a bit worried there was something I was missing. These kinds of issues are pretty hard to reproduce independently. I have found some before when people shared profiling data from their own apps though!

Glad to see it's sorted now!
