### ISSUE TITLE
Crash when trying to load a torrent file that was just created

### ISSUE THREAD

**Issue by ManlyMarco** [alanmcgovern/monotorrent#610]
Works fine in 2.0.7 but breaks in 3.0.0-beta.rev0106 (Edit: happens on a master build as well)

Exception:
```
MonoTorrent.TorrentException: Inconsistent hybrid torrent, mismatch in v1 and v2 files.
   at MonoTorrent.Torrent.ProcessInfo(BEncodedDictionary dictionary, PieceHashesV1& hashesV1, Boolean& hasV1Data, Boolean& hasV2Data)
   at MonoTorrent.Torrent.LoadInternal(BEncodedDictionary torrentInformation, RawInfoHashes infoHashes)
   at MonoTorrent.Torrent..ctor(BEncodedDictionary torrentInformation, RawInfoHashes infoHashes)
   at MonoTorrent.Torrent.Load(Stream stream, ReadOnlySpan`1 buffer)
   at MonoTorrent.Torrent.Load(String path)
   at Program.<Main>$(String[] args) in Program.cs:line 183
```
Code:
```cs
var tc = new TorrentCreator
{
    Announce = trackerAnnounceStringHttp,
    Comment = "...",
    CreatedBy = "...",
    Name = name,
    Private = true,
    StoreMD5 = false,
};
// Write the torrent file, overwrite existing
tc.Create(new TorrentFileSource(contentsPath, true), torrentPath);

var torrent = Torrent.Load(torrentPath);
```

I can send the created torrent file if necessary. `contentsPath` contains around 10 files in a single directory, nothing special maybe except for some files having Japanese characters in their file names.

Edit: The exact same torrent file generated by 2.0.7 loads without issues in beta builds.
Edit2: Torrent file generated by 2.0.7 is 10KB while one generated by a master build is 25KB.

**Comment by ManlyMarco** [comment]
It appears to be caused by file names specifically. I can get it to happen by creating a torrent with files named:
```
ASDkfsdjgsdSDFGsj.asd
aSvzxkaSqp AZXDCaj asdASDjas ASDl.aaaaaa
[aaaaa aaaaaaaaa]aaaaaa a aaaaaaaa.aaaaa
```
Contents don't seem to matter, it happens both when there is a single space character in all files as well as if I try putting random text in the files.

**Comment by alanmcgovern** [comment]
Oh, interesting. Hrmm, i was originally going to suggest that the issue might be related to https://github.com/alanmcgovern/monotorrent/tree/fix-padding-with-empty-files . Hybrid torrents (or v1 torrents with padding enabled) are still susceptible to a bug where the padding is attributed to the 'closest' file instead of the 'closest non-empty' file.

The spec for these things is pretty vague ( http://ll.www.bittorrent.org/beps/bep_0047.html ) so i'm finding most of the issues by creating files with arbitrary content using another library which supports BEP47/BEP52 and then trying to figure out what the difference is. It's slow going :( 

If an issue can be replicated with those three filenames, that's new and interesting! I'll dig into that now, and then merge the fix for your issue alongside the fixes in the empty-files branch (that branch just needs some thorough tests covering the edge cases I've identified).

**Comment by alanmcgovern** [comment]
![huh](https://user-images.githubusercontent.com/264396/215179526-0effacc6-f64b-4b25-954e-c4b77ff8c15c.png)

Well, that's unusual! 😆

**Comment by alanmcgovern** [comment]
```

**Comment by ManlyMarco** [comment]
The joys of .Net being culture-specific instead of invariant/ordinal by default, I've had plenty of a bug like this ;-)

By the way, the malformed torrent file seems to work just fine in qBittorrent and uTorrent 2.x.

**Comment by alanmcgovern** [comment]
The BEP52 (bittorrent v2) spec says:

> For interoperability with BEP 3 (bittorrent v1) a torrent can be created to contain the necessary data for both formats. To do so the 'pieces' field and 'files' or 'length' in the info dictionary must be generated to describe the same data in the same order. Since the old format did not align files to piece boundaries a multifile torrent must use BEP 47 padding files to achieve identical alignment.

I don't want to think *too* hard about the implications of files being in different orders in the 'bep3' or 'bep52' listing within the .torrent metadata. I assume that there'll be an oops at some point and data transmitted by a particular peer won't match the expected piece hash, and so the peer will be dropped. But *one* of the peers will send the correct data and it'll all be ok in the end?

**Comment by alanmcgovern** [comment]
> By the way, the malformed torrent file seems to work just fine in qBittorrent and uTorrent 2.x, other than showing the padding as a file.

I'm curious enough to try it now and see what happens :p

**Comment by ManlyMarco** [comment]
> I assume that there'll be an oops at some point and data transmitted by a particular peer won't match the expected piece hash, and so the peer will be dropped. But _one_ of the peers will send the correct data and it'll all be ok in the end?

Wait, that sounds like the intermittent issue I've been having where the sole client never starts a download from the seed. It seems to happen randomly, and if it does happen then it will keep happening across different client restarts, but after giving it a break and starting the client again it often begins downloading normally.

**Comment by alanmcgovern** [comment]
![broken](https://user-images.githubusercontent.com/264396/215186834-573eda4a-bae8-4435-8e5b-019cc5575550.png)

I created a torrent using mis-ordered keys and qBitTorrent 4.4.0 refuses to load it too. I'm surprised you were able to load the malformed torrent in it. I'm not sure if uTorrent supports BEP52 - i'd assume clients which do not support BEP52 would have no issues loading the malformed torrent as they'd ignore the BEP52 parts, and so the mismatch is irrelevant.

I attached the broken and fixed files here. If you extract the zip you can check the keys using any bencoded file viewer to see the difference. Maybe some clients try to work around it by treating the hybrid torrent as being *just* v1, or *just* v2 and hoping that the version they choose will result in a working download?

[broken-and-fixed.zip](https://github.com/alanmcgovern/monotorrent/files/10522723/broken-and-fixed.zip)

**Comment by ManlyMarco** [comment]
Both of the broken and fixed torrent files seem to work fine. I add them by dragging the torrent file in.
![image](https://user-images.githubusercontent.com/39247311/215189416-fb274757-fb6e-4cd8-9946-2e45a21cc7f1.png)
![image](https://user-images.githubusercontent.com/39247311/215189595-87879bbc-9c7e-47e2-892e-cfb2800ebc12.png)

**Comment by alanmcgovern** [comment]
> Wait, that sounds like the intermittent issue I've been having where the sole client never starts a download from the seed. It seems to happen randomly, and if it does happen then it will keep happening across different client restarts, but after giving it a break and starting the client 20 minutes later or so it often begins downloading normally

Maybe? If monotorrent is on the downloading side, keep tabs on the `TorrentManager.HashFails` property, or  the `PieceHashed` event, and see if peers are being dropped/blocked as a result of transmitting bad data. If connections are lost and that isn't being incremented, something else is going on

**Comment by ManlyMarco** [comment]
It is monotorrent on both sides, I'll add logging for these events and see what happens then.

**Comment by alanmcgovern** [comment]
Ah that makes sense. You have qbittorrent 4.3.2 which doesn't support bittorrent v2. The release notes for 4.4.0 has:

> FEATURE: Support for v2 torrents along with libtorrent 2.0.x support (glassez, Chocobo1)

The same is true for your version of utorrent - it doesn't support bittorrent v2 either, so it's ignoring that data. A client which correctly loads hybrid torrents will display both infohashes:

![both_hashes](https://user-images.githubusercontent.com/264396/215190846-55bb67fc-cfad-4599-8bd3-c830b486b0f4.png)
