### ISSUE TITLE
TorrentManager.MoveFileAsync seems to still only work when stopped in v3.0.0-beta-0159

### ISSUE THREAD

**Issue by ManlyMarco** [alanmcgovern/monotorrent#622]
Trying to use TorrentManager.MoveFileAsync while downloading still throws. Looking at disassembly of the v3.0.0-beta-0159 nuget package, the `if (this.State != TorrentState.Stopped)` check is still there inside `TorrentManager.MoveFileAsync` and `TorrentManager.MoveFilesAsync`.

**Comment by alanmcgovern** [comment]
huh, I wonder what happened to that change! It was supposed to have been in the branch I merged.

https://github.com/alanmcgovern/monotorrent/pull/604/files

Did I accidentally revert that in a different PR!?

**Comment by alanmcgovern** [comment]
oh ffs. that's the wrong if statement I removed.
