### ISSUE TITLE
TryVerify error while load a torrent which source file is large and torrent type is v1v2hybird

### ISSUE THREAD

**Issue by ycy1164656** [alanmcgovern/monotorrent#631]
I created a 40gb file's torrent with default type, when I load the torrent, 

this line would occur an error

![image](https://user-images.githubusercontent.com/8970351/218507973-09d4a90c-002e-4715-a646-59c2b21af511.png)

but v1only torrent would be ok

**Comment by ycy1164656** [comment]
![image](https://user-images.githubusercontent.com/8970351/219034698-a07cbcaa-8d53-4de3-a249-7edc394641a1.png)

**Comment by LambdaRan** [comment]
I also encountered this problem, have you solved it? @ycy1164656

**Comment by alanmcgovern** [comment]
This should be solved in master, and also the latest beta release in NuGet. Thanks for reporting!

**Comment by alanmcgovern** [comment]
Specifically - this should have resolved the problem: https://github.com/alanmcgovern/monotorrent/commit/c766bc86d9fba1717ce9b86f6763e187c9987863
