### ISSUE TITLE
Download Multiple Torrents

### ISSUE THREAD

**Issue by sekkit** [alanmcgovern/monotorrent#635]
If I wanna download multiple torrents, shall I create multiple engines or just download them with single engine instance?

**Comment by bdavis2-PCTY** [comment]
I download multiple torrents using the same engine with no issues.

**Comment by alanmcgovern** [comment]
both work fine. I'd recommend multiple torrents in one engine though. Upload/download rate limits are calculated on a per-engine basis, so if you want to limit all torrents to a specific bandwidth allowance, it's easier with one engine.

For most other things, the difference is negligible.
