### ISSUE TITLE
Question: are there any advantages of `ReusableTask` over `ValueTask`

### ISSUE THREAD

**Issue by lostmsu** [alanmcgovern/monotorrent#652]
I read your blog post, and you never mentioned `ValueTask` there.

**Comment by alanmcgovern** [comment]
They're slightly different in what they do.

When ValueTask was originally released it allowed a zero-allocation fastpath when operations completed asynchronously. When operations completed synchronously then it allocated a regular `Task` + all the usual machinery.

It was then updated to support zero allocation asynchronous operations too. `ReuseableTask` is effectively the same as the new version of ValueTask, and could likely be reimplemented as an `IValueTaskSource ` / `ManualResetValueTaskSourceCore` but i haven't looked into it too much.

I did some benchmarking/optimisations recently and this is an example of one benchmark where `ReusableTask` caches/reuses more data than `ValueTask` as it exists in .NET 8.0.

https://github.com/alanmcgovern/ReusableTasks/pull/7
