### ISSUE TITLE
MonoTorrent is unable to transmit files >2GB

### ISSUE THREAD

**Issue by lostmsu** [alanmcgovern/monotorrent#657]
plz see pull request https://github.com/alanmcgovern/monotorrent/pull/656 for an end-to-end integration test

The first issue I am hitting is inability to create a v2 torrent (did not test v1) that would include such a file due to `ArgumentOutOfRangeException`:
 

>    IPieceWriterExtensions.ReadFromFilesAsync(IPieceWriter writer, ITorrentManagerInfo manager, BlockInfo request, Memory`1 buffer) line 47
>     ReusableTaskAwaiter`1.GetResult()
>     MemoryCache.ReadAsync(ITorrentManagerInfo torrent, BlockInfo block, Memory`1 buffer) line 142
>     ReusableTaskAwaiter`1.GetResult()
>     DiskManager.ReadAsync(ITorrentManagerInfo manager, BlockInfo request, Memory`1 buffer) line 490
>     ReusableTaskAwaiter`1.GetResult()
>     DiskManager.GetHashAsync(ITorrentManagerInfo manager, Int32 pieceIndex, PieceHash dest) line 375
>     DiskManager.GetHashAsync(ITorrentManagerInfo manager, Int32 pieceIndex, PieceHash dest) line 399
>     ReusableTaskAwaiter`1.GetResult()
>     TorrentCreator.CalcPiecesHash(ITorrentManagerInfo manager, CancellationToken token) line 424
>     TorrentCreator.CreateAsync(String name, ITorrentFileSource fileSource, CancellationToken token) line 294
>     TorrentCreator.CreateAsync(ITorrentFileSource fileSource, CancellationToken token) line 241
>     IntegrationTestsBase.CreateAndDownloadTorrent(TorrentType torrentType, Boolean createEmptyFile, Boolean explitlyHashCheck, Int32 nonEmptyFileCount, Boolean useWebSeedDownload, Int64 fileSize) line 197
>     IntegrationTestsBase.DownloadFileInTorrent_V2_Empty_And_BigNonEmpty() line 113

I have my own fork where I replaced a few `int`s and floating point math with `long`s: https://github.com/lostmsu/MonoTorrent/commit/08893f77938d224a5b3ccb56e6e0c048a7de2e71 , but even with that fix for some reason creating a torrent succeeds, but when attempting to seed >2GB files fail hash check.

**Comment by lostmsu** [comment]
FYI, the abovementioned commit 08893f77938d224a5b3ccb56e6e0c048a7de2e71 has a couple of critical bugs in `IntMath`. It should look like this instead:

```csharp
using System;

namespace MonoTorrent
{
    static class IntMath
    {
        public static long PowUnchecked (long value, int power)
        {
            if (power < 0)
                throw new ArgumentOutOfRangeException (nameof (power), "Power must be greater than or equal to zero");
            if (power == 0)
                return 1;
            return (power & 1) == 0
                ? PowUnchecked (value * value, power >> 1)
                : value * PowUnchecked (value, power - 1);
        }

        public static long Pow (long value, int power)
        {
            if (power < 0)
                throw new ArgumentOutOfRangeException (nameof (power), "Power must be greater than or equal to zero");
            if (power == 0)
                return 1;
            return checked((power & 1) == 0
                ? Pow (value * value, power >> 1)
                : value * Pow (value, power - 1));
        }

        public static int Pow (int value, int power)
        {
            if (power < 0)
                throw new ArgumentOutOfRangeException (nameof (power), "Power must be greater than or equal to zero");
            if (power == 0)
                return 1;
            return checked((power & 1) == 0
                ? Pow (value * value, power >> 1)
                : value * Pow (value, power - 1));
        }
    }
}

```

**Comment by alanmcgovern** [comment]
@lostmsu Things should be good now! I'm curious if the latest version of `master` from this repo now supports your usecase without needing modifications.

If you still need tweaks, let me know!
