### ISSUE TITLE
Suspicious code in `TorrentCreator.CalcPiecesHash`

### ISSUE THREAD

**Issue by lostmsu** [alanmcgovern/monotorrent#658]
Please see https://github.com/alanmcgovern/monotorrent/blob/18fa8189430e44b101148b0a3c64caaacab5929c/src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs#L458

Here the `previousAppend` variable is never modified and is always `ReusableTask.CompletedTask`

BTW AFAIR `ReusableTask` can not be awaited multiple times...

**Comment by alanmcgovern** [comment]
That should be resolved now - it was dead code! I also made some minor tweaks to the code to improve parallelisation.

That was a good spot! Thanks for the report!

> BTW AFAIR ReusableTask can not be awaited multiple times...

That's true, but there are caveats. The one caveat you can rely on is that it's always safe to `await default(ReusableTask`. i.e. you can await a zero-inited reusable task. It's treated as a successfully synchronously completed task. `ReusableTask.CompletedTask` is (currently) implemented as: `return default`, which returns that kind of empty struct.
